### ISSUE TITLE
16p11.2

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#1001]
Add16p11.2 to list of epilepsy causes

**Comment by mbarton** [comment]
*Copying across discussion from an internal email thread by @eatyourpeas*

@coldunk, 16p11.2 microdeletions are either proximal or distal. You can also delete the whole locus (16p11.2 deletion syndrome) and you can have the opposite, that is microduplications.

- 16p11.2 deletion syndrome is 699307007
- 16p11.2 proximal microdeletion syndrome 718227006
- 16p11.2 distal microdeletion syndrome 733521003
- 16p11.2 microduplication syndrome 765142003

Can I check you are after the first one, or should we include any of the others?
