### ISSUE TITLE
Add epilepsy causes: 16p11.2 microduplication, HCN1 pathological variant and 2p16 microdeletion

### ISSUE THREAD

**Issue by nikyraja** [rcpch/rcpch-audit-engine#1005]
Hello,

Please could the following epilepsy causes be added to the platform. 
16p11.2 microduplication ; SCTID: 699307007
HCN1 pathological variant related epilepsy ; none
2p16 microdeletion ; none

Some don't have snowmed codes, is that okay?

**Comment by eatyourpeas** [comment]
The 16p microduplication I added along with the deletion last week.
The others we shall have to add to the admin directly. Is that the exact wording you would like?

**Comment by nikyraja** [comment]
yes please!

**Comment by nikyraja** [comment]
I've (hopefully) added HCN1 pathological variant related epilepsy & 2p16 microdeletion onto the platform, and Simon has added 16p11.2 microduplication.
