### ISSUE TITLE
Password setting/resetting emails arriving late

### ISSUE THREAD

**Issue by nikyraja** [rcpch/rcpch-audit-engine#1006]
We've had multiple users that say the link to set/reset their passwords are only arriving in their inboxes hours after they have requested this. Is this something we could check as I know the links are supposed to come through straight away?

The users have also spoken to their Trust IT and confirmed that their firewall isn't blocking the emails.

**Comment by mbarton** [comment]
Thanks for the report @nikyraja. I can't see any obvious reason, we did rotate some credentials used to send email last week but they should have been set up with the same capability as before.

I will try and access the system we use for sending email to see if there's any further information there

**Comment by eatyourpeas** [comment]
I have noticed this before on occasion, but usually late in the evening. This will be an issue with our email provider sendgrid/mailgun

**Comment by mbarton** [comment]
We have checked SendGrid for logs of an affected user and it seems like the email was delivered as expected.

We’ve updated the SPF record in our DNS, although it shouldn’t matter as SendGrid take care of that.

If you get more reports @nikyraja let us know, although with NHS emails it may be difficult to debug as it’s such a big provider

**Comment by nikyraja** [comment]
Thanks for checking! Will let you know if we get any further reports from users.
