### ISSUE TITLE
NHS/CHI number validation

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#101]
This needs implementing within the case form.

**Comment by anchit-chandran** [comment]
probably not an issue as [English,Wales numbers start above 4M
](https://en.wikipedia.org/wiki/NHS_number#:~:text=The%20current%20system%20uses%20a,and%20600%20000%20000%20upwards.) but current implementation means a NHS valid number starting with 0, when converted to a string in `nhs_number.py`, removes the zero, leading to an incorrect error message of "The NHS Number must be exactly 10 digits long."


![Image](https://user-images.githubusercontent.com/68898006/228258715-abd58324-1ccb-4ea9-ad22-467d93680fee.png)



![Image](https://user-images.githubusercontent.com/68898006/228259553-3d62df04-f479-4f45-90ec-20e8c0bfffb4.png)
