### ISSUE TITLE
Adding Treatments: Brivaracetam & Cenobamate 

### ISSUE THREAD

**Issue by SAbdin93** [rcpch/rcpch-audit-engine#1010]
Can we please add the following under treatments:

Brivaracetam & Cenobamate 

(Colin has approved)

Thank you so much,

**Comment by eatyourpeas** [comment]
Sure @SAbdin93 thank you. Can I check these are both rescue medicines?

**Comment by SAbdin93** [comment]
Hi @eatyourpeas I've checked with Colin and he's confirmed that they are regular ongoing meds and not rescue medicines.
