### ISSUE TITLE
Making 'guidance' tab visible when not logged in

### ISSUE THREAD

**Issue by nikyraja** [rcpch/rcpch-audit-engine#1012]
Currently, the guidance tab is only visible when users are logged in:
<img width="899" alt="logged in" src="https://github.com/user-attachments/assets/034fc68b-b427-4694-a6dc-953735d02721">

This is what users see before they log in:
<img width="929" alt="not logged in" src="https://github.com/user-attachments/assets/24dca842-a388-440f-90ec-3dd8824b136e">

Please could we make the guidance tab always visible, so that users can easily access this without having to sign in. This is also important because the information within the guidance tab is relevant to everyone visiting the site, regardless of whether they have an account or not, eg. contains user permission settings, info on the KPIs etc.

**Comment by mbarton** [comment]
@eatyourpeas does this need deploying to live?

**Comment by eatyourpeas** [comment]
Development is up to date but nothing is in live for the last few issues
S

From: Michael Barton ***@***.***>
Date: Monday, 12 August 2024 at 09:59
To: rcpch/rcpch-audit-engine ***@***.***>
Cc: Simon Chapman ***@***.***>, Mention ***@***.***>
Subject: Re: [rcpch/rcpch-audit-engine] Making 'guidance' tab visible when not logged in (Issue #1012)

@eatyourpeas<https://github.com/eatyourpeas> does this need deploying to live?
