### ISSUE TITLE
Terms of Agreement - Location 

### ISSUE THREAD

**Issue by SAbdin93** [rcpch/rcpch-audit-engine#1014]
Hiya,

We received a query in relation to accessing the Terms of Agreement on the platform. After speaking to Niky she has asked me to raise an issue here on Github. 

Would it be possible to add this link: https://e12.rcpch.ac.uk/docs/legal/terms-of-service/    to the text that reads "Terms of Agreement" as a hyperlink? I have included a screenshot of the location below. 

![Terms and Conditions](https://github.com/user-attachments/assets/ab3b56be-80df-47d1-ad72-eb79bcb321de)

Thank you,

Saleema

**Comment by eatyourpeas** [comment]
Thanks for this @SAbdin93 - now live in development. Will merge into live soon.
