### ISSUE TITLE
Make seizure description question non mandatory

### ISSUE THREAD

**Issue by nikyraja** [rcpch/rcpch-audit-engine#1015]
Some users have fed back that they would like the free text box within the episode description questions (4 Multiaxial diagnosis, DESSCRIBE definitions) to be made non-mandatory.
<img width="515" alt="Seziure description screenshot" src="https://github.com/user-attachments/assets/d0b9f169-7a17-41e4-a87e-a4f11681cc3d">
- The Yes/No question would remain mandatory, but users would have the choice to add a free text description

The Methodology & Dataset group agreed with this change. 

Would this be possible? Would it mess too much with the scoring of question completion etc?

**Comment by eatyourpeas** [comment]
This is an implementation in a branch:
<img width="702" alt="image" src="https://github.com/user-attachments/assets/012c106d-894b-4385-9413-d2dadc19d6be">
As illustrated, the user still has to score whether history was or was not gathered, but leaving the description blank is optional.
It is important that the data group understand though that this will mean it is unlikely to be completed by users and the spin off plan to validate key words to improve on those published by the ILAE will lose much of its validity. I have updated the explanation to reflect this. Of course happy to change the wording here.
Let me know if this is ok and I will make the changes and merge.

**Comment by nikyraja** [comment]
Hi Simon, thank you that looks great! 

Completely agree that users are unlikely to complete non-mandatory questions, however we agreed that this is okay for now because we are not analysing this data directly and we want to continue reducing the data burden for clinical teams. This is something that we could re-visit later. 

Please could the text just be edited to:
"Optional Question - Please include a freehand description of the episodes as recorded in the patient notes, using as much detail as you can (2000 character max). Key words with an agreed ILAE meaning will be automatically labelled and facilitate future word analyses to help broaden ILAE description lists."

Otherwise, happy for this to be made live.
