### ISSUE TITLE
New user log in issue - New Platform

### ISSUE THREAD

**Issue by SAbdin93** [rcpch/rcpch-audit-engine#1021]
Hi, 

A clinician has emailed to let us know that he is unable to set his password as his account has not been activated. When I have logged in to send him a password reset link I am unable to do so as it says he has not completed the sign up process. A small blue icon appears next to his name and I am not able to click onto his details.

![image](https://github.com/user-attachments/assets/d784d038-a9f5-4196-b860-ba8b66fba868)

Could you please advise?

Thanks,

Saleema

**Comment by mbarton** [comment]
Thanks for reporting @SAbdin93 I will contact you directly about this

**Comment by mbarton** [comment]
We don't have anything in the logs indicating how this user ended up unregistered, perhaps they were not receiving our email.

I've manually confirmed their email and set them as active so we can send a password reset link.

I couldn't work out how to do it in the Django admin so I ran the following Python code in the Django shell on the machine itself:

```python
>>> user = Epilepsy12User.objects.filter(email = "<redacted_email>").first()
>>> user
<Epilepsy12User: <redacted name>
>>> user.is_active
False
>>> user.email_confirmed
False
>>> user.is_active = True
>>> user.email_confirmed = True
>>> user.save()
INFO [epilepsy12.signals:69] <redacted name> (<redacted email>) updated by None.
```
