### ISSUE TITLE
Registering Lancaster Royal Infirmary 

### ISSUE THREAD

**Issue by SAbdin93** [rcpch/rcpch-audit-engine#1027]
Hi 

Can the Lancaster Royal Infirmary  be registered to the Morecambe Bay Hospital Trust audit. They are already registered for Furness General Hospital.

NHS Trust Site - ROYAL LANCASTER INFIRMARY (RTX02)
ASHTON ROAD
LANCASTER
LANCASHIRE
LA1 4RP

Thank you

**Comment by eatyourpeas** [comment]
Hi. This organisation currently does not exist in our database. We can definitely add with the information you have given.
Can you confirm this is what we must add, and these are the correct relationships? In particular, which Epilepsy Network does it fall under?

ROYAL LANCASTER INFIRMARY (RTX02)
ASHTON ROAD
LANCASTER
LANCASHIRE
LA1 4RP

It is overseen by University Hospitals of Morecambe Bay NHS Foundation Trust
ICB: Lancashire and South Cumbria ICB
NHS Region: North West
Epilepsy Network: awaited

**Comment by nikyraja** [comment]
Hi Simon, yes please can you add this as a new organisation that sits under University Hospitals of Morecambe Bay NHS Foundation Trust?

The ICB and region are correct above, and the OPEN UK network would be 'North West Children and Young People's Epilepsy Interest Group' (NWIG)

Thanks,

**Comment by eatyourpeas** [comment]
longitude: -2.800053987227962, 
latitude: 54.042662416624204
opened: 01/04/1998

**Comment by eatyourpeas** [comment]
<img width="1342" alt="image" src="https://github.com/user-attachments/assets/b2d5fcec-40eb-4309-9289-a928527c41cf">

**Comment by SAbdin93** [comment]
Thanks Simon!

Kind Regards,

Saleema Abdin
Epilepsy12 Project Coordinator
Royal College of Paediatrics and Child Health
Telephone: 020 7092 6157
Website: www.rcpch.ac.uk/epilepsy12<http://www.rcpch.ac.uk/epilepsy12>
Twitter: @epilepsy_12

Leading the Way in Children's Health
The Royal College of Paediatrics and Child Health (RCPCH) is a registered charity in England and Wales (1057744) and in Scotland (SC038299)
