### ISSUE TITLE
Opt Out - clinician facing

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#103]
What is currently presented as a lock field should  be changed to an opt out. If this is True, the record should be deleted, with the primary key remaining as a reminder that the record existed.

- [x] refactor lock to opt out
- [x] opt out to delete record on select.
- [ ] warning dialog box
- [ ] only edit access to opt out field

**Comment by eatyourpeas** [comment]
fixed by PR #136

**Comment by pacharanero** [comment]
@eatyourpeas were the bullets

warning dialog box
only edit access to opt out field

completed?

**Comment by eatyourpeas** [comment]
Those 2 elements not addressed no. Was planning to address when tackling this issues from the point of view of patients (#104). Could reopen this if you prefer.
