### ISSUE TITLE
Add new cause to the platform: Mesial temporal lobe epilepsy with hippocampal sclerosis & Interstitial heterozygous deletion 2q13 to 2q14.1

### ISSUE THREAD

**Issue by SAbdin93** [rcpch/rcpch-audit-engine#1038]
Hi, 

Could we please have the following causes added to the platform:

"Mesial temporal lobe epilepsy with hippocampal sclerosis" - SCTID: 770643005

"Interstitial heterozygous deletion 2q13 to 2q14.1" - No code 

Thank you! 
Saleema

**Comment by eatyourpeas** [comment]
these are now present in live and staging
