### ISSUE TITLE
Guidance tab not working on Platform

### ISSUE THREAD

**Issue by SAbdin93** [rcpch/rcpch-audit-engine#1041]
Hiya, 

I've received an email from a clinician getting the following message when trying to access the guidance tab on the platform: "The link you are accessing has been blocked by the Barracuda Web Security Gateway". She has checked with her IT team who have told her that they have checked the webpage and can not access it either.

I have just checked and I get a similar error message: "It looks like the webpage at https://epilepsy12docs.rcpch.tech/ might be having issues or it may have moved permanently to a new web address."

Could you kindly look into this?

Thanks so much! 

Saleema

**Comment by mbarton** [comment]
Thanks for the report Saleema, I suspect I broke this when we moved our underlying hosting infrastructure. I will look into it with priority

**Comment by SAbdin93** [comment]
Thanks Michael! 😊

Kind Regards,

Saleema Abdin
Epilepsy12 Project Coordinator
Royal College of Paediatrics and Child Health
Telephone: 020 7092 6157
Website: www.rcpch.ac.uk/epilepsy12<http://www.rcpch.ac.uk/epilepsy12>
Twitter: @epilepsy_12

Leading the Way in Children's Health
The Royal College of Paediatrics and Child Health (RCPCH) is a registered charity in England and Wales (1057744) and in Scotland (SC038299)

**Comment by mbarton** [comment]
Sorry again for the issues - it is totally my fault.

Just commenting to confirm this is related to the infrastructure changes I made. I think I know how to fix it but it will be tomorrow before I can deploy the fix.

**Comment by SAbdin93** [comment]
No worries Michael! Thank you for looking into it :)

**Comment by mbarton** [comment]
This is now fixed, thanks again for reporting @SAbdin93 

Fixed in #1042
