### ISSUE TITLE
Add organisational audit banner to organisation dashboard 

### ISSUE THREAD

**Issue by nikyraja** [rcpch/rcpch-audit-engine#1059]
Add a banner onto the organisation dashboard, visible to Lead clinicians and us, to direct people to the organisational audit when open.

“The 2024 Organisational Audit is now open. Please complete data entry[link] by 14 January 2025.”
- Either hyperlink or via additional button.

**Comment by mbarton** [comment]
I think we could make this generic in the Django admin and fix #882 (at least the Announcements part of it)
