### ISSUE TITLE
Deprivare maintenance

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#106]
Deprivation scores use the MySociety [standardised UK score[(https://www.mysociety.org/2021/04/22/unified-uk-measures-of-rurality-and-deprivation/) thanks to the remarkable work of @ajparsons and @mwardle. 
Questions therefore to @hstac and @coldunk 
1. are you happy to use this or should we report IMD based on the individual countries?
2. our server will need periodic update to ensure all versions of @mwardle deprivare are most current.

**Comment by pacharanero** [comment]
### Discussed in E12 meeting 10.03.2023
@coldunk: Core 20+5 seems to be driving national policy around this, we also want the type of IMD score we use to be common across all of RCPCH audits.

Action: @AmaniKrayemRCPCH will ask Saira for a decision.

**Comment by AmaniKrayemRCPCH** [comment]
Discussed with RCPCH data analysts. Current approach is calculating the quintiles for each country separately, then merging the quintiles. 
Saira - "Let’s say the scores for England go from 1 to 32844, you will create a new variable/column where the first 25% will be equal 1, second 25% equal 2 and so on. Then you will do the same for Wales, where the scores go from 1 to 1909. 
Then you will be comparing 1 “Most deprived quintile” in England with 1 “Most deprived quintile” in Wales. You can put them together in the same graph."

**Comment by eatyourpeas** [comment]
thank you @AmaniKrayemRCPCH 
I have built a new service [here](https://github.com/rcpch/rcpch-census-platform) that reports deprivation against a postcode. We can use this to generate quantiles of whatever size you need to produce a column chart with deprivation grouped by country etc.
