### ISSUE TITLE
[Organisational audit] - description at top of submission page

### ISSUE THREAD

**Issue by nikyraja** [rcpch/rcpch-audit-engine#1060]
Add the following description at the top of the organisational audit page:

“Please complete the 2024 Organisational Audit for your Trust/Health Board, to describe your epilepsy service as of 1 November 2024. Please complete your data entry by 23:59 on 14 January 2025. 
This form has been pre-populated with data from your most recent organisational audit submission. Please note, you will still need to submit/accept the data before the above deadline.”

Have submit/accept button either at top or bottom of the page – only visible if the form is prepopulated.

**Comment by mbarton** [comment]
I reworded this a bit - @nikyraja is it ok?

![Screenshot 2024-10-15 12 42 18](https://github.com/user-attachments/assets/c48b918f-e2b9-4345-a539-04f9f082dcf5)

**Comment by nikyraja** [comment]
Could we edit the first bit to 'Please answer to reflect your epilepsy service as of 1 November 2024 and submit..' ?

Otherwise, looks good!
