### ISSUE TITLE
Error handling if LSOA does not exist

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#107]
LSOA look up is performed using [postcodes.io](https://postcodes.io/). Any updates or edge cases should be handled here.
Any errors however due to postcode invalid or not existing currently not captured or handled.

**Comment by anchit-chandran** [comment]
I think you've done this @eatyourpeas ?

**Comment by anchit-chandran** [comment]
Keeping issue as closely related to replacing with new postcode API, which should solve this problem anyway

**Comment by anchit-chandran** [comment]
New postcode api implemented, closing
