### ISSUE TITLE
[Organisational Audit] - job plan questions

### ISSUE THREAD

**Issue by nikyraja** [rcpch/rcpch-audit-engine#1082]
Please could Q1.5 be re-worded to "What is the total number of hours per week for your Health Board/Trust (for example in nurse, doctor or allied professionals job plans) specified towards local epilepsy audit and quality improvement?"

Could an additional question then be added afterwards as Q1.6. "What is the total number of hours per week for your Health Board/Trust (for example in nurse, doctor or allied professionals job plans) specified towards local epilepsy service leadership?"

@SAbdin93 can you confirm that all the other questions are okay and match what was on NetSolving please?

**Comment by mbarton** [comment]
I've also loaded the answers from the previous submission. You can see an example here: https://e12.rcpch.ac.uk/trust/3/audit/

**Comment by mbarton** [comment]
@nikyraja what do you think about splitting the bracketed wording in 1.5 out to the right hand side panel (https://github.com/rcpch/rcpch-audit-engine/pull/1084)?

![Capture](https://github.com/user-attachments/assets/8dc5d8cd-c940-444f-9087-c413ad57ecb6)

**Comment by nikyraja** [comment]
That looks good, thank you Michael!
