### ISSUE TITLE
Adding organisation - The Robert Jones & Agnes Hunt Orthopaedic Hospital 

### ISSUE THREAD

**Issue by SAbdin93** [rcpch/rcpch-audit-engine#1088]
Hi, 

Please can the following organisation be added to the platform:

Name: The Robert Jones & Agnes Hunt Orthopaedic Hospital 
ODS Code: RL1

Address:
GOBOWEN
OSWESTRY
SY10 7AG
ENGLAND

Region: Y60 MIDLANDS COMMISSIONING REGION

ICB: QOC NHS SHROPSHIRE, TELFORD AND WREKIN INTEGRATED CARE BOARD

OPENUK: BRPNF - Birmingham Regional Paediatric Neurology Form

Organisations within the Trust: 
- Robert Jones and Agnes Hunt Orthopaedic Hospital  - Gobowen, Oswestry, SY10 7AG (RL1)
- Princess Royal Hospital - Apley Castle, Telford TF1 6TF (RL114)
- Royal Shrewsbury Hospital - Mytton Oak Rd, Shrewsbury SY3 8XQ (RL108)

If there's anything else you need give me a shout!

Thanks!
Saleema

**Comment by eatyourpeas** [comment]
Sorry, @SAbdin93 I always seem to have questions...
We currently have Royal Shrewsbury Hospital (RXWAS) as a child of THE SHREWSBURY AND TELFORD HOSPITAL NHS TRUST (RXW).
We also have THE PRINCESS ROYAL HOSPITAL (RXWAT), also a child of THE SHREWSBURY AND TELFORD HOSPITAL NHS TRUST (RXW).
We do not have ROBERT JONES & AGNES HUNT ORTHOPAEDIC HOSPITAL (RL131) or its parent THE ROBERT JONES AND AGNES HUNT ORTHOPAEDIC HOSPITAL NHS FOUNDATION TRUST (RL1)

Strangely though on the [ods](https://odsportal.digital.nhs.uk/Organisation/OrganisationDetails?organisationId=92007&showOpenChildredOnly=True) THE ROBERT JONES AND AGNES HUNT ORTHOPAEDIC HOSPITAL NHS FOUNDATION TRUST cites THE PRINCESS ROYAL HOSPITAL (RL114) and ROYAL SHREWSBURY HOSPITAL NORTH (RL108) as its child organisations - note the different ods codes.

Meanwhile [THE SHREWSBURY AND TELFORD HOSPITAL NHS TRUST (RXW)](https://www.sath.nhs.uk/) website states clearly that the two hospitals are theirs.

So I am a little confused as to what is the correct ods code for the Princess Royal Hospital and Shrewsbury Hospital and who their real parent is? Are we in the middle of a custody battle?

**Comment by eatyourpeas** [comment]
<img width="854" alt="image" src="https://github.com/user-attachments/assets/61c3d26a-fb3f-485b-b716-e3bc47c6461a">
chat GPT thinks this is more of a blended family, where the kids live between two amicably separated parents.

If this is correct, where is the epilepsy and paediatrics managed?

**Comment by SAbdin93** [comment]
Hi @eatyourpeas ,

Let me email them and find out. Will keep you updated

**Comment by eatyourpeas** [comment]
Reply from *Robert Jones and Agnes Hunt Orthopaedic Hospital NHS Foundation Trust*

> I spoke with the Assistant Chief Nurse, and there appears to have been some confusion. So while The Robert Jones and Agnes Hunt Orthopaedic NHS Foundation Trust and The Shrewsbury and Telford Hospital NHS Trust are both under the same ICS, we are two separate Trusts. We do work with both The Royal Shrewsbury Hospital (RSH) and the Princess Royal Hospital in Telford (PRH), but we are a stand alone Trust. We have a very small epilepsy service, confirmed by our Clinical Lead, but she also sees patients with epilepsy at both RSH and PRH. Will this be an issue? If we can have the log in details provided, we can try and get the data provided, but I’m also conscious that the window is getting smaller to be able to provide any data.

**Comment by eatyourpeas** [comment]
I have created ROBERT JONES & AGNES HUNT ORTHOPAEDIC HOSPITAL (RL131)  as an organisation, with its parent THE ROBERT JONES AND AGNES HUNT ORTHOPAEDIC HOSPITAL NHS FOUNDATION TRUST (RL1). It is all ready to use.
