### ISSUE TITLE
Make 'date seen' field non-mandatory for paediatrician with expertise, neurologist & ESN

### ISSUE THREAD

**Issue by nikyraja** [rcpch/rcpch-audit-engine#1095]
Please can the 'date seen' field for 1) paediatrician with expertise, 2) paediatric neurologist and 3) ESN (under Milestones section) be made non-mandatory? Example screenshot below:
![Neurologist Q screenshot](https://github.com/user-attachments/assets/1c996e50-91de-4e7c-99a1-a7c9aa80214e)

There will be instances where CYP are referred to a paediatrician/neurologist/ESN but are not seen within the first year (or before the data submission deadline). Currently, we mandate a 'date seen' for each professional and the record cannot be completed unless a date is entered. 

This has somehow slipped through out testing and has strangely only just been raised by a user. We feel that this is very common in practice though, and it may be because the majority of data entry is occurring now before the deadline and the cohort are completing their year of care now that this problem is arising. 

I would be open to having a button that says 'not achieved yet' that overrides the 'date seen' field. However, we need this actioning asap so that users can complete records before the January 2025 deadline, so I feel making the field non-mandatory may be the quicker and best option for now?

**Comment by eatyourpeas** [comment]
No problem @nikyraja 
This will have implications for KPI 1, KPI_2 and KPI 3 though

## KPI 1

```
"""
    1. `paediatrician_with_expertise_in_epilepsies`

    % of children and young people with epilepsy, with input by a ‘consultant paediatrician with expertise in epilepsies’ within 2 weeks of initial referral

    Calculation Method

    Numerator = Number of children and young people  [diagnosed with epilepsy] at first year AND (who had [input from a paediatrician with expertise in epilepsy] OR a [input from a paediatric neurologist] within 2 weeks of initial referral. (initial referral to mean first paediatric assessment)

    Denominator = Number of and young people [diagnosed with epilepsy] at first year
    """
```

## KPI 2

```
"""2. epilepsy_specialist_nurse

    % of children and young people with epilepsy, with input by epilepsy specialist nurse within the first year of care

    Calculation Method

    Numerator= Number of children and young people [diagnosed with epilepsy] AND who had input from an Epilepsy Specialist Nurse by first year

    Denominator = Number of children and young people [diagnosed with epilepsy] at first year
"""
```

## KPI 3

```
"""3. tertiary_input
    % of children and young people meeting defined criteria for paediatric neurology referral, with input of tertiary care and/or CESS referral within the first year of care

    Calculation Method

    Numerator = Number of children (
                    [less than 3 years old at first assessment] AND [diagnosed with epilepsy]
                     OR (number of children and young people diagnosed with epilepsy who had [3 or more maintenance AEDS] at first year) OR
                     (Number of children less than 4 years old at first assessment with epilepsy AND (has generalised myoclonic seizures OR has focal myoclonic seizures))  OR
                     (number of children and young people diagnosed with epilepsy  who met [CESS criteria] ) AND had
                     [evidence of involvement of a paediatric neurologist] OR [evidence of referral or involvement of CESS]

    Denominator = Number of children [less than 3 years old at first assessment] AND [diagnosed with epilepsy] OR (number of children and young people diagnosed with epilepsy who had [3 or more maintenance AEDS] at first year )OR (number of children and young people diagnosed with epilepsy  who met [CESS criteria] OR (Number of children less than 4 years old at first assessment with epilepsy AND  (has generalised myoclonic seizures OR has focal myoclonic seizures))
    """
```

How do you want the queries restructured?
I guess if we do this we have to recalculate everyone in the database?

**Comment by eatyourpeas** [comment]
Apart from this how about this?
<img width="672" alt="image" src="https://github.com/user-attachments/assets/910340d5-c8f7-4e2a-a498-2ceba17a94a4">

<img width="586" alt="image" src="https://github.com/user-attachments/assets/3df3e6e9-f088-4a27-b64c-64307139aacb">

<img width="586" alt="image" src="https://github.com/user-attachments/assets/25b0bf4a-66e7-472a-84f2-c8a34fa3c2ec">

**Comment by nikyraja** [comment]
Thanks Simon, those screenshots look great!

The KPIs shouldn't be affected as the criteria hasn't changed. The numerators would still only include those with input within the 2weeks/1 year, and the denominators would also remain the same. We'll just now start seeing some CYP with no input, making them the KPI. So I wouldn't expect the results to change or how we calculate them?

Would this affect the completeness of other records, or could we default 'yes' to "Has the child been seen by X" if a date has already been entered? I wouldn't want to change the status of completed records so close to the January deadline.

Happy to discuss over a call if we need?

**Comment by nikyraja** [comment]
Thanks so much Simon! this looks great on the platform.
