### ISSUE TITLE
Contact RCPCH

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#110]
The project board would like users to have a visible and easy way to contact RCPCH in situations where online documentation is inadequate and the local E12 admin does not have sufficient permissions to fix local issues.

- [x] email contact in footer or tooltip or individual audit form

**Comment by anchit-chandran** [comment]
Is the homepage contact sufficient @AmaniKrayemRCPCH  ?



![Image](https://user-images.githubusercontent.com/68898006/235700312-594b891a-d420-4238-bf9a-666e9896d4c4.png)

**Comment by AmaniKrayemRCPCH** [comment]
Yup! Looks good

**Comment by pacharanero** [comment]
Closing as it seems we are happy with the contact details for the team to be

`<a href="mailto:epilepsy12@rcpch.ac.uk" target="_blank">epilepsy12@rcpch.ac.uk</a>`

We will create a partial for this
