### ISSUE TITLE
Updating the Organisational Audit page on the Guidance tab

### ISSUE THREAD

**Issue by SAbdin93** [rcpch/rcpch-audit-engine#1102]
Hi Simon & Michael, 

I was wondering if we could update the wording on the guidance tab for the Organisational Audit: https://e12.rcpch.ac.uk/docs/clinician-users/organisational-audit/

Currently it reads: The Organisational Audit collects data on the paediatric epilepsy services within each Trust/Health Board. For the 2023 Organisational Audit, please complete this on the old Epilepsy12 platform.

I have had a few emails come in with trusts being confused as they are going onto the guidance tab and using the old link to the old platform which we no longer have access to. 

Can we update the text to read the following: 
The Organisational Audit collects data on the paediatric epilepsy services within each Trust/Health Board. For the 2024 Organisational Audit, please complete this on the new Epilepsy12 platform. 

and then include the link to sign in to the new platform in "new Epilepsy12 platform" maybe. 

Niky is away so happy for other suggestions btw if you have any! 

Thank you! 

Saleema

**Comment by mbarton** [comment]
Sure @SAbdin93, I will look at this today

**Comment by SAbdin93** [comment]
Thank you! :)

**Comment by mbarton** [comment]
Fixed and live @SAbdin93 :)

**Comment by SAbdin93** [comment]
Thanks @mbarton !
