### ISSUE TITLE
Jersey Unique Reference Numbers (URN)

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#1109]
Since Jersey is not part of the NHS, users do not have NHS numbers, instead they have URNs. There is no published methodology on the creation of these numbers, how uniqueness is ensured, whether there is any checksum/validation method as is the case for NHS numbers. To accommodate this this PR includes a new field in the Case model unique_reference_number which is (unique, obviously) but conditionally used in the forms, list views and so on if Jersey General Hospital and its patients are involved. The CaseForm now accepts an organisation_id parameter to check for this and has a is_jersey flag to decide whether to allow users to store URNs or NHS Numbers for a given patient. Cleaning methods have been updated for this. I have not yet added any tests for this but it appears to work in the UI at least. The templates have been updated conditionally to reference URN vs NHS Numbers, as well as the filters.

To address this issue more information is needed on how the URN is generated and validated.

@nikyraja - might you and the remarkable RCPCH Audit team be able to help here?

**Comment by nikyraja** [comment]
Thanks Simon. 

Currently the only validation we can think of is ensuring that there are only 6 numbers entered. Additionally, Excel & STATA tend to eliminate leading 0s when they recognize it as a number (and not a string). Many URN numbers start with a 0, so we may need to bear this in mind/find a work around. Amani suggested adding a letter at the front to retain the first 0?

I have asked our contact in Jersey if they have any further information, so will get back on this.

**Comment by nikyraja** [comment]
I have just spoken to our Jersey contact and as far as she is aware, there are no validation tools/methodology for the URNs like NHSE numbers have. 

She advised that Jersey have two identifiers: MRN - 6 digits and URN - 6 digits plus letter. 

Are we using URN? is NPDA? Happy to go with whatever NPDA has.

**Comment by mbarton** [comment]
We've decided not to do any validation for now as the small number of patients in Jersey means we can edit mistakes manually. We can also add validation rules later if required.
