### ISSUE TITLE
Remove Submitting Cohort & Active Cohort Information from Dashboard

### ISSUE THREAD

**Issue by SAbdin93** [rcpch/rcpch-audit-engine#1120]
Hi Michael & Simon,

I've spoken to Niky and after Issue #1116 & #1117 

We were wondering if we could remove the following box (Submitting Cohort & Active Cohort Information) from the dashboard? Just until we can come up with different wording. I know Michael has put up a banner saying that Cohort 6 is still open for submission, however we think removing this information temporarily will prevent any confusion.

![image](https://github.com/user-attachments/assets/49ecdc99-facf-4b3b-b36c-fa8bc1a1a9f8)

Let me know if there is anything you need from us!

**Comment by eatyourpeas** [comment]
how about this as a workaround?
<img width="1084" alt="image" src="https://github.com/user-attachments/assets/b1c42005-f5f0-4a3e-97dd-291432dbe4e6">

**Comment by SAbdin93** [comment]
@nikyraja

**Comment by nikyraja** [comment]
Thanks Simon.  

Could we highlight cohort 6 is someway, for example have a different colour background such as light blue to have a border around it? This will help make it super clear for users that they need to prioritise data entry for cohort 6.  We have been getting a lot of emails/calls with confused users, so if this isn't possible it may still be best to remove the tiles completely.

**Comment by mbarton** [comment]
I think hiding the tiles will still confuse people as it looks at a glance like their cohort 6 data has disappeared. Perhaps it's best to keep the dashboard showing the previous cohort during the grace period, as if the new one hadn't started yet?

**Comment by eatyourpeas** [comment]
As discussed - implementation to include all 3 cohorts but highlight the cohort that is soonest to close submission
<img width="1068" alt="image" src="https://github.com/user-attachments/assets/fab5c6b6-9c33-40ca-8c36-56a149373f1a">

**Comment by nikyraja** [comment]
Thanks Simon, that looks great!
