### ISSUE TITLE
Allowing decimals on Q1.5 & Q1.6 on the organisational audit

### ISSUE THREAD

**Issue by nikyraja** [rcpch/rcpch-audit-engine#1128]
Please can Q1.5 and Q1.6 of the organisational audit allow decimal entries like the Whole time equivalent questions? Currently you can only put in whole numbers
![image](https://github.com/user-attachments/assets/86649027-0d12-41f9-871b-00c910fefe66)

**Comment by mbarton** [comment]
No problem. Is this wording ok?
![Screenshot 2024-12-11 15 42 20](https://github.com/user-attachments/assets/a6a77caf-1b5b-4f34-a418-57762ef21345)

**Comment by nikyraja** [comment]
yes that's perfect thank you!

**Comment by mbarton** [comment]
This is live now @nikyraja
