### ISSUE TITLE
DESSCRIBE description Keyword list

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#113]
The DESSCRIBE tool includes a description tool which identifies key words in the free text which could potentially be used in future for analysis. The tool currently searches free text (using fuzzy matching) for epilepsy semiology keywords. The [ILAE](https://www.epilepsy.com/stories/2017-revised-classification-seizures) have published a [list](https://onlinelibrary.wiley.com/doi/full/10.1684/epd.2022.1430) which is incomplete for this app.

Currently the E12 platform stores keywords which are categorised as ILAE or custom.
New words can be added individually currently through the Django admin interface.

- [x] @coldunk to review keyword list with the project board and provide more/new custom keywords
- [x] @eatyourpeas to update constants list with these when database seeded

**Comment by pacharanero** [comment]
The keywords are managed at https://epilepsy12.rcpch.tech/admin/epilepsy12/keyword/

**Comment by pacharanero** [comment]
To some extent any improvement to this list needs to come from upstream, ie the ILAE list of agreed words may need to be updated, but we can't necessarily drive this process from E12.

Possible ways forward:
* Propose an RCPCH Epilepsy Glossary based on ILAE but adding more words
* Add new words in a 'proposed' class so that it's clear there are words we would like to add to ILAE

**Comment by pacharanero** [comment]
Discussed in E12 planning meeting 10.03.2023

**Comment by pacharanero** [comment]
@coldunk bumping following today's meeting.
@eatyourpeas could you put a link to where the code is that needs to be reviewed?
@coldunk If you have any difficulty in reviewing the list let us know. We could always do this on a call if it helps.

**Comment by eatyourpeas** [comment]
I think this issue is very difficult to close. The list is now in active service and will be validated once cohort 6 data is in and analysed. I will close this for now, but can reopen or post as a new issue at that point.
