### ISSUE TITLE
Add new sites to Sussex Community NHS Foundation Trust (RDR)

### ISSUE THREAD

**Issue by SAbdin93** [rcpch/rcpch-audit-engine#1135]
Hi,

Could we please add the following two sites to Sussex Community NHS Foundation Trust (RDR):

1. RDR08 - Chailey Heritage Clinical Services
Lead clinician: Dr Paul Wright (#########)
Address: Beggars Wood Road, North Chailey, Lewes, East Sussex, BN8 4JN

2. RDRC7 - Crawley and Horsham Child Development Centre
Address: Crawley Hospital, West Green Drive, Crawley, West Sussex, RH11 7DH

Let me know if you need any additional information.

Thanks

Saleema

**Comment by eatyourpeas** [comment]
These are now live
I have not registered any users.

<img width="1205" alt="image" src="https://github.com/user-attachments/assets/d8ef090e-e0e2-4d90-af8a-bcc0d5d131ad" />

<img width="1200" alt="image" src="https://github.com/user-attachments/assets/2f4b52dc-fbfc-4db6-8fdc-d015b43d08b6" />
