### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#129]
Lots of elements to this:

*General docs*
- [x] List audit team - @coldunk  Fridah Calvin-Mwingirwa, @hstac 
- [x] List technical team

*Developer docs*

- [x] HOWTO: Creating a custom audit for the home page
- [x] Deprivare server
- [x] SNOMED server
- [x] Style guide - "Child and Young Person"
- [ ] 

*User documentation*

- [ ] Explanation of Cohorts concept and data entry validation limits

*Privacy/Legal documentation*

- [ ] @hstac to provide CAG documentation
- [x] @pacharanero to add to documentation site

*Non-E12 (Audit Tools) documentation*

- [x] Deprivare needs documentation
- [ ] Hermes needs documentation

**Comment by pacharanero** [comment]
@nikyraja do you have access to any information on the CAG application for E12? It would be a nice additional to be able to add this to the documentation to explain that we have gone through all the proper procedure for data access.

**Comment by pacharanero** [comment]
This issue is out of date so closing - will continue to manage documentation issues on a more granular scale.
