### ISSUE TITLE
Additional Ethnicity Question 

### ISSUE THREAD

**Issue by nikyraja** [rcpch/rcpch-audit-engine#132]
Add 'Ethnicity of patient' in 'Add new Child/new Person' form, using the following categories: 

![ethnicity](https://user-images.githubusercontent.com/115647429/195384906-82e5e7de-9064-4025-a8ce-b16d9052be20.png)

**Comment by nikyraja** [comment]
@eatyourpeas @pacharanero

**Comment by eatyourpeas** [comment]
This is already implemented? Or is it the choices that are wrong?
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/1058647/195432114-0e58c4ae-d10b-452e-b98d-70cc7a99c2b4.png">

**Comment by nikyraja** [comment]
Great thanks! I couldn't get onto the form to check, but that looks good
