### ISSUE TITLE
Add in Mental Health questions

### ISSUE THREAD

**Issue by nikyraja** [rcpch/rcpch-audit-engine#133]
We want to add in the following questions to the DESC**RIBE** tab:

-  Add ‘Is there evidence of the child being assessed for mental health problems via clinical enquiry or the use of a screening questionnaire?’ with Yes/No options
(Mandatory) 

- Add ‘Does the child have any mental health issue identified?’ With Yes/No options 
(Mandatory) 

If ‘Yes’ is selected, have the following questions appear:
‘Add details of any known mental health problem(s)’, with the following options: ‘Mood Disorder, Anxiety, Emotional/behavioural, Self-harm, or Other’ (
‘Is there evidence of the child receiving support for their mental health?’ with the following options: 'Yes', 'No - referred but not received', or 'No - not referred and not received'

**Comment by eatyourpeas** [comment]
This question is asked at the initial paedatric assessment so would in effect be a duplicate. Are we sure we want this is 2 places? is this drop down list then to replace SNOMED which is what we had planned to implement?

**Comment by FridahC** [comment]
Priority task
