### ISSUE TITLE
Edit MRI question on Tab 6.Tests

### ISSUE THREAD

**Issue by nikyraja** [rcpch/rcpch-audit-engine#134]
Have the following questions appear:

Was an MRI brain scan requested? with Yes/No options
If ‘Yes ‘is selected, ask for: 

- Date of request
- Date of report

**Comment by eatyourpeas** [comment]
This is already implemented though the wording is slightly different: Is an MRI brain indicated? and MRI request date, MRI performed date.

Does the current wording need to change?

**Comment by eatyourpeas** [comment]
this is duplicate of #142 ongoing
