### ISSUE TITLE
Tab 6 Tests

### ISSUE THREAD

**Issue by coldunk** [rcpch/rcpch-audit-engine#142]
Indications for EEG:
The recommendation is that all children with Epilepsy should have an EEG

the 'Is an EEG indicated'  is therefore better phrased as 
Has a first EEG been requested? 
can the fields then be 'Date first EEG requested?'  Date first EEG performed? Date first EEG reported?

Indications for ECG:
The Epilepsy12 standard is that all children with an convulsive episode should have a 12 lead ECG

Indications for CT:
NICE recommends "If MRI is contraindicated, consider a CT scan for children, young people and adults with epilepsy."

Indications for MRI:
NICE recommends "Offer an MRI scan to children, young people and adults diagnosed with epilepsy, unless they have idiopathic generalised epilepsy or self-limited epilepsy with centrotemporal spikes. The MRI should be carried out within 6 weeks of the MRI referral

Can it be reworded to be 'Has a brain MRI been requested?' rather than 'Is an MRI brain indicated?'
can it again include the MRI brain reported date as an additional field.

**Comment by eatyourpeas** [comment]
Thanks @coldunk 
These are the fields we capture at the moment:
```mri_indicated```
```mri_brain_requested_date```
```mri_brain_performed_date```
Do you want to add a fourth date: ```mri_reported_date``` or just to replace ```mri_performed_date``` and keep the 3 dates?

This way we could report time to MRI from request and time to reporting from scanning, as well as time from request to report. Would involve asking clinicians to know those 4 dates, though we could later on make that an API hook potentially if trusts were happy to send the dates automatically.

**Comment by eatyourpeas** [comment]
As discussed with @coldunk : deprecate the performed_date and use reported_date
