### ISSUE TITLE
Tab 7 Treatment and care planning

### ISSUE THREAD

**Issue by coldunk** [rcpch/rcpch-audit-engine#143]
* [x] Has an Antiepilepsy Drug been given? Can this be reworded to 'Has an Antiseizure medication been given?'

* [x] Rather than 'Has an individualised care plan been put in place?'  can it say Has care planning (either an individualised epilepsy document or copy clinic letter including care planning information) commenced?

* [ ] we don't need a date for this as i am trying to articulate this as an ongoing process rather than simply a form!  

* [x] 'updated in last year' can this be rephrased as ' being updated as necessary'

* [x] can the question 'Does the individualised care plan have documentation of the following:' be rephrased as 'Does ongoing individualised care planning include:' 

* [ ] Can there be an additional question (in addition to the EHCP question) A school individual healthcare plan (IHP)  Yes no

**Comment by pacharanero** [comment]
> we don't need a date for this as i am trying to articulate this as an ongoing process rather than simply a form!
@eatyourpeas we can remove this from the model as well as the form

> Can there be an additional question (in addition to the EHCP question) A school individual healthcare plan (IHP) Yes no
@eatyourpeas I'd like to implement this together
