### ISSUE TITLE
toggle_button disabled functionality needs refactoring to remove duplication

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#148]
Currently a lot of code in the templates is duplicated, for example

```python
            {% if perms.epilepsy12.change_initial_assessment %}
                {% include 'epilepsy12/partials/page_elements/toggle_button.html' with hx_post=hx_post hx_target='#when_the_first_epileptic_episode_occurred' hx_trigger='click' hx_swap='innerHTML' test_positive=initial_assessment.general_examination_performed label='Full paediatric clinical examination' data_position='top left' disabled=False %}
            {% else %}
                {% include 'epilepsy12/partials/page_elements/toggle_button.html' with hx_post=hx_post hx_target='#when_the_first_epileptic_episode_occurred' hx_trigger='click' hx_swap='innerHTML' test_positive=initial_assessment.general_examination_performed label='Full paediatric clinical examination' data_position='top left' disabled=True  %}
            {% endif %}
```

Here there is identical content, written out twice, in order to have conditional logic to determine if the toggle button should appear 'disabled' or not.

It is possible to pass the permission boolean - in this case `perms.epilepsy12.change_initial_assessment - directly in as the value of `disabled` - however this would result in the **inverse** operation to what we want - the toggle would be disabled for those users who   DO have permissions.

So I propose changing the `disabled` flag to an `permission` flag, which will then result in a much simpler implementation. In the `include` invocation we would pass the flag `permissions=perms.epilepsy12.change_initial_assessment`.

We should also take the opportunity to put in some testing around the different user permissions and the behaviour of the UI.

**Comment by eatyourpeas** [comment]
fixed with https://github.com/rcpch/rcpch-audit-engine/commit/5dce425a069dafa4b71259325c25a00497ed573c
