### ISSUE TITLE
Reference and label text

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#153]
The label text and popup text have now moved out of the templates and into the models.
This makes them easier to refactor if wording and so on changes.
We now need accurate label text and in particular references from NICE / E12 documentation for users to know why a particular measure is being gathered.
To sign this off:
- [x] label text for every question
- [x] reference text for every question

**Comment by pacharanero** [comment]
https://github.com/rcpch/rcpch-audit-engine/blob/dd121d595b6869923810594ae12ec3fbc9576a63/epilepsy12/models_folder/assessment.py#L25

@nikyraja @coldunk @FridahC do the the reference texts make sense to you? If you have any changes you can just put them here and we will update in the code.

**Comment by AmaniKrayemRCPCH** [comment]
I've attached the latest version of our data dictionary. The last two columns could be used to update references/tool tips. Let me know if you'd like anything further from me or want to clarify anything. 

[Data Dictionary_280323.docx](https://github.com/rcpch/rcpch-audit-engine/files/11089605/Data.Dictionary_280323.docx)

**Comment by pacharanero** [comment]
This has been completed as part of #375
