### ISSUE TITLE
Design feedback on E12 platform from RCPCH design team

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#159]
|Recommended change|Type|Comments|
|---|---|---|
| Change all font to Montserrat, including for copy text, menu items|Design|Some has changed; could also change buttons like 'View all XYZ children' on clinian dashboard, which is now Helvetical. Presume want to use Arial for data, which is fine|
|Mobile display - Menu does display, but optionally use a burger menu to hide it|Design|Simon confirmed unlikely to be heavily used on mobile, but can work to improve mobile display esp on front page, other content pages|
|Colours - White text on our bright blue (#11a7f2) does not pass accessibility colour contrast – needs to be black text. Or use white background with Dark blue text for large blocks of copy|Design|Complete|
|Use sentence case for menu items, so ‘Patient access’ not 'Patient Access', etc.|Editorial|Complete|
|Don't use full stop after headings, eg 'The UK National Audit for Childhood Epilepsies'|Editorial|Complete|
|Home page content - To write new, welcoming content about who and what the site is for, and what you can do here? Can add a link to other pages for more detail as needed|Editorial|C&B/Ep12 team to provide mockup with copy / C&B team happy to review|
|Branding - There are two Epilepsy12 logos - new one at top banner, and old one in content window. Full RCPCH logo should be used. Recommend removing Epilepsy12 and RCPCH acronmyn logos from top of content window, even removing that top content box. And add logos - including full version to a footer, if available, and with RCPCH logo linking to main website|Layout/navigation|C&B team and Epilepsy12 team discussing options for revised Epilepsy12 branding, with one logo version possibly having strapline - will provide and can test that displays well alongside RCPCH logo|
|Links for clinician access and patient access - move higher up home page|Layout/navigation|Complete|
|Community & hospital' - Use 'and' instead of ampersand, and to match 'Children and families' - Generally we recommend using 'and' but not a major thing!|Editorial||
|Menu - Add Home link in addition to RCPCH/E12 logo/text?|Layout/navigation|A convention we use on our other sites, but not essential|
|Menu / layout - This cuts off for Kirsten's view, but possibly only as I see 'Database management' which I assume most users won't see. See screenshot Check to see if issue for others; if so, reduce font size?|Design||
|Favicon - add dynamic child icon - can download from https://childprotection.rcpch.ac.uk/wp-content/uploads/sites/6/2020/05/RCPCH_MICROSITE-favicon-Square-270x270-1.png (unless quick brand/logo check suggests alternative)|Design||
|Branding - Content & Brand and Audits (Epilepsy12) teams discussing new logo, possibly with strapline; We'll provide and test this displays alongside RCPCPH logo in header and/or in home page banner.|Design (internal)||
|Clinician access dashboard - consider using more brand colours Add clear links to the data entry (call to action)|Design|This is in progress; Simon noted that we could have different chart types (eg not pie charts)  Note I couldn't easily find an org/Trust with any data, and so not sure if any examples|
|Clinician access dashboard / patients listing - show name of organisation or Trust|Design|[Already changed to show name of org/Trust, but...] Sometimes the Trust name does not match, eg selecting Airey Close Lowestoft shows the blue contact details box with Norfolk and Suffolk NHS Foundation Trust. The 'View all children' button also to Trust - but when clicking through appears to be for just Airey Close. I assume it's due to Airey Close being a part of the Trust, but wonder if a bit confusing?|
|Clinician access: patients listing - add link back to dashboard|Content||
|Clinical access: activity log - this displays number of likes, but I can't see option from here to like. Is it needed? |Content||
|Clinican access: contact details box - check wrapping of some URLs - see screenshot|Design||
|Form to add a new pattient - Agree colours for buttons and actions, as discussed in meeting. C&B team suggested using colour to indicate meaning, eg Green for a completed stage (rather than Pink), but it was noted this had caused confusion in past as clinicians think they've completed whole thing not just one section! So for consideration.  Information message are blue on blue, but Simon suggests could be only visible on user action Buttons are blue, but consider changing to pink to match that of other websites - not essential. Add animation to show open/collapse for each section, eg on Multiaxial diagnosis Auto saves|Design|As seen at meeting. Kirsten doesn't have permissions to add a new patient, and gets an Access denied message - this is waiting for some contact information.|
|Footer - on hover, link text goes dark so not visible on black background. Option to set different colour, or no colour change, on hover? (On our main site, the link text is underlined on hover; on the microsites such as https://childprotection.rcpch.ac.uk/, the link text is turned blue on hover.)|Design||
|Footer - change Epilepsy12 link to www.rcpch.ac.uk/epilepsy12? That's where the reports and information about audit are. Link back to Data portal home for other audits?|Content||
|Footer, sort of - There's a link to Follow us on GitHub, and copyright - can these be moved into black background footer?|Layout/navigation||
|Terms and conditions - This reads 'Terms of service', should it be renamed on menu? It suggests a user needs to accept before proceeding - will there be a process when a user first signs up for the platform to acknowledge?|Content||

**Comment by eatyourpeas** [comment]
@pacharanero: as I work through some of these I would like to be able to sign them off as I go - could you please add in some mark down checkboxes or similar also so Kirsten can see review progress?

**Comment by anchit-chandran** [comment]
This all seems done? @eatyourpeas @pacharanero

**Comment by pacharanero** [comment]
closed as completed - can be reviewed by design team periodically
