### ISSUE TITLE
2-Factor Authentication for superusers and other users with augmented powers

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#166]
This will be addressed as part of pentest and DPIA recommendations. (pentest report awaited)

**Comment by anchit-chandran** [comment]
- Check whether NHS Staff Services is currently fit for our purposes
- Django plugin: https://django-two-factor-auth.readthedocs.io/en/stable/

**Comment by anchit-chandran** [comment]
close as complete - will require @AmaniKrayemRCPCH users' eyes on workflow
