### ISSUE TITLE
Need a new Administration staff permission Role for solely adding new children's details, pre-Registration

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#168]

**Comment by pacharanero** [comment]
@eatyourpeas I think we have this in the user roles as per https://github.com/rcpch/rcpch-audit-engine/blob/live/epilepsy12/constants/user_types.py#L22:1

 (AUDIT_CENTRE_LEAD_CLINICIAN, 'Audit Centre Lead Clinician'),
 (AUDIT_CENTRE_CLINICIAN, 'Audit Centre Clinician'),
 (AUDIT_CENTRE_ADMINISTRATOR, '**Audit Centre Administrator**'),
 (RCPCH_AUDIT_LEAD, 'RCPCH Audit Lead'),
 (RCPCH_AUDIT_ANALYST, 'RCPCH Audit Analyst'),
 (RCPCH_AUDIT_ADMINISTRATOR, 'RCPCH Audit Administrator'),
 (RCPCH_AUDIT_PATIENT_FAMILY, 'RCPCH Audit Children and Family'),

Can I close this as complete?

**Comment by eatyourpeas** [comment]
Yes this is implemented and can be closed
