### ISSUE TITLE
PROJECT TEAM: To make a decision on Move Cohort number to appear after DOFPA, then deadline should be indicated below. vs Change the epilepsy submission deadline to 'Epilepsy 12 Cohort Submission Deadline' and indicate the Cohort Deadline

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#177]

**Comment by nikyraja** [comment]
![image](https://user-images.githubusercontent.com/115647429/206519803-f4dd4bf8-da7e-46c3-84f4-f03630a51b2c.png)

Attached image of the 4 boxes we would like.
- submission deadline needs to be the first Tuesday in January after the end of the cohort, at 23:59.

**Comment by eatyourpeas** [comment]
@nikyraja This issue is already implemented and live.
