### ISSUE TITLE
Fridah needs access to Azure DB backend to test SQL

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#179]

**Comment by pacharanero** [comment]
@rcpch/rcpch-digital-team would you be able to liaise with Fridah to ensure she has appropriate access to Azure

For security reasons it should be 2FA access ideally, since the database is going to contain patient identifiable information when live. For testing the 2FA requirement could be skipped but it would need to be added later.

**Comment by eatyourpeas** [comment]
I wonder if Ollie can help with this?
the Postgresql database involves the user as well as there domain being whitelisted and having their own username and password.

**Comment by FridahC** [comment]
I have access to the database. I'm wondering if you have any metadata/data dictionary at hand? Something that shows how different data items are coded. For instance in the screenshot below, a file that shows what 0/1 are i.e no/yes

![image](https://user-images.githubusercontent.com/115698255/203546138-2bbf3040-22fa-4b51-97c7-6356eb94fb86.png)

**Comment by eatyourpeas** [comment]
In the design we deliberately went for boolean values for most fields. This means 3 potential values: true (1), false(0) and none (null) or unscored
For the look up fields the key value is usually a number, sometimes a string. I can provide you with these or you will find them in the repository in the constants folder, within the [constants folder](https://github.com/rcpch/rcpch-audit-engine/tree/live/epilepsy12/constants)

**Comment by pacharanero** [comment]
I think we might need to find a way to make it a bit easier for Fridah and other analysts to get at this information.
I think it should go in the documentation at least, the only caveat being we don't want to have to write and rewrite documentation if the spec/constants change. I will have a look at what we can do to make this easier.

Once we have a better understanding of what queries are being done then perhaps we can arrange it so that the more common queries happen in our custom admin-side UI which we can make to look nice and the labels clear

We can discuss this all at the meeting next week in London
