### ISSUE TITLE
LSOA postcode error

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#185]
If the postcode is not valid there is currently no error message raised 
it does not break the object saving but the LSOA look up and IMD calculation then fails.
- [ ] Need to validate postcode using api.postcodes.io prior to save

**Comment by pacharanero** [comment]
Desired behaviour would be:

```
if postcode_invalid == True:
    raise PostcodeInvalidException
else:
    Postcode.save()
``` 

Question for next E12 meeting: What should happen if the data-entry member of staff doesn't have a valid postcode available to them? Should the system refuse to save the record entirely, or allow them to be saved but without postcode (meaning no LSOA or Deprivation data will be available)?

**Comment by pacharanero** [comment]
### Discussed in E12 team meeting 10.03.2023.

Currently in the E12 platform, there is a workaround. If the postcode is not known there is a dummy NHS England pseudo-postcode which is entered. This excludes them from deprivation score analysis.

However we are also aware that there is different practice occurring in Wales and England.

### Proposed plan
* have a button to allow the user to click to say the patient had either 'No Fixed Abode' or 'Postcode Not Known'. Postcode input field would then disappear. What would be persisted in the DB would be as below.
* @AmaniKrayemRCPCH: ‘No Fixed Abode’ postcode (ZZ99 3VZ) or ‘Address Not Known’ postcode (ZZ99 3WZ), or ‘England UK - not specified’ (Z99 3CZ)
* Deprivation score analysis would be skipped for those records.

**Comment by AmaniKrayemRCPCH** [comment]
To confirm, all unknown postcodes, including 'No Fixed Abode' are excluded from deprivation score analysis.
