### ISSUE TITLE
set locked to true if registered > 1 y

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#19]
```
        # this currently is unlikely to work TODO set locked to true if registered > 1 y
```

https://github.com/rcpch/rcpch-audit-engine/blob/bf8ffc2df81f77474cb0c99c79fb24a31c578fe4/rcpch-audit-engine/epilepsy12/models/registration.py#L74

**Comment by pacharanero** [comment]
closed as this is a duplicate
