### ISSUE TITLE
Tab 7: Has an antiseizure medicine been given?   

### ISSUE THREAD

**Issue by FridahC** [rcpch/rcpch-audit-engine#206]
The platform doesn't allow  entry of **Medicine discontinued date**

Priority task please

**Comment by eatyourpeas** [comment]
Thanks @FridahC 
I am not seeing this - could you provide a bit more context/information or an example?
<img width="780" alt="image" src="https://user-images.githubusercontent.com/1058647/200683772-d0965064-6b58-4807-a560-0c1926cdf1ce.png">
The only issue with this field is that there is no provision for medicines where this field is blank which is something that has bothered me. Presumably users need to be able to list drugs that have no end date?

**Comment by FridahC** [comment]
Thank @eatyourpeas 
I'm able to enter the dates now

**Comment by FridahC** [comment]
@eatyourpeas 

Do you mean if the end date is **not known** or the child is **still taking the medication**? if the later, maybe adding **ongoing** button?
