### ISSUE TITLE
Need to reorganise into DESSCRIBE categories - still persist the granular but also concatenate seizure type as useable string

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#21]
```
# TODO Need to reorganise into DESSCRIBE categories - still persist the granular but also concatenate seizure type as useable string
```

https://github.com/rcpch/rcpch-audit-engine/blob/bf8ffc2df81f77474cb0c99c79fb24a31c578fe4/rcpch-audit-engine/epilepsy12/models/seizure_type.py#L17

**Comment by pacharanero** [comment]
This is in progress, we have started to build the DESSCRIBE tool into the way the data is gathered. @eatyourpeas has been working on this.

**Comment by eatyourpeas** [comment]
This is now implemented awaiting review by @cdunkley
