### ISSUE TITLE
Duplicate MH Questions

### ISSUE THREAD

**Issue by nikyraja** [rcpch/rcpch-audit-engine#210]
Simon you had previously raised this - we are asking the question about 1) learning difficulties and 2) MH conditions twice: in tab 2 first paediatric assessment and in the describe tab. 

Do we need this @coldunk? or can we remove the questions from first paediatric assessment tab?

**Comment by eatyourpeas** [comment]
These are the 2 forms @coldunk:

<img width="860" alt="image" src="https://user-images.githubusercontent.com/1058647/204038171-dbb99ec5-0f43-4329-b2ca-9624db52af2d.png">
<img width="818" alt="image" src="https://user-images.githubusercontent.com/1058647/204038278-e6878d7a-e634-4b78-9efe-9f206b6050a5.png">

**Comment by coldunk** [comment]
Is fine. The first is asking about the presence of this specific during enquiry at first paed assessment.  The second at any time by the end of first year.
