### ISSUE TITLE
Epilepsy12 Data Submission Deadline rules and calculations

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#215]
The Epilepsy12 Data Submission Deadline is the **2nd Tuesday in the January following the end of the Cohort**
(Cohorts end on 30th November)

UI: consider adding the submission date to the patient list view so users can see when the submission is due. (IMPORTANT: that button should reference the Cohort number as well. @calvindowns)

**Comment by eatyourpeas** [comment]
- [x] add new field submission_date field to data model as calculated field, logic in the save() method as per 2nd Tuesday rule (dateutils package should be able to do this)
- [x] add submission_date to ui next to one year on date in registration form
- [x] add time_ to_submission counter in case_list (submission_date - date.now())
- [x] disable enter data button once submission date has passed
- [x] implement new data submit button in case_list - two way toggle to allow unsubmit right up to submission_date
- [x] colour change in case_last to ?orange in week before submission date, with further urgency on day of submission, referencing cohort e.g. 'Only 5 hours left til cohort 5 submission deadline...'

**Comment by eatyourpeas** [comment]
(@pacharanero  this would be a really nice one to pair on as it touches the templates, the view and the models)

**Comment by eatyourpeas** [comment]
Some questions about the logic here for the E12 time.
The audit submission deadline is always on the 2nd Tuesday in January.
Is that the January immediately following the first paediatric assessment date or the the January following the one year on from first paediatric assessment date?

**Comment by eatyourpeas** [comment]
So for example:
<img width="876" alt="image" src="https://user-images.githubusercontent.com/1058647/205467373-7b3b1407-80ee-4ae2-85a5-da095dc90520.png">

**Comment by eatyourpeas** [comment]
as discussed with @coldunk 
submission date is the second Tuesday in January following the first completed year of care from the first paediatric assessment. Even if the cohort ends in February, users still have a further 11 months before submission closes.

**Comment by coldunk** [comment]
Or longer. For example the Decembers in the cohort will need to wait for the 2nd January!! Eg 13/12
