### ISSUE TITLE
Cohort dates 

### ISSUE THREAD

**Issue by hstac** [rcpch/rcpch-audit-engine#22]
Patient first paediatric assessment date was/will be between
Cohort 4:	1 December 2020 – 30 November 2021
Cohort 5:	1 December 2021 – 30 November 2022
Cohort 6:	1 December 2022 – 30 November 2023
Cohort 7:	1 December 2023 – 30 November 2024

**Comment by pacharanero** [comment]
Cohort-calculating code has been implemented in a previous version, but is missing in the current codebase, which I think is an omission on our part. It's tracked in issue #14 so I will close this one.
