### ISSUE TITLE
Groups and User Permissions review & sense-check

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#221]
@nikyraja as discussed today here's the code for the user permission and groups that we have roughed out, need to make sure they align with all likely situations you encounter in operational reality.

https://github.com/rcpch/rcpch-audit-engine/blob/live/epilepsy12/constants/user_types.py#L22:1

If you have changes that need making, GitHub allows you to comment on individual lines of code, this makes it easier for us to make the edits. See below of how to do it - click on line number then the three . . . dots, then Create Issue

![image](https://user-images.githubusercontent.com/2348385/204820799-3b5bf6f9-02eb-4644-8de2-ca320ea89f6a.png)

**Comment by pacharanero** [comment]
@nikyraja are these User ROles consistent with your requirements?

    (AUDIT_CENTRE_LEAD_CLINICIAN, 'Audit Centre Lead Clinician'),
    (AUDIT_CENTRE_CLINICIAN, 'Audit Centre Clinician'),
    (AUDIT_CENTRE_ADMINISTRATOR, 'Audit Centre Administrator'),
    (RCPCH_AUDIT_LEAD, 'RCPCH Audit Lead'),
    (RCPCH_AUDIT_ANALYST, 'RCPCH Audit Analyst'),
    (RCPCH_AUDIT_ADMINISTRATOR, 'RCPCH Audit Administrator'),
    (RCPCH_AUDIT_PATIENT_FAMILY, 'RCPCH Audit Children and Family'),

**Comment by eatyourpeas** [comment]
answered by email. Thanks @nikyraja
