### ISSUE TITLE
Drug names, and the NHS Dictionary of Medicines and Devices (via API)

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#24]
Quick note that as of this week there has been an announcement that the NHS "Dictionary of Medicines and Devices" aka. "dm+d" (not to be confused with the DM&D "Data Model and Dictionary" (you couldn't make it up, they are unrestrained in their idiocy) now has a REST API via the NHS Terminology Server and so we can potentially use this to look up drug names, classes, etc for the Audit Engine.

https://discourse.digitalhealth.net/t/nhs-dictionary-of-medicines-and-devices-dm-d-data-now-available-through-a-web-api/23990

**Comment by eatyourpeas** [comment]
Currently medicines now loaded in from SNOMED
