### ISSUE TITLE
Landing Page Text edit 

### ISSUE THREAD

**Issue by nikyraja** [rcpch/rcpch-audit-engine#245]
Please could the following changes be applied to the landing page? (mainly to the opt out text)

**Welcome to the Epilepsy12 data platform**
Epilepsy12 is delivered by the Royal College of Paediatrics and Child Health (RCPCH). The RCPCH mission is to transform child health through knowledge, innovation and expertise.

_National Data Opt Out Implementation (England only)_

The Epilepsy12 audit is now exempt from the NHS National Data Opt-Out. Healthcare providers in England no longer need to screen patients against the opt-out list prior to entering their data. Patients can still opt out of Epilepsy12 specifically by contacting their clinical team. You can indicate this in the first year of care form and the record will be deleted. 
Please take a look at our [methodology and data submission page](https://www.rcpch.ac.uk/work-we-do/quality-improvement-patient-safety/epilepsy12-audit/methodology-data-submission) for more information.

Childhood epilepsy
Epilepsy affects around one in every 200 children and young people in the UK (aged 18 and under). The condition is one of the most common significant long-term health conditions of childhood. Epilepsy can have a huge impact on children and families. Epileptic seizures can happen in any part of the brain cortex and what happens depends on where in the brain the seizure is happening. Seizures can be distressing but it’s not just the seizures that are the problem. Children and young people may experience issues with learning, behaviour and emotions. That’s why children and parents need support and guidance from healthcare professionals throughout the stages of diagnosis and treatment.

About Epilepsy12
Epilepsy12 (The UK collaborative clinical audit of health care for children and young people with suspected epileptic seizures) is a national clinical audit established in 2009 and has the continued aim of helping epilepsy services, and those who commission health services, to measure and improve the quality of care for children and young people with seizures and epilepsies. The audit is overseen by a project board and a dedicated project team within the RCPCH. 
You can contact the team at: epilepsy12@rcpch.ac.uk or on 020 7092 6157/6056. Dr Colin Dunkley, Consultant Paediatrician, is the current clinical lead for Epilepsy12.

**Comment by pacharanero** [comment]
Can I just clarify which bits have changed here?

You only need to send us the stuff that is **changing**. Anything else just confuses and results in significant time spent manually determining whether there is a small change in the text or if it's the same.

As far as I can see it's the NDOO stuff which I'll add in now. If there are any other changes to the text please indicate which.

Ta

M
