### ISSUE TITLE
Documentation text edit

### ISSUE THREAD

**Issue by nikyraja** [rcpch/rcpch-audit-engine#246]
Please could the text on the documentation page be edited to reflect the new performance indicators:

**Introduction**
The RCPCH Audit Engine is a framework for national clinical audits. Its first deployment is as a new platform for the RCPCH's established Epilepsy12 audit, a national audit for childhood epilepsies which has been in place since 2009, but it is designed so as to be reusable for other audits in the future.

National clinical audits are there to collect diagnosis and care process data on patient cohorts with a diagnosis in common, nationally, to benchmark the standard of care and feed back to care-giving organisations about their performance. They are a way to make sure that clinics are meeting centrally-set standards, and give clinics feedback on how they are doing. Most national audits such as Epilepsy12 are commissioned by NHS England.

The RCPCH Audit Engine is a Django 4.0 project, using Semantic UI for the user interface framework. It aims to standardise those elements of a national audit that can be standardised, such as the concept of a Case (patient), Registration of cases to the audit, and management of researchers and administration users.

**Stated Aims of the Audit**
•	Continue to measure and improve care and outcomes for children and young people with epilepsies
•	Include all children and young people with a new onset of epilepsy,
•	Enable continuous patient ascertainment,
•	Use a pragmatic and concise dataset,
•	Incorporate NICE Quality Standards alongside metrics about mental health, education and transition to adult services,
•	Provide services with local real-time patient- and service-level reporting.

**Quality Improvement**
•	Supporting regional and national quality improvement activities
•	Epilepsy Quality Improvement Programme (EQIP)
•	Healthcare Improvement Plan
•	Involving children and young people

**There are 10 key performance indicators**
1.	Input into care from a paediatrician with expertise in epilepsies,
2.	Input into care from an epilepsy specialist nurse (ESNs),
3.	(a) Appropriate tertiary input into care, and (b) appropriate epilepsy surgery referral
4.	Access to electrocardiogram (ECG)
5.	Access to magnetic resonance imaging (MRI)
6.	Assessment of mental health issues
7.	Mental health support
8.	Girls and young women prescribed sodium valproate with an annual risk acknowledgement form completed
9.	(a) Comprehensive care plan that is updated and agreed with the patient, and (b) Documented evidence of all key elements of care planning content
10.	Record of a school individual health care plan

Feedback and feature requests

**Comment by pacharanero** [comment]
This has been done and is now live at https://epilepsy12docs.rcpch.tech/
