### ISSUE TITLE
Implementer documentation

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#25]
Implementers who are wanting to use the API will need detailed descriptions of the mapping or data fields that they will need to pull from their EPR and how to send them to the API in a suitable manner that it is accepted.

It will probably be possible to maintain the documentation withing the audit-engine main codebase, perhaps generating a static website from Markdown in a `docs/` folder.

MkDocs would do this, or there may be a way to do it with a plugin for Django itself. (Ideally this documentation should be pre-rendered into static HTML rather than server-side rendered by audit-engine for each request)

**Comment by pacharanero** [comment]
Documentation section should also include Roadmap section to describe future development of the E12 platform and timescales thereof

**Comment by pacharanero** [comment]
Branch `mkdocs` contains a first draft of a Material for MkDocs site which has stubbed out documentation.
It is mounted inside the Django app to the /docs/ route

**Comment by eatyourpeas** [comment]
This has now been done. Documentation has yet to be written but the site is functioning. Thanks to @pacharanero
