### ISSUE TITLE
Hospital list as a service

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#250]
Discussion today at E12 meeting for data visualisation.
There is an appetite for aggregating data by geographical and health region, as well as over time.
For this we need a detailed hospital trust model that stores not only information about the individual hospital, but also which region it sits in, as well as ICB etc. Since boundaries can change, each model instance needs to have a valid_at date field and an is_valid boolean to filter against to ensure the correct region for the correct date is chosen.

This potentially needs to be run as a separate service so that it can be kept up to date independently using the E12/RCPCH network.

**Comment by eatyourpeas** [comment]
Quite a lot of work has been done on this since posting this issue, which has thrown up some questions. There is now a separate repository [rcpch-nhs-organisations](https://github.com/rcpch/rcpch-nhs-organisations) seeking to offer this as a service, and there is also a much better and more comprehensive service provided by @wardle called [clods](https://github.com/wardle/clods)
As an original author of what is now the ODS API, @mattstibbs has provided some helpful insights into the quality of centrally-held data.
There are 2 APIs holding organisational data: [ODS](https://directory.spineservices.nhs.uk/apidocs/#/) and [api.nhs.uk](https://developer.api.nhs.uk/nhs-api/documentation/service-search-organisations-2). The latter requires an API key, the former does not. The former is versioned - containing dates of change to organisation, which is important for E12. Neither holds information on the new ICBs which are important for E12.
It had been envisaged that the rcpch-nhs-organisations maintain an up to date list of hospitals by polling ODS and NHS apis, but this feels like duplication when there are better solutions available.

Discussion today at length chewing this over with @pacharanero 
General feeling is that we should 
1. shelve the rcpch-nhs-organisations project for the time being. It may be in future it might be a way of publishing organisational data in a versioned way as a python package to make it more consumable than hooking up an API. Either way, no further activity will take place here for the time being
2. Update the HospitalTrust model with a last_updated date field to allow versioning, potentially using infrequent calls to the ODS /sync endpoint, persisting old versions.
3. Update the HospitalTrust model to include ODSCode, CCGCode and ICBCode. It is not clear how to map [ODSCodes to hospitals](https://digital.nhs.uk/services/organisation-data-service/upcoming-code-changes). I have posted a question on the [nhs developer forum](https://developer.community.nhs.uk/t/ods-and-integrated-care-boards/249) about this, unless anyone has any other insights.

**Comment by wardle** [comment]
Personally I'd create your own limited subset of organisations for your project but ensure that you include an ODS code so that you potentially can map to and from as required. I do this, eg I have a system to track orgs that I can lookup PAS data - and so use ODS to then say... oh can I use this to help process data for that.

**Comment by eatyourpeas** [comment]
Thanks @wardle I think we have decided to go this route. I have created a list of hospitals across England and Wales (which may need curating) that contains all the relevant ODS and ONS codes.
