### ISSUE TITLE
Alignment of Nav items changes on hover

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#261]
![Image](https://user-images.githubusercontent.com/2348385/223720758-b68af9a6-cd91-456c-ad04-5b1f7e0130c5.png)

On hover the vertical alignment of the nav items moves slightly, which needs to be fixed.
The [base.html](https://github.com/rcpch/rcpch-audit-engine/blob/live/templates/base.html) file is the place to start.

**Comment by anchit-chandran** [comment]
Fixed with #289 , will close once merged
