### ISSUE TITLE
HTMX version duplicated in /static

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#265]
From what I can see in `base.html` we are using 1.8.4 but we have an older version in /static as well

![image](https://user-images.githubusercontent.com/2348385/223983047-16b584ed-0023-467e-97df-f51693c620bb.png)

@eatyourpeas can I just check that HTMX 1.7 can be removed?

**Comment by eatyourpeas** [comment]
Yes it can be removed
