### ISSUE TITLE
Last log in 'elapsed time' is incorrect, and while IP may be useful, the port probably isn't and may confuse users.

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#267]
![image](https://user-images.githubusercontent.com/2348385/224007229-98ef8b6d-13de-4790-8a9e-6e2cd8da23e1.png)

See screenshot - the IP address has the port as well, which is superfluous. Can just show IP address. Maybe consider expressing it within a link that would take the user to a 'Where Is My IP' type site, as this would be helpful for less technical users wanting to find out if the last login was plausibly them.

Also the elapsed time since last login seemed wrong. I hadn't logged in to E12 since the day before. Just maybe need to review the logic for what is being used to evaluate the **start** of the last login period (session creation time).

**Comment by anchit-chandran** [comment]
This is odd - seems to be working fine for me, think @eatyourpeas fixed in [this commit 5 days ago?](https://github.com/rcpch/rcpch-audit-engine/commit/9d9c44091e9560c9912415596847fa07eb596639) 

![Image](https://user-images.githubusercontent.com/68898006/224733867-b73092c1-179b-4c40-b67b-060752a7fe40.png)

**Comment by pacharanero** [comment]
Fixed with e3b57ecaaee49535aa2cc47d271d2301ed61a9ca

**Comment by pacharanero** [comment]
Reopening this because currently the banner displays the details of the _current_ login, not one's actual last login. Should be a simple enough fix.

**Comment by eatyourpeas** [comment]
I think this is just my bad phrasing. Do we need to report the date/time the user last logged in? Why would they need to know? If you are happy I will change it to: ```"{{user}} logged in at {{date/time}} from {{isp_address}}"```

**Comment by pacharanero** [comment]
I think we might be talking at cross purposes here. The purpose of the feature is that you are told that you last logged in at date/time/IP so that you can be alerted to an illicit login which occurred in your absence.

However at the moment the session which is being reported is the _current_ session

![image](https://user-images.githubusercontent.com/2348385/232250763-07b7b487-699d-4f86-ab15-fa58e862d1c0.png)
I just logged in to the dev site, it is Sat 15th April at 20:56 GMT+1, as you can see it's reporting the time I am logging in *now*, which is neither use nor ornament as we say in Yorkshire. (he time in the screenshot is being reported as UTC hence the hour difference. We should probably try to fix the TZ difference at some stage too)

**Comment by eatyourpeas** [comment]
fixed
