### ISSUE TITLE
Mathesar | Open source UI for Postgres databases

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#276]
https://mathesar.org/

I saw this and wondered if it might be useful for data analysis. It could avoid us having to develop bespoke tooling inside the E12 app itself.

**Comment by eatyourpeas** [comment]
This is interesting and would work for us since we have fairly few relationships in our schema.
@nikyraja @AmaniKrayemRCPCH @FridahC have a look and see if you would find this useful?
