### ISSUE TITLE
Scores negative if mental health support sought but not found and no help needed or in place

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#277]
https://github.com/rcpch/rcpch-audit-engine/blob/6d7443eedbe6d53d7c0391545963116e1372d426/epilepsy12/common_view_functions/calculate_kpis.py#L165

Currently the mental_health_support_in_place KPI score negatively for those who don't have have a mental health problem. Ideally this should only be counted only if a MH problem has been sought but not supported, rather than any one for whom no help is in place

**Comment by pacharanero** [comment]
The mental health questions are currently

Multiaxial Diagnosis
![Image](https://user-images.githubusercontent.com/2348385/224374099-80f1adb0-c884-429e-8502-6ecb9229ebd6.png)

Treatment and Care Planning
![Image](https://user-images.githubusercontent.com/2348385/224372389-138e83bc-cd81-4b83-b805-17874d362181.png)

**Comment by pacharanero** [comment]
### Discussed at E12 Meeting 10.03.2023
* @coldunk will take away these 4 data items and arrive at a methodology for which items to use for the KPIs

**Comment by coldunk** [comment]
hopefully this will explain the mapping between our KPIs and current data fields!

![Image](https://user-images.githubusercontent.com/79205365/224382836-12a8f85d-4835-4b75-96d0-92f6a5a8b4bd.png)
