### ISSUE TITLE
Landing page text

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#278]
Landing page text can be moved into the documentation site, except the E12 team contact details, which should still be on the E12 site.

**Comment by AmaniKrayemRCPCH** [comment]
Patient access link - https://www.rcpch.ac.uk/resources/patient-parent-guide-epilepsy12-audit

**Comment by anchit-chandran** [comment]
Fixed with #290 and [#7](https://github.com/rcpch/epilepsy12-documentation/pull/7) from docs repo
