### ISSUE TITLE
Landing page - children and families

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#285]
The expectation on the future road map is for children and families to have access to their own data and approve/withold its submission to the audit. For secure access we have in principle support from NHS login to implement their API.

As discussed with E12 team - this aspiration is not for MVP which is focussed on onboarding clinicians to this platform and ensuring accuracy and usability. 

The child and families tile on the home page therefore should be redirected to the current epilepsy12 reporting page

**implementation**
 @nikyraja to supply redirect URL
alter the href tag for the child and families tile on the landing page
update the documentation

**Comment by pacharanero** [comment]
related to Issue #1

**Comment by anchit-chandran** [comment]
Pt access link for reference https://github.com/rcpch/rcpch-audit-engine/issues/278#issuecomment-1464098286

**Comment by anchit-chandran** [comment]
Fixed with PR #291 ([this commit](https://github.com/rcpch/rcpch-audit-engine/pull/291/commits/7ab1f4938585f88d1aca6151cbe7f61dda67e2b2))
