### ISSUE TITLE
(Experiment) Would the documentation site be better if it was embedded in the E12 application?

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#286]
At one stage the docs site was managed within the codebase of the E12 application, but this presented problems of having to build the static site into a folder and serve it from within Django, which they [expressly warn you not to do](https://docs.djangoproject.com/en/4.1/howto/static-files/) or at least what they suggest adds a bit more complexity as you possibly need to have a separate upload step for the docs site, to a directory on the Web App Service container, from where it can be served.

Because of this we removed the docs site out into its own repo, and it's CI'd by GitHub Actions up to Azure Static Web Sites. This works but it means we have two different URLs for the E12 stuff:

E12 https://epilepsy12.rcpch.tech
Docs https://epilepsy12docs.rcpch.tech/

-----

Alternative approach - `iframe`

* We could put the docs site into the E12 application using an `iframe`
* This would mean we could leave it with its own repo, CI build steps, and deployment infrastructure, but we could style it so it looked better in the existing navigation of E12. 
* It would be easier for users to find the docs
* The styling of the docs would be easier to match with E12 main application
* A technical writer familiar with MkDocs and Markdown (which they are familiar with) could still make their changes without having to get embroiled in a Django codebase (which they probably wouldn't be familiar with)

Thoughts?

**Comment by anchit-chandran** [comment]
This is what it looks like on the [dev site](http://epilepsy12-development.azurewebsites.net/docs).

- I think it integrates quite well and agree with all the benefits you've mentioned, particularly for people just working on docs not having to work with the entire Django project (+more room for errors during the dev environment set up)

![Image](https://user-images.githubusercontent.com/68898006/224936749-8c1aa04c-f666-4357-bef4-c382648d53d5.png)

**Comment by pacharanero** [comment]
Yep, I'm pleased with how that looks and works.

We could remove the RCPCH logo from the docs site, and possibly tweak font sizes to match more closely. I would say that really the fonts on E12 are too small, and trust they should be enlarged rather than reducing font size on the docs site.

**Comment by pacharanero** [comment]
This has been completed and is working well over last few weeks in Dev

**Comment by pacharanero** [comment]
Reopened this issue as I do think it would be better from the point of view of timely edits to the docs site if the docs codebase was embedded within the E12 codebase.

* [x] Stage 1 - bring the docs site codebase within a directory `/docs/` in the E12 codebase, but leave the build system and `<iframe>` display mechanism exactly the same.

* [ ] Stage 2 - change the build system so that `mkdocs build` is executed before `collectstatic` and results in a `/site/` folder somewhere, which can be collected into the static files.

* [ ] Stage 3 - re-engineer the display part of the docs so that Django/gUnicorn renders the static pages and the docs site is 'mounted' at a URL like `https://epilepsy12.rcpch.tech/docs/` and all subsequent parts of the URL pertain to the path within the docs.

Each of these stages can be achieved independently of one another and need not break anything currently working.

**Comment by pacharanero** [comment]
Stage 1 of this Issue completed as part of #599

**Comment by eatyourpeas** [comment]
@pacharanero this looks now to be done?

**Comment by pacharanero** [comment]
Yes, this was all completed a little while ago as part of #599 
Caddy now serves the static documentation site on `https://{baseurl}/docs`.
This has solved all the problems with Django's static file server serving documentation
Happy to close now
