### ISSUE TITLE
Fictional cases for testing

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#292]
There are currently fictional cases which seed the database and these are scored randomly. We could use this logic to generate a test set to run each time a pull request is made or push to dev/live.

Work flow:
1. generate fictional case(s)
2. store results
3. write tests measuring scores, KPIs against these

**Comment by anchit-chandran** [comment]
Related to #350

**Comment by pacharanero** [comment]
Plan was to develop some documents (eg Word) which outline a 'script' for entering a fictional case - from which we can develop automated testing inside the application.

**Comment by pacharanero** [comment]
Testing is now well underway, and @anchit-chandran has developed an extensive suite of Factories which can create testing Cases on demand.
