### ISSUE TITLE
ProgrammingError at /hospital

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#295]
When on https://epilepsy12.rcpch.tech/ on Amani's account, the clinician's access page (https://epilepsy12.rcpch.tech/hospital) comes up with a programming error. 

This issue is not affecting Niky. Unsure if it is affecting other users, but access to the platform will be needed for audit team members, who are testing until 17/3/23. 

![Image](https://user-images.githubusercontent.com/126471383/225029145-bbb0ada6-9ddf-4b83-ac0b-c01dde3ed492.jpeg)

**Comment by eatyourpeas** [comment]
This is now fixed.
