### ISSUE TITLE
Summary of main issues in testing so far

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#299]
- [x] #300
- [x] #301
- [x] #302
- [x] #303
- [x] #304
- [x] #305

**Comment by pacharanero** [comment]
Thanks @AmaniKrayemRCPCH 
I've converted each of those bullet points into its own Issue so they can be addressed.
If/when you have time, could you add detail to the #300 issue to guide us to where the spelling/grammatical errors are?
Similarly #304 - which items appeared multiple times? Screenshots super helpful if poss.

**Comment by AmaniKrayemRCPCH** [comment]
Will do! There's already a few more 'bigger' issues on the log, and other smaller ones, as more people are testing today. I'll send the full list on Monday, when I return from leave.
