### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#3]
Need to decide which fields and table structure we want to use

**Comment by pacharanero** [comment]
I've been seriously thinking about whether MongoDB might be a really good way to build this. It reduces the modelling down to a minimum, we would possibly only need 2 collections - one for each patient and one for each E12 submission.

Patients would have more than one E12 submission.

This approach reduces the upfront modelling and also means we can simply take the entire E12 document and persist it straight as it comes from the webform.

Are there any significant disadvantages to this that you can think of @eatyourpeas?

**Comment by eatyourpeas** [comment]
I don't have any big objections to this. The main thing I have found about nosql databases is that they are great until you start searching for data that is nested more than a layer deep. It starts getting cumbersome after that, and the relational integrity that comes with sql/oracle wins if you have lots of connected tables. The denormalised structure though is appealing and would allow us to add new fields in future without breaking things. I think a deep dive into the existing tables (as we are planning) will make it clear in the end the best way to go.

**Comment by pacharanero** [comment]
Following a development spike on MongoDB we have reverted back to Postgres since there didn't seem to be many advantages to using MongoDB and the Django/Python library integration didn't seem mature enough for production use at this stage.

**Comment by pacharanero** [comment]
Database model has largely been fully reviewed and agreed with the end-users and audit team, so I think we can close this Issue for now as we have most of the data model defined in Django now.
