### ISSUE TITLE
Some spelling/grammatical errors

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#300]

**Comment by AmaniKrayemRCPCH** [comment]
Here are the relevant issues raised

- [x] "On the patient's verification and registration form, in the eligibility criteria text, there is a spelling error in item 3 of the exclusion criteria - "has gone on to have ongoing care within the first year of care for their epilepsy provided by adult or non-NHS services by an inpatient our outpatient, hospital or community paediatric service, or a dedicated paediatric team based in ED."
- [x] "Clinician access page > patient registration form: 7 Treatment and care planning > Should 'antiepilepsy' and 'antiseizure' be hyphenated?" **SNOMED only use unhyphenated versions so kept same**
- [x] "Question 8 of the Epilepsy Context questionnaire just needs a capital H at the start of the sentence, i.e. it currently reads as: “has the diagnosis of epilepsy been withdrawn?”"
- [x] "On the "Edit child details" page change the field labelled currently as "NHS/CHI Number" to simply "NHS Number" as CHI numbers relate of course to Scottish patients and we don't process any Scottish data for Epilepsy12"
- [x] "patient record, section3, question 7 - the information tool tip should ask about focal seizures, not "focal convulsive seizures""
- [x] "Clinician access page > patient registration form: 2 First paediatric assessment > 'Is the first paediatric assessment in an acute or nonacute setting?' should it be 'Was the...?'"

**Comment by anchit-chandran** [comment]
Fixed by PR #308 . Will close issue once PR'd
