### ISSUE TITLE
Formatting of password reset emails. Some password reset emails not received, although reason unclear

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#302]

**Comment by AmaniKrayemRCPCH** [comment]
Example of an email received - 



    <div class='ui container'>

        <div class="ui two column centered grid">

            <div class="column">

                <div class='row'>
                
                    <div class="ui header">
                        <img src='/static/images/epilepsy12-logo-1.3b08f7bf0eb0.png'>
                        <div class="content">
                            <h2>Epilepsy12 password reset</h2>
                        </div>
                    </div>

                    <p>Dear Ms Karina Green,

                    <p>To reset your password to the Epilepsy12 platform, click the link below:</p>

                    <p>http://epilepsy12.rcpch.tech/registration/reset/MjI/bkfm0r-ec4fd65355e89e672600676149845a24/</p>

                    <p>If clicking the link above doesn't work, please copy and paste the URL in a new browser window instead.</p>
                    <p>If you did not make this request, please contact the RCPCH Epilepsy12 team.</p>

                    <p>Sincerely,</p>
                    <p>The RCPCH Epilepsy12 team</p>
                
                </div>
            
            </div>
        
        </div>

    </div>

**Comment by eatyourpeas** [comment]
The styling is now fixed and emails are sending/receiving on testing
