### ISSUE TITLE
Errors when creating new users

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#314]
- [ ] Error when adding users on Amani's account
```[09:55] Amani Krayem  Registration Unsuccessful: <ul class="errorlist"><li>hospital_employer<ul class="errorlist"><li>This field is required.</li></ul></li></ul>```  amani.krayem@rcpch.ac.uk, 02/03/2023
- [ ] Once you have tried to add the new user it doesn’t save the details and instead an error notice appears which reads as: 
```Registration Unsuccessful: <ul class="errorlist"><li>email<ul class="errorlist"><li>This email address is already in use.</li></ul></li></ul>``` 
 epilepsy12@rcpch.ac.uk, 20/03/2023

**Comment by pacharanero** [comment]
I can replicate this

![Image](https://user-images.githubusercontent.com/2348385/228210331-0977b2db-bbec-4dde-9155-9bbcd24b283c.png)

**Comment by eatyourpeas** [comment]
thank you this is fixed in the version now live on development. Now errors are redirected back to the form and signposted under the field in question. @pacharanero could you please confirm you are happy with this work flow and close if so? Any problems do please post back here.
