### ISSUE TITLE
No way to tell which site a user belongs to

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#316]
When on national view (for staff or patients), there's no way for the E12 project team to see which site a user/patient belongs to. Maybe that should be another column?

amani.krayem@rcpch.ac.uk, 02/03/2023

**Comment by eatyourpeas** [comment]
Good point!
- [x] add user.hospital_employer in Django-template to the user template and an extra column

**Comment by anchit-chandran** [comment]
Added `hospital_employer` for user table 



![Image](https://user-images.githubusercontent.com/68898006/228339700-06996156-e444-489f-aac4-64d6ed0f52c5.png)





Couldn't work out where to find the `hospital_trust` for each patient. Trying `case.hospital_trusts` returns `epilepsy12.HospitalTrust.None` for each `case`


![Image](https://user-images.githubusercontent.com/68898006/228340166-bbb202a4-d67e-462e-92db-66e069ce59c8.png)

**Comment by anchit-chandran** [comment]
Closing this as fixed for users.

Will open another issue for patients
