### ISSUE TITLE
What happens to the data for Ineligible patients?

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#317]
What happens to patients who are not eligible? If the clinician never ticks the 'I confirm this patient is eligible' box, then the patient and their demographic data will sit there. Should clinicians be able to say 'this patient is not eligible' and, in turn, their data is deleted/record locked?

amani.krayem@rcpch.ac.uk, 08/03/2023

**Comment by pacharanero** [comment]
@eatyourpeas will know what happens here. We definitely have a separate 'opt out' system which blanks out the patient data, however I'm not sure what happens in the case of patients who are not eligible. There is no particular reason to keep their data if it is not going to be analysed. We might want to keep track of the proportion of patients registered who turn out not to be eligible, for statistical purposes, but not keep detailed information on them.

**Comment by eatyourpeas** [comment]
As it stands they cannot progress. To unlock the steps on the left hand side of the screen you have to confirm the child has epilepsy, allocate a lead centre and only after that can you set a date of first paediatric assessment. With those three data points the progress unlocks and the child is registered formally in the audit and the fields can be completed. We could potentially delete all those incomplete records when the audit closes, but I would be inclined to leave them - it would give us an idea of how many are entered.

**Comment by pacharanero** [comment]
I have a feeling that even with S251 approval, IG best practice is to minimise the data held. If we are not analysing this data then we shouldn't keep it. We could anonymise the records in a similar way to an opt-out?

**Comment by pacharanero** [comment]
There is a feature of the platform to delete data if the centre lead wishes to do so
