### ISSUE TITLE
Opt-out

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#318]
Following on from the above, is there a way for clinicians to say 'this patient has opted out from the audit' and, in turn, the patient's record is deleted?

amani.krayem@rcpch.ac.uk 08/03/2023

**Comment by eatyourpeas** [comment]
If you go to edit case (the pencil icon from the patient list) there is a large message box with a red box offering the user to opt out with a warning and confirmation modal. if you go ahead, the record is removed except for the database identifier to show there was once a patient there. 
Currently the cohort too is removed but maybe you want to leave that so you know which cohorts have how many dropouts?
Any opt-outs show up in the patient list as ###

**Comment by nikyraja** [comment]
Thank! This looks good.

Would be good to keep the cohort if possible. 

We can remove the records from the patient list so clinicians don't see them, we just need to keep a record somewhere for E12 team. Are there record IDs that we could use here (no patient info)?
