### ISSUE TITLE
Ethnicity graph labels

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#319]
Clinician access page:
Distribution pie chart key labels are cut off (i.e White an[d Asian], Not Spe[cified])

Also White and Asian makes it look like these ethnicities have been grouped together. Perhaps it could instead be labelled 'Mixed: White and Asian' instead?

karina.green@rcpch.ac.uk, 9/3/23

![Image](https://user-images.githubusercontent.com/126471383/227987485-7353f8a9-30f7-4522-88c4-22f294ac4ac0.PNG)

**Comment by anchit-chandran** [comment]
Updated ethnicity titles 

![Image](https://user-images.githubusercontent.com/68898006/228263399-efaec603-f1d8-44cc-ab3d-23a0eb97b7fe.png)

**Comment by eatyourpeas** [comment]
Thanks @anchit-chandran - if you are happy that is reflected in the UI etc would you be happy to send through a PR and I will merge?

**Comment by anchit-chandran** [comment]
Can't find an easy way to wrap the legend labels which are being cut-off (see: StackOverflow: https://stackoverflow.com/questions/40792349/how-to-wrap-legend-text-in-chartjs).

A more intuitive method could be to change layout so visualisations have more space?

**Comment by pacharanero** [comment]
I think having reviewed this that the solution is actually to remove the key/legend from the right entirely.

The ethnicity types are easily visible using hover/tooltip

This also avoids the problem of there being insufficient width in the box to display the full name of the ethnicity type AND also there being insufficient height in the box to display all 16 ethnicities (currently only the top 7 being shown)

**Comment by anchit-chandran** [comment]
Preview:



![Image](https://user-images.githubusercontent.com/68898006/231707573-cfb5167e-163b-408f-ad46-9e4472259a8d.png)
