### ISSUE TITLE
Deprivation graph labels

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#320]
Clinician access page:
Distribution by deprivation quintile key label just says '5', I think this needs more explanation e.g Most/Least deprived (not sure what 5 is lol)

karina.green@rcpch.ac.uk, 9/3/23

![Image](https://user-images.githubusercontent.com/126471383/227987719-8b2a8a42-333c-4a48-b5f2-c154d71e004e.PNG)

**Comment by eatyourpeas** [comment]
thanks @AmaniKrayemRCPCH - I agree it could be clearer. The numbers are the quintiles, 5 least deprived, one most deprived. We should make this clear in the charts.

**Comment by anchit-chandran** [comment]
does this make more sense? 

![Image](https://user-images.githubusercontent.com/68898006/230644604-4a90806b-b82a-4746-b57f-bd9a32ec22b9.png)

can have any mapping:
```
deprivation_quintile_str_map = {
    1 : '1st quintile',
    2 : '2nd quintile',
    3 : '3rd quintile',
    4 : '4th quintile',
    5 : '5th quintile',
}
```

**Comment by anchit-chandran** [comment]
Added a tooltip to make extra clear. @AmaniKrayemRCPCH let me know if happy to close :)

![Image](https://user-images.githubusercontent.com/68898006/231501485-e2d77e1b-b981-4130-a380-6f9bd9b50a54.png)

**Comment by AmaniKrayemRCPCH** [comment]
That's great! Happy to close.
