### ISSUE TITLE
Unclear why a case was not created.

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#321]
Clinician access page:
I tried adding a new patient with two instances of bad info - a DOB year of 1959 and a 16 digit NHS number. It didn't let me create the case, it came back with a warning saying 'Case not created'. Very good that it didn't allow it, but is there any way of letting the user know why - e.g. warning 'DOB must be between X-X' or 'NHS number must be 10 digits' or just automatic visual validation, like a red box around an nhs number that is too long/short

(I was able to add a patient just fine when I put a normal DOB and NHS no! :) )

karina.green@rcpch.ac.uk, 09/03/2023

**Comment by eatyourpeas** [comment]
Thanks for this @AmaniKrayemRCPCH This should have already been fixed. related to #341.
Again, @pacharanero and @anchit-chandran I would be grateful if you could check the workflow around new users and new cases in the development branch.
