### ISSUE TITLE
Time last logged in

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#324]
- [x] Last logged in message - the time format does not handle 0s correctly - "You last logged in at 12:4". Should be 12:04 amani.krayem@rcpch.ac.uk, 20/03/2023
- [x] Time last logged in has not updated with daylight savings
- [ ] Does it make sense to use location instead of IP address in this notification

**Comment by pacharanero** [comment]
> Does it make sense to use location instead of IP address in this notification

To convert IP address to an (approximate) location we would need to call an external API such as MaxMind Geo Information API https://dev.maxmind.com/geoip/geolite2-free-geolocation-data?lang=en which for the free tier is limited to 1000 lookups per day, this might be enough for us possibly.

**Comment by pacharanero** [comment]
Sorry 1000 lookups per day

**Comment by eatyourpeas** [comment]
Or we could do both :).

**Comment by anchit-chandran** [comment]
Time logs now fixed, postgres db's timezone set to London time taking into account DST. Currently hard coded in `docker-compose` NOT in an env variable yet

**Comment by anchit-chandran** [comment]
will close once PR'd
