### ISSUE TITLE
Can't complete multiaxial diagnosis

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#326]
I don’t seem to be able to fully complete the Multiaxial diagnosis (DESSCRIBE) form as it sticks on 23/24 questions answered. Not sure if that relates to the final Add details of any known mental health problem(s) question?

epilepsy12@rcpch.ac.uk 20/03/2023

**Comment by eatyourpeas** [comment]
I did identify an issue with this in a previous commit and fixed it, though will only be live in development branch, not live branch. Could you please send through steps to reproduce this error?

**Comment by AmaniKrayemRCPCH** [comment]
I've tried to play around to find the issue. I think it's where episode/syndrome entries aren't complete but it's hard to identify when that's the case.

For example, I've found these patients with incomplete section 4 

1. Isabella Awour 2873193609 - I can't seem to find what's missing. 
2. Josh Albie 7010056954 - Multiaxial diagnosis was marked as incomplete until I went into the first episode type, and selected an answer to the question 'How best describes the generalised nature of the epileptic episode(s)?', which was left blank. There was no indicator of missing data here. 
3. Carley Beirne 3645064151 - There is an indicator of missing data on one of the syndromes.

**Comment by eatyourpeas** [comment]
1. The only episode entered for Isabella Awour is non epileptic so no measures for episode are counted. If you enter an epileptic episode (either generalised or focal) it should complete as expected
2. This is helpful feedback. I will look at better signposting to incomplete fields episodes, causes and syndromes
3. Carley Beirne had 3 syndromes entered but one of them had no diagnosis date denoting an incomplete field. Once that was completed you can see a pink tick appeared and the dial incremented.

The multiaxial description form is by far the most complicated as the denominator changes a lot depending what items are selected and not. I think it is all working though it is quite possible there are permutations that have not been tested.

I think to close this issue I will:
- [ ] implement feedback to user if any fields hidden in the subforms (episode/syndrome and causes) are incomplete.

**Comment by eatyourpeas** [comment]
There was a mistake in the maths for children with non epilepsy whose onset was described as other. This has been fixed.
Also I have made it clearer if episodes have been incompletely filled or if there are episodes scored but none of them epileptic.
<img width="777" alt="image" src="https://user-images.githubusercontent.com/1058647/229619630-8eb01ad9-407d-4ada-95c7-61ca4104d12a.png">
