### ISSUE TITLE
Allowing incorrect dates to be entered.

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#327]
- [x] In the Milestones section you can currently enter a date (a long way) into the future in response to the question “"Date seen by a consultant paediatrician with expertise in epilepsies." Also not sure how the Time to Review is calculated but I was able to enter dates where it calculated that the review should be undertaken in three years’ time. epilepsy12@rcpch.ac.uk, 20/3/2023
- [x] For the Paediatric Neurology section of Milestones you can enter a date way into the future for the Date seen by consultant paediatric neurologist question and have a Time of Review indicated as up to 5 years’ time. epilepsy12@rcpch.ac.uk, 20/3/2023
- [x] It is currently possible to enter a data way into the future for the date seen by the CESS. epilepsy12@rcpch.ac.uk, 20/3/2023
- [x] For the Epilepsy Specialist Nurse section of Milestones you can enter a date way into the future for the Date seen by an epilepsy nurse specialist question. epilepsy12@rcpch.ac.uk, 20/3/2023
- [x] Overall, should it be possible to enter dates of interventions prior to the date of the First Paediatric Assessment?. epilepsy12@rcpch.ac.uk, 20/3/2023
- [x] For the Tests section you can enter a date into the future for the Date EEG performed field. epilepsy12@rcpch.ac.uk, 20/3/2023
- [x] For the Tests section you can enter a date into the future for the Date MRI brain reported field. epilepsy12@rcpch.ac.uk, 20/3/2023

**Comment by eatyourpeas** [comment]
This is allied to #288 
It is possible to constrain the dates but I am not clear from @coldunk 's previous answer what ultimately you want to happen. If you allow dates in the future (currently that is the case), it needs to be possible that the scan/referral etc is not complete/reported etc by the close of audit. 
Question to the E12 team therefore is how would you like dates constrained? (currently seen or performed dates cannot be before the request dates but in theory can be at any time in the past or future)

**Comment by anchit-chandran** [comment]
![Image](https://user-images.githubusercontent.com/68898006/235894004-1363247a-7d4a-4249-b132-3ebd5ef70654.png)

**Comment by anchit-chandran** [comment]
Full list will be provided by RCPCH team @AmaniKrayemRCPCH

**Comment by eatyourpeas** [comment]
This now fixed
