### ISSUE TITLE
Epilepsy12 button unclear

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#328]
When going to complete a patient record, the 'Epilepsy12' button is unclear. Maybe it should say something like 'Edit Record'

amani.krayem@rcpch.ac.uk, 21/03/2023

**Comment by anchit-chandran** [comment]
changed to "`Audit`" instead of "`Edit Record`" as thought it would differentiate from editing the child's details. Does this make sense to you or would you rather "`Edit Record`"?

![Image](https://user-images.githubusercontent.com/68898006/228346781-05abc8dd-586f-44d2-b460-f5b64ca37585.png)
