### ISSUE TITLE
Clinician Access Page Comments

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#329]
Some comments relating to the landing page - It would be good for the patient list to be more prominent on the landing page, that is to say I know there is a button on the top right which reads as "View All (Trust Name) Children" however it should probably have greater prominence than the "View all Staff" button to the left of it. I would have thought that in terms of display the large box with the Trust name and address and contact details doesn't need to be so big (only helpful for us as Epilepsy12 admins I would think as opposed to Trust users themselves?). The current cohort and days remaining is helpful for users, however it probably doesn't need to be so large and how would you access details of other cohorts from there? The two "Completed Returns" dials in the box to the right of it are a bit confusing as I am not sure what the difference is between the two. 

epilepsy12@rcpch.ac.uk

**Comment by eatyourpeas** [comment]
fixed
