### ISSUE TITLE
implement 5000 character cut off

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#33]
```
    TODO implement 5000 character cut off
```

https://github.com/rcpch/rcpch-audit-engine/blob/55ae3bbfed2962c39af773f886c8a688fe27b02d/epilepsy12/view_folder/multiaxial_description_views.py#L28

**Comment by eatyourpeas** [comment]
Implemented in [d333ab6](https://github.com/rcpch/rcpch-audit-engine/commit/d333ab603fd401ee04879d0e863d100ad782a6e2)

**Comment by pacharanero** [comment]
Has been implemented but doesn't appear to be working at the moment.
5000 character limit has not bee tested

**Comment by eatyourpeas** [comment]
In fact 5000 characters is way too much so an upper limit has been set at 2000 characters and this has been implemented in the UI
