### ISSUE TITLE
Edit child details

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#330]
- [ ] The "Edit child details" button on the patient row of the patient list page allows you to change all of the key info for that patient including name, date of birth, NHS number etc. Did we definitely want to allow that degree of editing or is there any instance where we want some of those key elements to be locked down prior to the care data entry process? epilepsy12@rcpch.ac.uk, 21/03/2023

**Comment by eatyourpeas** [comment]
It is possible to lock down editing of certain fields but the decision made some time back was to allow blanket edit only or view only depending on user group. One to discuss within E12.

**Comment by eatyourpeas** [comment]
closed
