### ISSUE TITLE
Missing items unclear in patient form

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#331]
Overall for the patient data entry, it is helpful to see the number and % of completion of data fields for each section but is there an easy way to for the outstanding data fields to be highlighted/listed so that you can be aware of where you need to go to be able to fully complete the dataset for the child? That function may already exist however I couldn't intuitively see one.

epilepsy12@rcpch.ac.uk, 21/03/2023

**Comment by eatyourpeas** [comment]
I have wondered about this but not that clear how best to implement it. Bearing in mind that if you go to the audit forms the incomplete field will be in the form that is not yet pink and so should be easy to find. Perhaps one we could discuss?

**Comment by eatyourpeas** [comment]
This has been addressed with clearer signposting in the forms to highlight incomplete fields
