### ISSUE TITLE
Resizing

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#333]
- [ ] Real time KPI metrics overrun on a small browser window. 
amani.krayem@rcpch.ac.uk, 21/03/2023

- [ ] View patients buttons overrun on small window
amani.krayem@rcpch.ac.uk, 27/03/2023

![Image](https://user-images.githubusercontent.com/126471383/228002985-f2ef42fa-342b-4215-8a3c-7c0a7fab5f9c.PNG)

**Comment by eatyourpeas** [comment]
@anchit-chandran this is a ```<div class='ui buttons>``` customised element in ```templates/partials/page_elements```. Do you think we can encourage the buttons to wrap on small screens or maybe change size on narrow screens?

**Comment by anchit-chandran** [comment]
Fixed using some manual css flexbox, couldn't work out how to do with `SUI`

![image](https://user-images.githubusercontent.com/68898006/228332681-4244761c-0e9c-4557-9e3b-9385fa1857fc.png)

**Comment by anchit-chandran** [comment]
will close one PR'd

**Comment by eatyourpeas** [comment]
fixed
