### ISSUE TITLE
Patient search providing patients from other sites

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#334]
- [ ] Currently when in the patient list for the Norfolk and Suffolk Trust as the epilepsy12@rcpch.ac.uk user I started typing "g" into the "Start typing to Filter by name or NHS Number" seach box and it brought up a list of what I assume might be any children and young people on the system added by all Trusts, not just for Norfolk as I know that there is only 1 patient added for Norfolk so far.  I can see the names, DoB, NHS number etc. for all of those children. I do get an "403 - Access Denied" notice appearing if I try to click to Complete audit details or Register buttons for those patients not within my Trust but I shouldn't be able to see them in the first place.

epilepsy12@rcpch.ac.uk, 21/03/2023

- [ ] The system currently allows you to "Submit to Epilepsy12" a case for a patient who isn't actually part of your Trust
epilepsy12@rcpch.ac.uk, 21/03/2023

**Comment by eatyourpeas** [comment]
Good spot thank you - allied to another issue about filtering but not the same.

**Comment by eatyourpeas** [comment]
fixed
