### ISSUE TITLE
Performance summary - PI not applicable

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#335]
N/A icon needed in the patient performance summary tab for performance indicators which they are not eligible for.

**Comment by eatyourpeas** [comment]
This has been implemented in the following way and signed off by @coldunk 
Live in development branch but not yet in live branch, so will move these changes over in due course.
<img width="775" alt="image" src="https://user-images.githubusercontent.com/1058647/228271893-559317fa-fb23-4dcc-831f-5b0e124ccb15.png">
