### ISSUE TITLE
Multiaxial diagnosis - No known cause

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#336]
This might be a misunderstanding on my part, but does it make sense to have the 'Not Known' option and the first question on the cause item (see screenshot). Surely if a cause is not known, people would say no to 'has a cause been identified'. Having both questions would lead to errors in interpretation. 

amani.krayem@rcpch.ac.uk, 27/03/2023

Edit: I now realise that this has been the format for the audit up until now. Maybe something for discussion, unless I've misunderstood the issue.

**Comment by eatyourpeas** [comment]
Not at all @AmaniKrayemRCPCH very good observation. The dropdowns for those questions were moved wholesale from the existing platform. Happy to change things like the order or the choices if you wish. Perhaps @coldunk can guide.

**Comment by anchit-chandran** [comment]
- [ ] REMOVE 'Not known' from  category options
- [ ] ADD 'Other' option to "main identified cause of the epilepsy" in dropdown

**Comment by pacharanero** [comment]
As part of fixing this issue it would be good if we could review the SNOMED-derived list of Epilepsy Causes in the options, so that there are no duplicates and the list is appropriate. We need to arrange a meeting with @coldunk to review these conditions.

**Comment by anchit-chandran** [comment]
@eatyourpeas did you complete in 2fa branch?

**Comment by anchit-chandran** [comment]
Implemented as so. Will close on PR of `perms-custom` branch

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/68898006/c025844e-4374-4f55-ac3f-b725706c4d84)
