### ISSUE TITLE
Home page when logged in

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#337]
Patient access button is not needed when logged in as staff. Should a user be directed to the relevant page (clinician/patient access) once logged in. 

amani.krayem@rcpch.ac.uk

**Comment by anchit-chandran** [comment]
I checked for `if request.user|has_group:"patient_access"` to only show the patient access tab if the user is a patient. Does this look right @eatyourpeas ? should we remove `clinician access` if their user group is `patient_access`?


**base view**
![Image](https://user-images.githubusercontent.com/68898006/228555950-7379405c-0bd5-4094-8444-d7b5ea6b5df8.png)


**user group is NOT patient**
![Image](https://user-images.githubusercontent.com/68898006/228555937-42086e6b-f0e3-48b2-9a48-d1e5364a7569.png)

**user group is patient**
![Image](https://user-images.githubusercontent.com/68898006/228555971-d884ba12-7b48-4247-93c7-24a3d741e50a.png)




![Image](https://user-images.githubusercontent.com/68898006/228560152-ce58f607-6731-4214-93e3-15cb57406483.png)

**Comment by pacharanero** [comment]
Yep I'd say don't show clinician access if it's a patient logged in.
Don't show patient access if it's a clinician logged in.
Try to keep the logic for this as simple as possible and ideally not too duplicated in the templates.

**Comment by anchit-chandran** [comment]
Cool fixed. Will close once PR'd

### Patient view (`{% if request.user|has_group:"patient_access" %}`)
![image](https://user-images.githubusercontent.com/68898006/228617207-416ad5e4-885e-4256-a814-dc9919cfebc1.png)

### Clinician view (`{% if not request.user|has_group:"patient_access"  %}`)
![image](https://user-images.githubusercontent.com/68898006/228617341-1b00ed4a-3be1-4a12-828a-cbb9bb370646.png)

**Comment by pacharanero** [comment]
I presume Database Management is only shown to Admins?
I would probably suggest renaming this tab to Admin and moving it to the far right of the nav

**Comment by anchit-chandran** [comment]
![Image](https://user-images.githubusercontent.com/68898006/228765444-fc4ff1ea-b11e-45ce-b8d1-a31a01658777.png)

**Comment by anchit-chandran** [comment]
Will close if happy + once PR'd

**Comment by eatyourpeas** [comment]
fixed
