### ISSUE TITLE
Can terms of service go in documentation

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#338]

**Comment by pacharanero** [comment]
Yes, this would seem like a good idea, fairly straightforward to do.

**Comment by pacharanero** [comment]
The T&Cs section has been moved from the Django site to the Documentation site
docs: https://github.com/rcpch/epilepsy12-documentation/commit/c2991573999f8e28c5a56cd5169614016f9787ca
e12: d685195396963e96ef337fb8e74f5f05bcb204e5

**Comment by pacharanero** [comment]
this is working on the development server now, will be merged into live tomorrow
