### ISSUE TITLE
Completed Returns repeating hospital name

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#339]
Clinician access page:
There are two 'Completed Returns' sections - one iabelled with the full name of the hospital 'Abbey Sefton Hospital (University Hospital Aintree)' while the other just has 'Abbey Sefton Hospital', should they be labelled the same?

karina.green@rcpch.ac.uk 9/3/23

![Image](https://user-images.githubusercontent.com/126471383/227988173-06dbde48-4122-4b79-a9b4-c973b28de273.PNG)

**Comment by anchit-chandran** [comment]
Abbey Sefton Hospital's `ParentName` is called "Abbey Sefton Hospital (University Hospital Aintree)". Might be a case of editing in our database if this is incorrect @eatyourpeas ?

![Image](https://user-images.githubusercontent.com/68898006/228559196-b19be471-cd44-4624-ab23-3aa682e1132a.png)

**Comment by anchit-chandran** [comment]
Updated: `"ParentName": "University Hospital Aintree"`. Will close once PR'd
