### ISSUE TITLE
KPI Table View

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#340]
- [x] Clinician access page: On the 'Overview' table, I think the header 'Real-time KPI Metrics' should be renamed to 'Real-time key performance indicator (KPI) metrics'
- [x] I know that the Real-time KPI Metrics dashboard isn't ready to test yet in the sense that no data is connecting through to it as yet, but in terms of appearance: There seem to be 19 KPIs listed currently. I know that is because the current list includes all of the sub metrics which feed the three separate overall indicators for Comprehensive Care Plan agreement and Comprehensive Care content and Teritary input and that I am stating the obvious but the formatting will need to make it clear that there are 10 KPIs but that three of them are "fed by" sub metrics. epilepsy12@rcpch.ac.uk 21/03/2023
- [x] Suggest editing the information note at the bottom of the KPIs table so that it reads as: "These are key indicators for your Health Board/Trust, compared to the percentages for your relevant ICB, NHS England Region, OPEN UK Region, Country and England and Wales combined". epilepsy12@rcpch.ac.uk 21/03/2023
- [x] For the Real-time KPI table, label the second column as "Health Board/Trust" rathen than "Trust" and also label the column on the right hand side as "England & Wales combined" as opposed to National. epilepsy12@rcpch.ac.uk 21/03/2023
- [x] On clinician access page, number the 10 performace indicators (on patient summary tab too). niky.raja@rcpch.ac.uk, 21/03/2023

**Comment by eatyourpeas** [comment]
@anchit-chandran would you be happy to look at this? One perhaps the 3 of us otherwise could pair (is there a word for that involving 3 people?) on?

**Comment by anchit-chandran** [comment]
@AmaniKrayemRCPCH i wanted to confirm if this numbering for the kpi's is correct 

![Image](https://user-images.githubusercontent.com/68898006/228583638-a2ba328b-dd61-420e-9420-f5be0032dc4e.png)

**Comment by anchit-chandran** [comment]
^went with this numbering. If happy with the styling, will close (also added background color on hover)



![Image](https://user-images.githubusercontent.com/68898006/228592773-f2a1bd66-9614-43e5-be2a-bcfd71ce2511.gif)

**Comment by eatyourpeas** [comment]
fixed with #359

**Comment by AmaniKrayemRCPCH** [comment]
Hello! Sorry for the delayed reply. 
I'd just like to update the numbering for 9a &9b. 

9a. Care planning agreement
a. Patient-held individualised epilepsy document/copy of clinic letter that includes care planning information
b. Patient/carer/parent agreement to care planning
c. Care planning has been updated when necessary. 

9b. Care Planning content
a. Parental prolonged seizures care plan
b. Water safety
c. First aid
d. General participation and risk
e. SUDEP
f. Service contact details

So there is no Performance indicator 9. It's been separated out into 9a and 9b. 
9a is present if all of the sub measures are present (9a.a, 9a.b, and 9a.c). 

<img width="222" alt="9aCalculation" src="https://user-images.githubusercontent.com/126471383/229514660-e51b07cf-3d5f-4684-ba9d-c5e43000eb0e.PNG">

9b is present if 9b.a is present **if the patient is prescribed rescue medication**, and if all of the remaining sub measures are present (9b.b, 9b.c, 9b.e, 9b.d, and 9b.f)

<img width="218" alt="9bCalculation" src="https://user-images.githubusercontent.com/126471383/229514704-bb71f36f-9cf4-430e-953c-79d98641982a.PNG">

Let me know if this needs clarification. You can see the calculations [here](https://www.rcpch.ac.uk/sites/default/files/2022-09/epilepsy12_round_4_methodology_overview.pdf)

**Comment by AmaniKrayemRCPCH** [comment]
@anchit-chandran Heya. Just checking if you've seen my comment above updating the numbering. I realised I added a comment to a closed ticket.
