### ISSUE TITLE
Cannot create new patients

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#341]
I can't currently add any new patients on the API test site as I get the following Error message when trying to save the details I have entered: 500 - Server ErrorE12 Server error. Our apologies for this. If this error persists please contact the E12 team or go back to the home page

epilepsy12@rcpch.ac.uk, 21/03/2023

**Comment by eatyourpeas** [comment]
This should now be fixed and live in the development branch, but not yet in live. @pacharanero or @anchit-chandran could you please test in the dev site and confirm that it is possible to add a new patient and that any expected errors (eg wrong NHS number, existing NHS number, DoB in the future, mandatory fields missing) all post meaningful messages back to the form?

**Comment by anchit-chandran** [comment]
yep testing now

**Comment by anchit-chandran** [comment]
All seems fine with adding cases + appropriate errors on the dev branch 
![image](https://user-images.githubusercontent.com/68898006/228270980-724559d0-c36c-4a63-abdc-525d4687e691.png)

**Comment by eatyourpeas** [comment]
sorted as per comment above.
