### ISSUE TITLE
NHS/CHI number terminology

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#342]
- [ ] On the "Edit child details" page change the field labelled currently as "NHS/CHI Number" to simply "NHS Number" as CHI numbers relate of course to Scottish patients and we don't process any Scottish data for Epilepsy12. epilepsy12@rcpch.ac.uk, 21/03/2023

**Comment by anchit-chandran** [comment]
Fixed with #308
