### ISSUE TITLE
Duplicate patient

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#343]
It seems as though the system does not check against a patient already being on the system as I can see two children listed who both have the same NHS number: Frankie Barber	Female	6409037418

epilepsy12@rcpch.ac.uk 21/03/2023

**Comment by pacharanero** [comment]
We can check for NHS Number uniqueness and prevent children being added a second time.
What would be the preferred behaviour if a child is already on the system?
It's possible that two centres could be providing care (secondary/tertiary?) and not know that the other one has already entered them onto the system?

We could for example say:

* A child with this NHS Number has already been entered on the system.
* Please check the NHS number carefully in case of error.
* If this child has already been entered on the system for YOUR organisation, then you do not need to enter it again.
* If this child has already been entered on the system for ANOTHER organisation, then if you can confirm that the child's identity is the same, you may need to change the Primary or Secondary care centre.
Thoughts?

**Comment by eatyourpeas** [comment]
This has been fixed in the recent spate of PRs when the add_case form was rebuilt. It should now not be possible to add either an invalid NHS number or a child that is already anyway on the database. 
@AmaniKrayemRCPCH could you please confirm if you want it to be possible to reregister a child that has been in a previous cohort?

**Comment by eatyourpeas** [comment]
This is now fixed
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/1058647/229305004-895f9ddd-5d3c-4554-a8d6-7811e3c97723.png">
