### ISSUE TITLE
User search not working

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#344]
I'm not sure if the "Start typing to Filter by name or NHS Number" search function is currently working within the Add Trust Users form

epilepsy12@rcpch.ac.uk 21/03/2023

**Comment by pacharanero** [comment]
Good spot. It seems to work for National View but not in Trust or Hospital View.

**Comment by eatyourpeas** [comment]
Thank you - this is broken in the live branch but fixed in development. However, filtering here does not take account of the user's own hospital so is a vulnerability - thank you for picking this up. Again, @pacharanero perhaps I can allocate to you and we fix together?

**Comment by eatyourpeas** [comment]
I think this is now fixed @pacharanero ?

**Comment by eatyourpeas** [comment]
closed with #357
