### ISSUE TITLE
Current cohort date incorrect

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#346]
Submission date/cohort isn't correct on the clinician landing page. The current live cohort shoudl be cohort 5 (first assessemtn 1 decemebr 2021 - 30 Novemer 2023), as teams are now entering data on the first year of care of the patients in cohort 5. The submission date for cohort 5 is 10 Jan 2024. Check back to this issue for the logic: https://github.com/rcpch/rcpch-audit-engine/issues/215
The logic is correct in indivual patient records 

niky.raja@rcpch.ac.uk, 27/03/2023

**Comment by eatyourpeas** [comment]
@pacharanero nice one for you since you did the original cohort function. There are a few more functions in that folder we could perhaps pair on?

**Comment by eatyourpeas** [comment]
I think I will need another explainer @AmaniKrayemRCPCH 
Your example above suggests cohort 5 is 2 years long.
It is currently coded that the cohort runs from 1st Dec - 30th Nov the following year, with the submission date the following Jan (second week on Tuesday).
So this would suggest
| cohort number | start date | end date | submission date |
|----------------|-----------|----------|-----------------|
|  5 | 1/12/21 | 30/11/22 | 10/1/2023 |
| 6 | 1/12/22 | 30/11/23 | 9/1/2024 |
---------------------------------

I know this is not correct. Could you explain again please?

**Comment by AmaniKrayemRCPCH** [comment]
Hi Simon, 

I think the confusion is around the assessment dates. 

Cohort 5 patients will have their first assessment between 1/12/21 and 30/11/22. So their first year of care will finish between 1/12/22 and 30/11/23. The submission date will be the January after the last patient completes a year of care - 10/1/24. 

The start date and end date in your table can compute which cohort a patient is in. Those are correct. 
The submission date needs +1 year. 

Hopefully this makes sense.

**Comment by eatyourpeas** [comment]
This is fixed

**Comment by eatyourpeas** [comment]
This is not fixed it seems.

**Comment by AmaniKrayemRCPCH** [comment]
Realise that I explained this poorly in my above comment. 

Cohort 6 submission deadline is 14/01/2025 - 
Cohort 7 is 13/01/2023 - 

So, in cohort 6, the latest a child will have their first assessment is 30/11/2023. The audit collects data from the first year of care. 
If a child has an assessment on 30/11/2023, the audit period for them will end on 30/11/2024. 

The data deadline is then the **second tuesday of the January** after the last child completes one year of care. 

If its easier, just think that Cohort 6 is 2025, cohort 7 is 2026, and so on. The deadline will always been in the second tuesday of January.

**Comment by AmaniKrayemRCPCH** [comment]
There was also an issue with the days remaining figure on the organisation page. It currently says 0 days remaining

**Comment by anchit-chandran** [comment]
Hi Amani, can i confirm these dates?

For Cohort 6, when should be the latest date of first paediatric assessment and latest data submission date (the 2nd Jan Tues of which year?).

From what I understand:

`earliest date of first paediatric assessment` = `YYYY-12-01`
`latest date of first paediatric assessment` = `YYYY-11-30`

`latest data submission date` = the first `2nd Tuesday in Jan` AFTER the `latest date of first paediatric assessment` 

For Cohort 6, what would be the dates for the above `date variables`?

**Comment by AmaniKrayemRCPCH** [comment]
Hi Anchit - mostly correct. 
`latest data submission date` = the first `2nd Tuesday in Jan` AFTER  `the latest date of first paediatric assessment + one year`. 

This is because we need to collect data on **one year** of care for each patient. 

For Cohort 6:

`earliest date of first paediatric assessment` = `2022-12-01`
`latest date of first paediatric assessment` = `2023-11-30`
`latest data submission date` = `2025-01-14`

(`latest data submission date` = the first `2nd tuesday in jan` after `2024-11-30`)

**Comment by anchit-chandran** [comment]
Given that today is 2023-08-30, is this correct now:


![Image](https://github.com/rcpch/rcpch-audit-engine/assets/68898006/34e0ab18-c726-4a0f-81b1-ca5385bdfa63)

Raw data:
```
cohort_data={
  'cohort': 6, 
  'cohort_start_date': datetime.date(2022, 12, 1), 
  'cohort_end_date': datetime.date(2023, 11, 30), 
  'submission_date': datetime.date(2025, 1, 14), 
  'days_remaining_until_cohort_end_date': 364, 
  'days_remaining_until_latest_submission': 503
}
```
