### ISSUE TITLE
Cannot select reason for no postcode

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#348]
Creating new patient - after selecting 'no postcode', i can't select why. I get an error saying

amani.krayem@rcpch.ac.uk, 27/03/2023

![Image](https://user-images.githubusercontent.com/126471383/228011219-9be67a36-85f4-489b-b5fa-cb261e242efa.PNG)

**Comment by eatyourpeas** [comment]
Thanks for identifying this. This is a bug and relates to not passing the correct permission to the partial template

**Comment by eatyourpeas** [comment]
fixed with #358
