### ISSUE TITLE
Employer drop-down showing address line 1

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#349]
- [x] When adding a new user via the epilepsy12@rcpch.ac.uk user the employer drop down option only shows the first line of the address of the Trust, rather than the Trust name itself.   epilepsy12@rcpch.ac.uk, 20/03/2023

**Comment by eatyourpeas** [comment]
Can I check I have understood?
The first hospital in the database is 1b St Catherine's, Gorleston. Is that what you are referring to? That is the organisation name, not the address. To add a new user to a given hospital, you first have to select the hospital from clinician access selected hospital view, and select View all ### Staff. For example if you select Addenbrookes here you add a user to Addenbrooke's team:
<img width="569" alt="image" src="https://user-images.githubusercontent.com/1058647/228265305-060a3df7-b509-4dd9-8af3-26f850780788.png">

**Comment by AmaniKrayemRCPCH** [comment]
Hi Simon, 

I think you're correct in that this was a misunderstanding. I've logged into the account which the tester was using (epilepsy12@rcpch.ac.uk) an the employer does say 1b St Catherines, so I think it's just confusion caused by the name. 

I tried to take a look on my account, but that drop down isn't there. 

![Image](https://user-images.githubusercontent.com/126471383/229511446-62bce01d-3822-4266-9669-f43d09e94b56.PNG)

I think it would be useful if I could see the employer field too when adding users so there's no risk of confusion.

**Comment by eatyourpeas** [comment]
The presence/absence of the drop down is determined by the user role/permission. In the image you post the RCPCH audit member box is greyed out as is the RCPCH staff box. You can be a clinician and an RCPCH audit team member, which is why there are 2 toggles. 
You are logged in there as an audit centre lead - most of these people will not be RCPCH audit team members so would not normal be offered a national view.
I am happy to change your permissions?

**Comment by AmaniKrayemRCPCH** [comment]
Thank you for explaining. That makes sense!

It would be ideal if my permissions were changed, so i could set up the new users for testing. Thanks!

**Comment by eatyourpeas** [comment]
You are currently set up as an RCPCH Audit Team member as well as an RCPCH Staff Member (ie not affiliated with a hospital). There are 2 categories as some clinicians (like @coldunk ) are both clinicians and RCPCH Audit Team members. As such you should already have national view permissions. Maybe we could run through permissions at the next meeting to make sure these are correctly implemented.

**Comment by eatyourpeas** [comment]
fixed in #447
