### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#350]
Different behaviours to test.

# Permissions

Test different views according to user permissions

- assert actions DO work depending on permissions
- assert actions DON'T work depending on permissions

**Comment by pacharanero** [comment]
Related Issues - each need to be checked through and closed before the master Testing issue can be closed:

* [x] https://github.com/rcpch/rcpch-audit-engine/issues/435
* [x] test `user_may_view_this_child` and `user_may_view_this_organisation` in `decorators.py` permissions for interacting with models, based on user permissions

**Comment by anchit-chandran** [comment]
Will close on PR

**Comment by pacharanero** [comment]
complete
