### ISSUE TITLE
E12 needs to tolerate failure to contact IMD server

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#352]
At present if the E12 server can't contact the IMD server it will fail with a stacktrace.
We need to ad logic to this which allows for either failure or delay in contacting the IMD server.
Consider either a backoff or async job possibly? Or do we just have a nice message saying you can't save the Registration/Case at this time?
For discussion.

**Comment by eatyourpeas** [comment]
I agree. It tests for a 404, but does not raise an exception for anything else. It does need to fail gracefully.

**Comment by anchit-chandran** [comment]
Has this been done @pacharanero @eatyourpeas ?

**Comment by pacharanero** [comment]
This now fails gracefully so can be closed
