### ISSUE TITLE
Current code commit/version should be linked in topmost nav (left)

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#376]
For ease of administrator/developer debugging, it would be a nice-to-have if the current commit hash of the running version of the software was visible in the top left nav.

* [ ] Should show **short** commit hash of the current version
* [ ] Should only be shown to Admins and Developers
* [ ] Should click through to the commit on Github for quickly viewing the relevant code
* [ ] Version number +/- Git tag +/- Github Release should also be displayed once we have semver established

Sketch of what this would look like

![Image](https://user-images.githubusercontent.com/2348385/231704602-3108b7e8-7705-4874-a149-814e92bfa592.png)

**Comment by anchit-chandran** [comment]
This can be done in 2 potential ways:

## `gitpython` - external dependency

Get the latest commit via:

```
import git

repo = git.Repo(search_parent_directories=True)
commit_hash = repo.head.object.hexsha
```

## `subprocess` 

- found this snippet online, you make a template tag
- it appears on the template, but it couldn't find the repo - possibly needs some bash path exploring

**in `epilepsy12_template_tags.py`** add:
```
@register.simple_tag
def git_ver():
    '''
    Retrieve and return the latest git commit hash ID and tag as a dict.
    '''
 
    git_dir = os.path.dirname(settings.BASE_DIR)
 
    try:
        # Date and hash ID
        head = subprocess.Popen(
            f"git -C {git_dir} log -1 --pretty=format:\"%h on %cd\" --date=short",
            shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        version = head.stdout.readline().strip().decode('utf-8')
 
        # Latest tag
        head = subprocess.Popen(
            f"git -C {git_dir} describe --tags $(git -C {git_dir} rev-list --tags --max-count=1)",
            shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        latest_tag = head.stdout.readline().strip().decode('utf-8')
 
        git_string = f"{version}, {latest_tag}"
    except:
        git_string = u'unknown'
 
    return git_string
```

**Comment by anchit-chandran** [comment]
Currently added just the short hash with GitHub Action (seen in https://epilepsy12-development.azurewebsites.net/organisation):



![Image](https://user-images.githubusercontent.com/68898006/232714864-46b7548b-5f15-48a8-9801-d99500f9508e.png)

(also to note, it takes the most recent commit hash that includes a push to development [&therefore azure])


![Image](https://user-images.githubusercontent.com/68898006/232716412-e579fdb9-a673-456b-85a2-df03225acc38.png)




## Further work

Further work will include the branch also e.g:



![Image](https://user-images.githubusercontent.com/68898006/232714900-7c8e0bda-11c8-4e69-9c02-80458a46ced7.png)


Also need to embed link to commit on GitHub

**Comment by pacharanero** [comment]
Nice. I like the idea it could be used to remind admins which version and branch they are on. With multiple sites (live/staging/dev) it's useful for sense-checking unexpected behaviour - "ohhhhhh - I'm actually on staging not development" etc

I'd suggest could make the format fairly terse, something like:

`branch: development - commit: af6e8bc`

**Comment by anchit-chandran** [comment]
implemented as so:

![Image](https://user-images.githubusercontent.com/68898006/233035613-06a0781d-4d34-4bc6-a00b-62319b9906a1.png)

Will close on PR
