### ISSUE TITLE
Chart.js key/legend has clickable 'disable' feature which is not necessary and possibly confusing

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#377]
![Image](https://user-images.githubusercontent.com/2348385/231707472-16dffa70-77fc-4d8d-828d-1be98d77fc5f.png)

As shown above, the default chart.js label in the legend can be clicked and this disables the data from being shown. In the example I have disabled both 'Male' and 'Female' from the display, which renders a totally ridiculous pie chart.

**Consider disabling this feature in all charts**, unless there is a clear use-case. One such possibly valid use-case is where there is a large cohort with 'None' or null data, which can be removed from the analysis.

**Comment by anchit-chandran** [comment]
Easy change, just add `onClick: null`. Can implement depending on user preferences @AmaniKrayemRCPCH

**Comment by AmaniKrayemRCPCH** [comment]
Thanks both!
We're happy to disable this feature in all charts.
