### ISSUE TITLE
Create users at other sites

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#378]
Which user types can create users at sites other than their own?

Can we allow RCPCH Audit Lead users to add new users to any site.

**Comment by eatyourpeas** [comment]
This feature already exists. Only RCPCH staff can add users at multiple sites though this still needs testing. The hospital is selected from the hospital landing page and from there users can be added/removed/updated or created:
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/1058647/232209496-50c1c388-b282-47bb-a3bc-4e7500bea824.png">
