### ISSUE TITLE
Add "Making edits directly to documentation" explained to E12 docs

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#382]
Added in this button for each page which will directly take you to the current Github page to edit text: 

![Image](https://user-images.githubusercontent.com/68898006/232085679-76ba33fd-bc11-4f7e-83b8-c6a948859dc9.png)

You can manually go to the same place at this [link](https://github.com/rcpch/epilepsy12-documentation/tree/live/docs). These include all the text files (specifically markdown files) where each section's content comes from:

![Image](https://user-images.githubusercontent.com/68898006/232086048-6abd472b-7f9c-43bb-b939-e6f390973c53.png)

## Steps to make request to edit

1. Click on the file you want to edit. You will be able to view the file contents.
1. Click on the 'edit' pencil icon near the top right of the file. It will take you into edit mode.
2. Make any edits you want to (e.g. in the gif below, I changed "centrally-set to centrally set".
3. Scroll to the bottom and select "`Create a new branch for this commit and start a pull request.`". Name this anything e.g. `amani-edits`.
4. Click on "Propose changes". You will be taken to the "Pull Request" screen where you can describe the changes you're requesting to make. Add any further details here (but if it's just wording changes, putting that in the title should be enough!)
5. Finally, click "Create pull request". This will send the request for your changes to be made

**Walkthrough of steps**

![Image](https://user-images.githubusercontent.com/68898006/232091175-73673488-1ef2-4b09-b1f3-454778381330.gif)

**Comment by anchit-chandran** [comment]
@pacharanero @eatyourpeas the above steps describe how Amani can make a PR directly to `live` which I know goes against our standard workflow. Reasoning was:
1. I couldn't see a `development` deployed site?
2. The changes will only be in the markdown files so wouldn't be able to break anything
3. Decreases complexity

Is that fine?

**Comment by eatyourpeas** [comment]
This is a brilliant explainer @anchit-chandran thank you. I think running everything off of live is fine

**Comment by AmaniKrayemRCPCH** [comment]
Amazing! This is really helpful. 

Thank you @anchit-chandran

**Comment by pacharanero** [comment]
Great stuff @anchit-chandran 

I think this Issue explaining how to make edits could be moved into a section in the E12 docs site, aimed at the E12 team/Audit admins? Will leave this issue open and slate that work to be done.

**Comment by anchit-chandran** [comment]
This section can now be found on the site: https://epilepsy12docs.rcpch.tech/admin-users/how-to-edit-docs/

Will close
