### ISSUE TITLE
Can administrators see only their organisation or their whole trust?

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#383]
If logged in as a centre administrator, currently the user sees this screen:
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/1058647/232229343-b8648758-7512-449d-9dfc-2f28fb366a9c.png">

Should they be able to add/edit users across all the organisations in their trust or only their organisation?

**Comment by AmaniKrayemRCPCH** [comment]
I'm not sure we want centre administrators to be able to add/edit users - they should have **view only** permissions. 
I think they should only be able to view their organisation.

These users are normally clinical effectiveness teams, who access the platform to view summary data for their **trust**

What do you think @nikyraja ?

**Comment by nikyraja** [comment]
Yes, I would agree. 

We want centre administrators to be able to view all users in their trust/health board. We only really want the leads to add/edit users across all organisations within the trust. 

Admin users would be clinical audit teams or admin staff within the clinical teams who are assisting with data entry, so we would still want the ownership or who has access to the data etc to be with the trust leads

**Comment by eatyourpeas** [comment]
fixed
