### ISSUE TITLE
Icons in user list should be side by side

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#388]
Currently icons are crowding
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/1058647/232248853-957b0b5a-ab1f-482f-9d4a-f611a8875ad8.png">

**Comment by anchit-chandran** [comment]
will be fixed in PR



![Image](https://user-images.githubusercontent.com/68898006/232747578-771771e9-4a3b-48c2-a0d4-ff25d74c8000.png)
