### ISSUE TITLE
Text in steps should wrap

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#389]
If the text in the steps is too long for the line, the whole line wraps under the tick. The tick icon should occupy the whole space to the left of the text, and the text should wrap if too long to fit on one line
![image](https://user-images.githubusercontent.com/1058647/232248968-d1959622-2093-4629-a66b-2d05232841e0.png)

**Comment by anchit-chandran** [comment]
Fixed using `flex-wrap: nowrap`

Will be in next PR



![Image](https://user-images.githubusercontent.com/68898006/232752146-829a6786-af55-4848-9a8b-cb8ce9f7c366.png)
