### ISSUE TITLE
Errors when no last_logged in (only on first user first log in?)

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#402]
Last logged in fails if user has never logged in

![Image](https://user-images.githubusercontent.com/68898006/232436600-14495e65-f351-475c-8392-8d48721d4360.png)

Will fix myself

**Comment by pacharanero** [comment]
This is fixed in 174acce0317aaa1119ef4f522bacd4b89123aafb, which has added logic to determine if there has been any previous login or not and gives a different user message accordingly.
