### ISSUE TITLE
Edit homepage text

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#405]
Apologies, I don't have permission to write this myself.

https://github.com/rcpch/rcpch-audit-engine/blob/d2d8c755d1d3c6f71ac24e98b9846fdbd16488e8/templates/epilepsy12/epilepsy12index.html

- [x] Line 29 - Can the text be changed to "Epilepsy12 (The National Clinical Audit of Seizures and Epilepsies for Children and Young People) is a national clinical audit established in 2009 and has the continued aim of helping epilepsy services, and those who commission health services, to measure and improve the quality of care for children and young people with seizures and epilepsies."
- [x] Line 44 - Can this image be changed to a graph or data table? 
- [x] Line 47 - Change to 'Epilepsy12 data capture platform'
- [x] Line 50 - Change to 'Access Epilepsy12 audit data for your organisation' 
- [x] Line 64 - Can we remove the Children and families button for now?
- [x] Line 94-95 - Can this be moved below the contact details?

**Comment by anchit-chandran** [comment]
Made all changes except Line 64 -> I think @pacharanero  @eatyourpeas said we might want to use this for public facing reporting? 

![Image](https://user-images.githubusercontent.com/68898006/234585748-bc151607-7f47-455d-b665-e723e0c35b21.png)

**Comment by anchit-chandran** [comment]
@AmaniKrayemRCPCH are you happy for this to be left as the link to the pt-facing dashboard? Will close if so

**Comment by eatyourpeas** [comment]
This was discussed at last E12 project board meeting and has now been implemented. The tile remains and is redirected to the patient-facing KPI page.
