### ISSUE TITLE
Change bar chart and pie chart colours

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#406]
Love the bar charts!

I just wanted to provide the colours from the March update to the brand guidance. Could we use the college colours in the graphs?

![Image](https://user-images.githubusercontent.com/126471383/232489188-3ce574d4-54df-4523-ad71-bfceb0703eca.PNG)
![Image](https://user-images.githubusercontent.com/126471383/232489189-5b6b5d15-8346-4d78-a497-fb3f42126989.PNG)
![Image](https://user-images.githubusercontent.com/126471383/232489190-167ad227-0d01-4b86-8514-1fa61b8da0fb.PNG)
![Image](https://user-images.githubusercontent.com/126471383/232489191-d6a48bde-eb4c-41b0-9979-fcfd8e629695.PNG)

**Comment by AmaniKrayemRCPCH** [comment]
Here's all the colours and hex codes in one image

![Image](https://user-images.githubusercontent.com/126471383/232494994-1665713d-5424-4579-b6fe-40f1aa00d7c3.PNG)

**Comment by anchit-chandran** [comment]
@AmaniKrayemRCPCH is there a link to this doc?

**Comment by anchit-chandran** [comment]
Also I think @eatyourpeas has already fixed this - these colours are from RCPCH branding?





![Image](https://user-images.githubusercontent.com/68898006/232780289-013d65e9-bbea-43e7-8f61-36cfba0e733f.png)






![Image](https://user-images.githubusercontent.com/68898006/232778591-8465eca8-ee8b-44f8-a3e2-3e7de1f169b8.png)




![Image](https://user-images.githubusercontent.com/68898006/232778638-223b2358-8db6-4bf7-b753-536ee2210bd1.png)

**Comment by AmaniKrayemRCPCH** [comment]
Hi Anchit, 
Here you go! Sorry it wouldn't let me attach pdf files to the original issue.

[RCPCH Brand Guide.pdf](https://github.com/rcpch/rcpch-audit-engine/files/11271830/RCPCH.Brand.Guide.pdf)

**Comment by anchit-chandran** [comment]
A couple of the colours have changed slightly - cross-check with new ones provided by Amani

**Comment by pacharanero** [comment]
Closed at F2F E12 meeting 3.5.2023 - team satisfied with colour choices.
