### ISSUE TITLE
Bar charts shrinking away upon legend click

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#408]
On microsoft Edge, the bar chart shrinks once the legend is clicked. Sometimes, the charts are automatically shrinking and the legend click will actually stop the shrinking. 

This doesn't happen on Chrome. 

See video here, I couldn't attach it to the issue - https://1drv.ms/v/s!Ar1l8xUlmvoMhBKbqZ44rgsxNU-V?e=hhzxT4 
Apologies for the poor video quality.

**Comment by anchit-chandran** [comment]
Thanks for finding - easiest fix is to disable ability to deselect legend items. Is that fine or would you still like to deselect? Can think of a better solution if so

**Comment by AmaniKrayemRCPCH** [comment]
I think we're ok to disable the legend click.

**Comment by anchit-chandran** [comment]
Cool, I think @eatyourpeas might have actually already fixed the weird shrinking even with disabling legend, but it will be disabled  regardless in our next updates
