### ISSUE TITLE
Remove 'Number achieving measure' from individual kpi legend -> move to x label

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#412]
# Current

 the 'number achieving measure' legend label doesn't make sense as a legend label

![Image](https://user-images.githubusercontent.com/68898006/232757252-0def43e4-b823-47e3-8b46-9f668ddd60f2.png)

# Proposed change

Move to x-axis title

![Image](https://user-images.githubusercontent.com/68898006/232756684-2b7e846a-d6a9-49fd-820f-3bc7750f6ba6.png)

@eatyourpeas if you're happy with this, will add in next PR

**Comment by eatyourpeas** [comment]
That looks great. @AmaniKrayemRCPCH has said she would like it changed to 'percentage of children achieving this measure'. We then then need to change the aggregation from a SUM to a percentage, and the average line would have to be the average of this.

**Comment by anchit-chandran** [comment]
Think I've gotten the pct e.g. Eastern Paediatric Epilepsy Network's avg is 11.11%  (`1 / 9`), which I calculated in the E12 template tags: 

![Image](https://user-images.githubusercontent.com/68898006/233047993-554fb50a-f44e-4ce0-8a66-4e7069ddd6b5.png)



```python
@register.simple_tag
def kpi_for_kpi_name(aggregated_kpi, kpi_name):
    if aggregated_kpi['aggregated_kpis'][kpi_name] is None:
        return 0
    else:
        pct = 100*aggregated_kpi['aggregated_kpis'][kpi_name] / aggregated_kpi['aggregated_kpis']['total_number_of_cases']
        return pct
```

Using this data by doing `paediatrician_with_expertise_in_epilepsies /total_number_of_cases ` :

```{
'region': ('EPEN', 'Eastern Paediatric Epilepsy Network'), 
'aggregated_kpis': {
        'paediatrician_with_expertise_in_epilepsies': 1, 
        'paediatrician_with_expertise_in_epilepsies_average': 0.1111111111111111,
        'total_number_of_cases': 9
    }
}
```

However, I'm a bit more stumped calculating the average, as unsure how your aggregations here work in Line 142 onwards from `aggregate_by.py`:

```python
if kpi_measure:
        # a single measure selected for aggregation

        q_objects = Q(
            **{f'registration__kpi__{kpi_measure}__lt': 2}
        ) & Q(
            **{f'registration__kpi__{kpi_measure}__isnull': False}
        ) & Q(**{f'registration__kpi__{kpi_measure}__isnull': False})
        f_objects = F(f'registration__kpi__{kpi_measure}')

        # sum this measure
        aggregation_fields[f'{kpi_measure}'] = Sum(
            DJANGO_CASE(When(q_objects,
                        then=f_objects), default=None)
        )
        # average of the sum of this measure
        aggregation_fields[f'{kpi_measure}_average'] = Avg(
            DJANGO_CASE(When(q_objects,
                        then=f_objects), default=None))
        # total cases scored for this measure
        aggregation_fields['total_number_of_cases'] = Count(
            DJANGO_CASE(When(q_objects,
                        then=f_objects), default=None))
    else:
```

**Comment by anchit-chandran** [comment]
Implemented avg line as so: 

![image](https://user-images.githubusercontent.com/68898006/233616624-f82d0859-8278-4372-8702-7f1110118c5c.png)

@nikyraja this is how the avg looks:

**NOTE**: average calculated only from eligible cases/regions, excluding `Region: None`

**Comment by anchit-chandran** [comment]
Will close once PR'd as converted counts to pct, however still have sizing issue detailed in #419
