### ISSUE TITLE
New questions to multiaxial diagnosis

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#417]
The project board have agreed on 3 new questions

1. "Does the child have documented global developmental delay/learning disability/intellectual disability?"
Answer options: Yes, No.
      a. If above question is answered yes, "Is this mild, moderate, severe, profound, or uncertain?"
      Answer options: Mild, Moderate, Severe, Profound, Uncertain
2. "Does the child have a diagnosis of autistic spectrum disorder?"
Answer options: Yes, No.

These questions need to be mandatory. Can this be in the multiaxial diagnosis section, under the relative impairment subheading?

@coldunk @nikyraja 

Are we happy with the wording?

Do we therefore want to remove LD, GDD, ID, and autism from the comorbidities question?

**Comment by nikyraja** [comment]
How about:

'Has a global developmental delay (under 5 years) or learning disability/intellectual disability (over 5 years) been identified?'
Answer options: Yes, No.
a. If above question is answered yes, "Add details on the severity of the neurodevelopmental condition'
Answer options: Mild, Moderate, Severe, Profound, Uncertain

'Has there been a diagnosis of autistic spectrum disorder?'
Answer options: Yes, No.

Agree we should then remove these from the general comorbidities list to avoid duplication. We should also do this for the MH conditions. 

Would it make sense to place 'Are there any relevant impairment, behavioural, educational or emotional problems?' after the questions on MH and LD then? (maybe a separate issue?) 

Happy to discuss other views!

**Comment by eatyourpeas** [comment]
closed with #453
