### ISSUE TITLE
ChartJS individual KPI charts sizing bug

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#419]
The initial vertical sizing for ICBs is too small, causing ICB labels to cut off and bars appearing odd:

![Image](https://user-images.githubusercontent.com/68898006/233617271-4c017bbb-5721-45a9-b673-57dd660aec29.png)

Changing the selected KPI measure, causing the rendered charts to update, causes height to (seemingly randomly) increase to fit all labels, but is unusable long (screenshot very zoomed out to fit entire chart in):

![Image](https://user-images.githubusercontent.com/68898006/233617421-182c0faa-92ca-4c18-8153-2b01f5199ea3.png)

# Expected behaviour

- Will play with chart container to fix responsive sizing. @eatyourpeas looping you in to confirm if you've set any CSS chart sizing yourself?

**Comment by eatyourpeas** [comment]
this is now fixed
