### ISSUE TITLE
Select organisation dropdown needs different query info

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#423]
Currently, the new query means the organisation name pulled through doesn't have all the info / exact type of info we need. For example, for this 'Child Development Centres':

![Image](https://user-images.githubusercontent.com/68898006/233970448-28d6ade9-d24e-4812-ac83-d9c9066d51ed.png)

**Comment by pacharanero** [comment]
Needs to include either more address details or more Trust details so that one can tell which of many 'CHILD DEVELOPMENT CENTRE's are being selected (in this example)

for example

"CHILD DEVELOPMENT CENTRE, WEST SUFFOLK NHS FOUNDATION TRUST"

**Comment by eatyourpeas** [comment]
fixed in #439
