### ISSUE TITLE
Password resend email formatting needs fixing

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#428]
No image showing:

![image](https://user-images.githubusercontent.com/68898006/234525949-bc48c10c-8d40-40e1-b161-7ab82a8e3175.png)

**Comment by eatyourpeas** [comment]
The whole create user work flow has changed actually @AmaniKrayemRCPCH we can show you on Wednesday. there are now 2 buttons, where  depending on your role and permissions, it is possible to create different types of user. My guess is that this will fix your issue. This overcomes the confusion that all those with edit authority can allocate all roles. From now on, no rcpch staff will be allocated to an organisation, but all clinicians will be. Some (rare) clinicians will still be allowed national access however through the is_rcpch_team_member toggle.
![image](https://user-images.githubusercontent.com/1058647/235171404-9edc5011-f1b0-4d05-b775-7659340d4e4a.png)
