### ISSUE TITLE
NHS Trust or Health Board vs hospital site

### ISSUE THREAD

**Issue by hstac** [rcpch/rcpch-audit-engine#43]
Key affiliation is at NHS Trust or Health Board level, rather than hospital

![image](https://user-images.githubusercontent.com/94547588/178023081-65d37261-22d0-4bcb-b078-840edebc1b35.png)

**Comment by eatyourpeas** [comment]
The list of hospitals is comprehensive. This list of fields is:
`{
        "OrganisationID": "39921",
        "OrganisationCode": "R1ARG",
        "OrganisationType": "Hospital",
        "SubType": "Hospital",
        "Sector": "NHS Sector",
        "OrganisationStatus": "Visible",
        "IsPimsManaged": "True",
        "OrganisationName": "Malvern Community Hospital",
        "Address1": "Malvern Community Hospital",
        "Address2": "185 Worcester Road",
        "Address3": "",
        "City": "Malvern",
        "County": "Worcestershire",
        "Postcode": "WR14 1EX",
        "Latitude": "52.123851776123047",
        "Longitude": "-2.3228452205657959",
        "ParentODSCode": "R1A",
        "ParentName": "Herefordshire and Worcestershire Health and Care NHS Trust",
        "Phone": "01684 612600",
        "Email": "",
        "Website": "https://www.hacw.nhs.uk/malvern-community-hospital",
        "Fax": ""
    },`
1. Would you like to filter out all Independent Sector and include only NHS Sector? This would still include community as well as acute hospital trust
2. Shall I then use the ParentName, rather than OrganisationName?

**Comment by pacharanero** [comment]
This has been amended to display the Trust not the hospital
