### ISSUE TITLE
RCPCH Staff user sign up workflow

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#431]
For RCPCH staff user sign ups - the select organisation box should disappear if 'RCPCH Staff' is selected like this:

![Image](https://user-images.githubusercontent.com/68898006/234548241-1d9462e1-2b21-42a4-841c-48516c7db9ae.png)

**Comment by eatyourpeas** [comment]
#439 partially fixes this. Now new RCPCH users are not associated with an organisation. This needs only some hyperscript show/hide logic to toggle the drop down
