### ISSUE TITLE
bug - Inactive user after logging in the first time

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#444]
I logged in with my new account and viewed my user permissions -  i didn't have the pink tick indicating I'm an active user and I was unable to edit a patient's record. I was met with an error saying I didn't have permission to edit a patient's record. 

I logged out and then logged back in, the pink tick appeared, and I could enter data.

**Comment by eatyourpeas** [comment]
fixed with #447
