### ISSUE TITLE
Graphs - Differentiating between 0% and No data

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#445]
There needs to be a way to differentiate between 0% and no data on the graphs. In the example below, Eastern Paediatric Epilepsy Network actually has an average of 0% whereas the rest of the networks have no data entered. 

Maybe we can put the percentage on the bar?

![Image](https://user-images.githubusercontent.com/126471383/235109539-09193ce6-29e4-45d6-a370-c4594581f430.PNG)

**Comment by anchit-chandran** [comment]
Update to this:



![Image](https://user-images.githubusercontent.com/68898006/235647236-6d6533e6-5794-4cba-880f-9610860ae1d8.png)



@AmaniKrayemRCPCH to confirm, did you want the average line to consider regions with `No data`? Currently, it only considers the eligible cases (i.e. bars which are NOT '`No data`').

I thought the current avg line makes more sense as if you look at the national view in this example, blue line is average considering everything, pink line is current implementation which only considers eligible areas:




![Image](https://user-images.githubusercontent.com/68898006/235648197-67163806-03fe-485b-b8a6-312ce0599646.png)

- It looks like England is overperforming compared to the rest, but in reality, it's underperforming compared to eligible areas (in this case, only competition is Wales)

**Comment by anchit-chandran** [comment]
Will close on PR, can discuss avg tomorrow

**Comment by pacharanero** [comment]
Closed at F2F E12 meeting 3.5.2023 - team satisfied with current approach.
