### ISSUE TITLE
New user not creating - no error message associated

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#446]
Here's a screen recording from me trying to create a new user. 
It doesn't progress and has no error message. We didn't receive any emails at epilepsy12@rcpch.ac.uk. 

This was done on my account. 

https://user-images.githubusercontent.com/126471383/235167672-fc242740-9b45-4f78-9d32-ba15fe49cdc9.mp4

**Comment by anchit-chandran** [comment]
What's the url of this website? (checking which version it is)

**Comment by AmaniKrayemRCPCH** [comment]
Thanks Anchit - It's https://epilepsy12.rcpch.tech/

**Comment by anchit-chandran** [comment]
I've made you a superuser - are you able to add people now?

**Comment by AmaniKrayemRCPCH** [comment]
Yes! Thank you!

**Comment by eatyourpeas** [comment]
fixed with #447
