### ISSUE TITLE
Passsword reset email renders as plain text

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#448]
When I was made a superuser, I couldn't log in - it said details were invalid. Fixed upon password reset. Password reset email rendered as plain text. 

If it's relevant, our emails are scanned by VIPRE email security. The other emails ive received from the platform formatted correctly. 

![Image](https://user-images.githubusercontent.com/126471383/235179731-93684fdf-bf5d-40b7-b6a7-3a1a10805b6d.PNG)

**Comment by eatyourpeas** [comment]
now fixed with #447
