### ISSUE TITLE
Registration form

### ISSUE THREAD

**Issue by hstac** [rcpch/rcpch-audit-engine#45]
![image](https://user-images.githubusercontent.com/94547588/178023475-016f434e-26e1-40c9-9368-60b78217c3bd.png)

**Comment by eatyourpeas** [comment]
- [x] eligibility criteria for registration
- [x] home postcode (at time of registration)
- [ ]  review ethnicity choice list (?use snomed)
- [ ] Add CHI number and validation
- [x] Rename to Children's Epilepsy Surgery Service
- [x] fix hospital lookup
- [x] move hospital selections to section 4

**Comment by eatyourpeas** [comment]
@hstac The registration date is a date field to allow the user retrospectively to register. Could you let me know if you would prefer them not to have that freedom? Instead it could could be replaced with a date/time stamp at time of form submission.

**Comment by hstac** [comment]
I'd replace it with a system date/time stamp. We'd want users to be able to enter EEG and first assessment dates retrospectively; but the date patients enter the audit isn't one we calculate from

**Comment by eatyourpeas** [comment]
This entire page has now but rebuilt. The unchecked items remain so leaving this for the moment

**Comment by eatyourpeas** [comment]
many of these issues are now fixed. I will close here now but open new items for chi/nhs number validation and considering different ethnicity selection choices.
