### ISSUE TITLE
Add DRF-Spectacular

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#456]
It is part of the RCPCH-Incubator handbook that we use open-api and swagger for documenting our endpoints
We have used DRF spectacular in the rcpch census platform so should add the same for E12. As part of this, the documentation for implementers needs updating.

- [x] add DRF spectacular as a dependency
- [x] add DRF spectacular decorators to views and urls
- [x] update documentation

**Comment by anchit-chandran** [comment]
- [x] update urls according to APIM base url
