### ISSUE TITLE
Adding an audit eligibility / verification stage

### ISSUE THREAD

**Issue by hstac** [rcpch/rcpch-audit-engine#46]
![image](https://user-images.githubusercontent.com/94547588/178023712-0aeeda01-ad78-41e2-a0a9-0d4f122efa97.png)

**Comment by eatyourpeas** [comment]
thanks @hstac reading these through they do not make much sense and actually, searching all the Epilepsy12 documentation online (excluding @coldunk 's videos) nowhere is there a comprehensive list of inclusion and exclusion criteria. They are phrased as questions but criteria are statements so should be along the lines of:

The following criteria must <b>all</b> be fulfilled before registering for Epilepsy12
- Child is an NHS patient
- Child has had 2 or more documented seizures >24 hours apart
- Child has not participated in Epilepsy12 before
- Child/Parents have NOT requested an opt out (deets...)

If you wanted, these could be rendered as check boxes, which once all checked could allow the user to progress.

The registration form as it stands is a gateway to audit completion - the steps cannot be completed until a start date has been defined and a cohort etc allocated. This means the registration form is also a good place to ensure eligibility criteria are met, maybe register the hospitals involved in the child's care, before allowing the user to proceed further. If you prefer, though, very happy to move them instead to section 4.

If possible could you point me to a reference of all the inclusion/exclusion criteria please?

**Comment by eatyourpeas** [comment]
Discussion with @hstac and @coldunk 
Registration to be refactored to Validation.
Registration refers to the entering of a child's details into the audit database (allocating a lead centre at the same time)
Validation refers to the process of confirming eligibility, assigning as start date and allocating to a cohort.

**Comment by coldunk** [comment]
Just checked.  First phase is registration. Can second be verification? I said validation yesterday but verification is term to be consistent with.

**Comment by eatyourpeas** [comment]
This now closed some time back
