### ISSUE TITLE
Public facing kpi charts

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#462]
# Initial implementation
- Any denominators / numerators less than 3, mask as asterisk
- essentially take real-time KPI metrics and put on a public-facing landing page
- need to think about DDOS protection / server use 
- aggregation for data calculated e.g. once a day a 9am and cached - filtering per organisation on this pre-calculated table would then be the only per-user computation
- implementation would allow Trusts to know the quarterly reports before they are refreshed
- Once cohort deadline is passed, the case will be locked

**Comment by eatyourpeas** [comment]
This largely implemented now.
Outstanding work
- [ ] mask fields with < 3 as asterisks
- [ ] persist query results for 24 hours and serve from storage
- [ ] cron job to run query every 24hrs and update storage (see redis/celery branch with initial implementation)

locking cases after one year will be moved into a separate issue
