### ISSUE TITLE
In the drug list, for the `Other` option, remove "`(None)`" from the label

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#463]
Remove this:

![Image](https://user-images.githubusercontent.com/68898006/236438929-470ed6b2-2491-44d6-baf8-a242da04a2d5.png)

**Comment by anchit-chandran** [comment]
@eatyourpeas I've been annoyingly stuck on this for a while.

## (Situation/Background) Reason for bug

The stuff inside parentheses is coming from `MedicineEntity.preferredTerm`. 



![Image](https://user-images.githubusercontent.com/68898006/236439976-c88f5381-0331-4ae6-b673-7545d6d798ca.png)

which is fed into the re-usable `select_model.html` here:





![Image](https://user-images.githubusercontent.com/68898006/236441321-d5e3dcd9-de9e-436e-bc9c-fa4b71003318.png)





  On Line 68, the `field_name2` is `preferredTerm`. The following template tag `value_for_field_name` evaluates to `None` (I assume because where `MedicineEntity.medicineName == 'Other'`, then its `.preferredTerm` is `None`.



![Image](https://user-images.githubusercontent.com/68898006/236440480-75e24fe0-5826-458f-ae88-98d2840afab7.png)



![Image](https://user-images.githubusercontent.com/68898006/236442169-465928ec-b73e-478f-9789-47925ae136c8.png)

This causes `Other (None)` to appear in the selections



## (Assessment) What I've tried and why it doesn't work

1. Changing the custom template tag / select_model.html

- this won't work as they're used in multiple places and might break something

2. Changing template tag to check if `value_for_field_name == None` 

-  this won't work because the Jinja template system can't work with an if condition AND a custom template tag that takes 2 arguments

## (Reccomendation) I'm stuck

Unsure how else to deal with this / don't understand the full scope of how the `select_model.html` dropdown works - and whether editing it would break something elsewhere

**Comment by pacharanero** [comment]
Not sure I can add much here, I was surprised that the code inside `if field_name2` runs when field_name2 is returning `None`, because in Python `None` is a Falsy constant, according to what I've read.

But I can't really add anything to help at this stage

**Comment by anchit-chandran** [comment]
> Not sure I can add much here, I was surprised that the code inside `if field_name2` runs when field_name2 is returning `None`, because in Python `None` is a Falsy constant, according to what I've read.
> 
> But I can't really add anything to help at this stage

currently, `if field_name2` just checks if you want to add the second field_name. In this case, we give it `preferredTerm`, so it is always True (soit's NOT checking the *value* of `MedicineEntity.preferredTerm`, only whether a `field_name2` is provided, which it always is)

**Comment by eatyourpeas** [comment]
I have pushed a fix for this. You are right there was a false conditional test here - it should have been testing the value or field_name2, not the presence of the key.

The fix I have applied is to change the template tag to accept a new param and also test for None in the value, not the key:

```
@register.simple_tag
def value_for_field_name(model, field_name, in_parentheses):
    """
    Returns the field value for a given field name in a model
    If in_parentheses is true, return the value in parentheses.
    """
    return_val = getattr(model, field_name, None)
    if in_parentheses:
        return_string = f"({return_val})"
    else:
        return_string = f"{return_val}"

    if return_val is not None:
        return return_string
    return ""
```
