### ISSUE TITLE
Change KPI chart colors to be uniform per abstraction (e.g. openUK = blue, national = red)

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#465]

**Comment by anchit-chandran** [comment]
@AmaniKrayemRCPCH the arbitrary color order i've chosen for each abstraction is:

```python
        'open_uk_color' : colors.RCPCH_RED_LIGHT_TINT1,
        'icb_color' : colors.RCPCH_ORANGE_LIGHT_TINT1,
        'nhs_region_color' : colors.RCPCH_YELLOW_LIGHT_TINT1,
        'country_color' : colors.RCPCH_STRONG_GREEN_LIGHT_TINT1,
```

which looks like below. Let me know if any change needed:



![Image](https://user-images.githubusercontent.com/68898006/236186572-00c15a0c-f412-4ea1-8cc9-5207c36d6114.png)

**Comment by eatyourpeas** [comment]
I think that looks great @anchit-chandran - as we start to add historical data we just change the tint - darker or lighter, whatever you think appropriate. Is there a way of changing the code subtly to use the cohort in someway to change the tint? 
Otherwise, do send a PR and I will merge.

**Comment by anchit-chandran** [comment]
one implementation of this could be changing this colors constant file into a module where you ask for a color name - assuming we have enough tints per cohort, we can then programmatically do e.g.:

![image](https://user-images.githubusercontent.com/68898006/237049979-c0072afa-466f-493e-84cd-d707e24790ba.png)



```python
COHORT = 6
Colors.get_color(f"RCPCH_LIGHT_BLUE_TINT_{COHORT}")
```

Will require adjusting the color names +/- liaising with E12 as to exactly which tints, so perhaps for a future roadmap?
