### ISSUE TITLE
Add NICE guidance re investigation requesting post-diagnosis into tooltip

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#468]
@AmaniKrayemRCPCH to pls provide preferred text

![Image](https://user-images.githubusercontent.com/68898006/235895342-3ac446c1-6bdf-413f-978e-506cad1c028f.png)

**Comment by AmaniKrayemRCPCH** [comment]
Question | Tooltip
--- | ---
Has a first EEG been requested? | If a diagnosis of epilepsy is suspected, a routine EEG should be carried out to support the diagnosis. CYP undergoing initial investigations for epilepsy should have tests within 4 weeks of being requested.

We're happy with the existing tooltips for CT and MRI.

**Comment by anchit-chandran** [comment]
Updated. will close on PR
