### ISSUE TITLE
For Investigations ordering section - add button 'Could not be performed' but requested

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#469]
# Discussion
- For EEG ordering, add a series of encodings (with particular dates) for reasons EEG not performed
- Have a 'scheduled date' and a 'has been achieved' state + 'uncooperative' state

@AmaniKrayemRCPCH pls confirm what is wanted

**Comment by eatyourpeas** [comment]
I think it was left:
- [x] no dates can be in the future
- [x] for EEG and MRI, performed date nolonger a mandatory field.
- [x] for EEG and MRI add a button 'Unable to perform' (@AmaniKrayemRCPCH to suggest appropriate wording). On press this hides the performed date and persists a dummy date (15/4/1915 is the date of birth of Jean Henri Gestaut).
- [x] conditional logic to allow dummy date to be stored and excluded from mri wait and eeg wait calculations
- [x] Note if performed date not filled for legitimate reasons, still fail the measure
- [x] Add explanation to reference_help_text in model for both performed dates

**Comment by eatyourpeas** [comment]
closed with #475
