### ISSUE TITLE
Graph colours

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#482]
Colours for the bar charts

•	OPEN UK: Aqua #00BDAA
•	Country: Dark blue #0D0D58
•	NHSE region: Bright blue #11A7F2
•	ICB: Strong Blue #3366CC

We've kept to the blues but happy for you to edit this and give some suggested colours if it looks odd

**Comment by anchit-chandran** [comment]
@AmaniKrayemRCPCH i re-did ordering so it fits with increasing size, but used those same colors:



![Image](https://user-images.githubusercontent.com/68898006/237048281-49b64fb8-a9e8-4791-b675-25217ca1b1aa.png)

Will close on PR

**Comment by AmaniKrayemRCPCH** [comment]
Looks great! the dark blue graph might need white text on the data labels?

**Comment by pacharanero** [comment]
> white text on the data labels?

@anchit-chandran could the data be moved to outside the coloured bar to fix this?

**Comment by anchit-chandran** [comment]
Cant move outside the bars as positioning is broken when bars are at 100% with the plugin we're using.

Instead, used black color for light bars and white for dark bars: 

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/68898006/96a058a2-b1ac-4f27-b219-fc8c7412c6cb)

Will close issue on PR.
