### ISSUE TITLE
Cannot enter first paediatric assessment date

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#484]
I get an error with no text, and cannot progress through the form. This error occurs with multiple patient records. 

https://user-images.githubusercontent.com/126471383/237134458-908b6d57-6a0a-4735-ae70-eb3e83987d2f.mp4

**Comment by eatyourpeas** [comment]
That is probably my fault - sorry. In the process of fixing all the date field thresholds I may have forgotten that one.
