### ISSUE TITLE
"# _id = models.ObjectIdField()" commented out in case.py - can it be removed

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#488]
```
    # _id = models.ObjectIdField() #TODO
```

https://github.com/rcpch/rcpch-audit-engine/blob/b3cd222ce9899705f9897d77b8ab7b00acdcbb48/epilepsy12/models_folder/case.py#L35

**Comment by eatyourpeas** [comment]
fixed in next PR
