### ISSUE TITLE
Epilepsy type select boxes broken

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#493]
When selecting `Epileptic` for seizure type, it automatically also selects `Non-epileptic`, and doesn't allow you to unselect either.

It works when selecting any of the other options.

![Image](https://user-images.githubusercontent.com/68898006/239877387-258a585b-3bc7-4697-b1fa-ec347da1a23b.png)

**Comment by eatyourpeas** [comment]
fixed by #494
