### ISSUE TITLE
Milestones section of audit form, when changing pre-filled Q1 'Consultant Paediatrician referral' from yes to no leads to `ValueError`

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#496]
Found bug in Milestones when clicking through audit form of seeded children.

**steps to recreate**: If `Has a referral been made to a consultant paediatrician with expertise in epilepsies?` is Yes, with dates filled in for the seeded child:
![image](https://github.com/rcpch/rcpch-audit-engine/assets/68898006/8984ca59-3f22-4136-acbc-bb06ed1f6143)

- when you click No, the field stops responding to further clicks
- then, when clicking off Milestones section and back, leads to the following error:
- 
![image](https://github.com/rcpch/rcpch-audit-engine/assets/68898006/75cbe59c-6367-42e0-b167-d5c4b0d41be5)

**Comment by eatyourpeas** [comment]
now fixed with next update
