### ISSUE TITLE
Date validation

### ISSUE THREAD

**Issue by FridahC** [rcpch/rcpch-audit-engine#498]
I have attached a document of the suggested date validations

[Dates validation.docx](https://github.com/rcpch/rcpch-audit-engine/files/11562721/Dates.validation.docx)

**Comment by anchit-chandran** [comment]
@eatyourpeas have you implemented these already?

**Comment by eatyourpeas** [comment]
closed with [c3ade85](https://github.com/rcpch/rcpch-audit-engine/commit/c3ade852f881e961b627d95e8a4e131809ead0c0)
