### ISSUE TITLE
Data download for users

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#501]
Can we add a feature for trust leads to download their trust's data?

**Comment by eatyourpeas** [comment]
I think the devil is in the detail here. What are they downloading?
I would be inclined to leave this as a future feature and wait for users to feedback what they would want that they can't get from the platform already built.

**Comment by AmaniKrayemRCPCH** [comment]
This is a feature in the current platform. Patients can download any individual form and we also provide a key for interpreting downloads. 

Users don't typically use it for the E12 audit itself but for other tasks requiring the same data. 
- Internal audit and QI. 
- Some users also use our platform as a database of patients and want to be able to search by certain traits (e.g. view all patients who are on levetiracetam). 
- They may want to run analyses that we don't do within our reporting (e.g. find median EEG wait time)
- They may want to list patients who have not met certain requirements, which aren't in the performance summary (e.g. list of patients who have not had a CT)

Not necessarily something within the remit of our work but users do find it useful at the moment. If there's other tools that may meet these needs, then we're open to them of course!

**Comment by eatyourpeas** [comment]
This is all doable @AmaniKrayemRCPCH but feels like something for phase 2? @pacharanero and I chatted about this and worried about governance of downloading actual patient data - it feels to me this is straying away from being an audit to being an actual clinical tool.

**Comment by eatyourpeas** [comment]
Closing this for now, but could be reopened in future.
