### ISSUE TITLE
store drugs twice

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#508]
It is currently possible to store a drug more than once. This should only be possible if there is a start and an end date.

**Comment by anchit-chandran** [comment]
Similar issue with `Syndrome` & `Comorbidity`. Perhaps need to filter out select options inside the view, depending on which has already been selected:

## Syndrome


![Image](https://github.com/rcpch/rcpch-audit-engine/assets/68898006/eae6c90f-8e6a-4604-871e-97afa7abd1e4)



## Comorbidity



![Image](https://github.com/rcpch/rcpch-audit-engine/assets/68898006/fdaad441-5335-41f1-94cd-108be7257a59)

**Comment by eatyourpeas** [comment]
closed with #520
