### ISSUE TITLE
Add medications drop down

### ISSUE THREAD

**Issue by hstac** [rcpch/rcpch-audit-engine#51]
So that names of different anti-epilepsy medications recorded, same way as the rescue meds are (no notes/dates needed)

**Comment by hstac** [comment]
And where 'Sodium Valproate' is chosen we need to ask an additional question about PREVENT if patient is female

**Comment by hstac** [comment]
e.g. Is there a pregnancy prevention programme (PPP) in place?

**Comment by hstac** [comment]
Acetazolamide; ACTH; Carbamazepine;  Clobazam;  Clonazepam; Eslicarbazepine acetate; Ethosuximide;Gabapentin; Lacosamide; Lamotrigine; Levetiracetam;  Methylprednisolone; Nitrazepam;  Oxcarbazepine; Perampanel; Piracetam;  Phenobarbital; Phenytoin; Pregabalin; Prednisolone;  Primidone;  Rufinamide;  Sodium valproate; Stiripentol; Sulthiame; Tiagabine;  Topiramate;  Vigabatrin; Zonisamide; Epidyolex® ; Other Cannabis-based medicinal product; Other

**Comment by eatyourpeas** [comment]
partially fixed with [8601650](https://github.com/rcpch/rcpch-audit-engine/commit/8601650c975c62892ea02aa99f4a875e16fdfb0f)

Currently these drugs are not used, rather SNOMED is used
