### ISSUE TITLE
unregistering a child in Epilepsy12 is currently not implemented

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#512]
https://github.com/rcpch/rcpch-audit-engine/blob/927134287e779089939e1ed7fed929131b940eee/epilepsy12/constants/user_types.py#L105

**Comment by eatyourpeas** [comment]
This is a question aimed at the E12 team. It is currently possible for a clinician or RCPCH audit team member to register a child in the audit - that is confirm eligibility as one of the 3 required steps. This is a one way button at the moment - once eligibility is confirmed, it allows the lead centre to be allocated (is usually allocated on creation of a new case), and the date of first paediatric assessment is set. 
If we allow an RCPCH audit team member the authority to remove eligibility, the child may then have data scored in the audit that cannot be included. Do you want to be able to reverse the eligibility step?

**Comment by AmaniKrayemRCPCH** [comment]
Heya, 
I don't think this feature is necessary, as users/RCPCH staff can just delete a child from the audit if they aren't eligible.

**Comment by anchit-chandran** [comment]
Closing as feature not required
