### ISSUE TITLE
Transfer/Edit/Delete lead centre

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#513]
It is currently possible to edit the existing lead centre (without sending emails), as well as transfer, and even delete the current lead centre. At the moment only RCPCH staff have this power. Should it be possible for them to do this?

**Comment by AmaniKrayemRCPCH** [comment]
Hello!
The lead at each site and RCPCH staff should be able to edit, transfer, and delete the lead centre. 

On the current platform, when a child is transferred to another centre, the lead clinician at the receiving site has to 'accept' the transfer. Is it possible to implement this?

All they have to do is acknowledge the transfer before they can edit the audit form.

**Comment by pacharanero** [comment]
> when a child is transferred to another centre, the lead clinician at the receiving site has to 'accept' the transfer. Is it possible to implement this?

There does need to be some kind of Transfer Child workflow, at some future point, but not imminently.
Possibly this could be managed using a new `transfer_child` Model? This would link the Case/Registration, Old site, New site, and could contain flags for `transfer_initiated` and `transfer_accepted`.

For now the E12 team will transfer the children manually by editing the Case/Registration.

* [x] remove Transfer button protemps
