### ISSUE TITLE
Opt out

### ISSUE THREAD

**Issue by hstac** [rcpch/rcpch-audit-engine#52]
Opt out question should be edittable at any stage of data entry. Answer of yes should prevent any further information being added/the case being shown in analyses/downloads. Needs to be removed from the database (with record of system case ID left to track numbers of opt out), deletion on some kind of delay to give small window to retrieve in case opt out applied in error.

**Comment by eatyourpeas** [comment]
Opt out icon added in place of lock icon to case list. Setting opt out to true prevents further editing of record. Still need to add a cron job which deletes the data after 24 hours
