### ISSUE TITLE
Maps don't render if no organisation longitude/latitude

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#523]
Need to add some graceful fail if no organisation longitude/latitude coordinates supplied

**Comment by pacharanero** [comment]
All organisations now have a Lat/Long so this should not happen any more. The application doesn't error, it just fails to render. At some future point this needs to be fixed.

For now we could switch off the maps using a feature flag?

**Comment by dc2007git** [comment]
If all orgs have longitude and latitude then will close this issue. @pacharanero do you want to make a more specific issue to the error you've mentioned above?

**Comment by eatyourpeas** [comment]
The maps actually need a rethink and there are other issues which relate to this so closing this.
