### ISSUE TITLE
E12 Login Security Recommendations resulting from E12 Privacy Impact Assessment

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#526]
In discussion with the team that is formulating the PIA for E12 some architectural and security recommendations were suggested:

* **Data in the DB should be encrypted at rest.** This would require the application to be passed in a decryption key at runtime, but the DB data would all be encrypted. Our exposure should a breach occur is reduced, not to zero, because the _running_ application could be compromised which would have decrypted data in it, but certainly if a pure DB extraction was made it would be impossible to extract any private data from it.

* **There should be a minimum password length of 8 characters.** 

* **Two factor authentication** would be a further desirable step to add to reduce risk of compromise. This could use SMS or a 2FA authenticator app. It potentially adds a degree of difficulty for users, but it is an effective and widely-used mechanism to reduce unauthorised login and makes "brute-force" or password guessing attacks infeasible.

**Comment by eatyourpeas** [comment]
This is of course fine and I have found 2 good libraries on PyPi that might encrypt aspects of database as well as 2FA.

My question is what implications will that have for the E12 team who may want access to the Postgres instance for adhoc analysis? If all the info is encrypted/decrypted through the app, we would have to run all custom queries through that or potentially from the shell?

**Comment by pacharanero** [comment]
It would mean that direct DB access would be out of the question really. And TBH I am not sure direct DB access is a great idea for staff unless they are actually developers as well. It's just too risky, there are IG worries etc

**Comment by eatyourpeas** [comment]
I am generally very supportive of this view. It may be though that the dev team will come under pressure in future to pull out data and run bespoke queries at the request of the E12 team. Could we perhaps use the API for this instead? We could have a series of endpoints for anticipated queries that the E12 team would run. They would largely be GET requests and if the scoping issue were addressed (see #531) could give them access to tables direct from excel or similar.

**Comment by pacharanero** [comment]
Linked to #166

**Comment by anchit-chandran** [comment]
Password and 2fa implemented. Db encryption is in a separate issue so will close this one.
