### ISSUE TITLE
Scheduling KPI Calculation

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#529]
We have had lots of discussion on select queries and aggregation queries being run every time the organisation view is loaded.

This is inefficient and also if the same logic is applied to the public facing site, means that live reporting is available to the world. 

As a first step therefore, a new model was created (KPIAggregation) which holds the results of any aggregations, and this in turn is used to pull results into reports. It is the first step in allowing a scheduling process to run the queries.

To do this though we could either use Cron, or go for some other scheduler - my preference is for Celery, though this will require a new container to run Beat alongside.

**Comment by pacharanero** [comment]
@eatyourpeas @anchit-chandran I believe this KPI calculation is now scheduled and is handled in Celery?
I think it was closed by #617

**Comment by eatyourpeas** [comment]
This is now handled by celery.
