### ISSUE TITLE
cookie handling for GDPR

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#530]
[GDPR](https://gdpr.eu/cookies/) means that we need some messaging around the way cookies are handled. There are libraries to do this on PyPi
[django-cookie-consent](https://pypi.org/project/django-cookie-consent/) looks well-maintained, but there are others.
If anyone has any views/preferences about this do please put them here.

**Comment by pacharanero** [comment]
We need to ascertain if GDPR consent is required for a simple session cookie ONLY. @nikyraja going to chat to Adele and ask.

**Comment by nikyraja** [comment]
Adele has responded with the following info:

"If they are not essential cookies, we will need a cookie banner. There are certain GDPR requirements around consent and cookies and the information you need to provide. For the website one, we asked our website provider to undertake an audit and update it to be compliant with GDPR. Essentially we need to inform individuals why we are using them, what we are collecting and give them a clear option to opt in or out (accept or decline) non essential cookies."

So, if they are essential cookies then we don't need to implement this?

**Comment by pacharanero** [comment]
I would agree that these are essential to the functioning of the site and are the absolute bare minimum to allow a user to log in. So according to our advice from Adele this means that we do not need a Cookie Consent banner.
