### ISSUE TITLE
Patient facing dashboard - quarterly updates

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#532]
The patient dashboard should refresh on specific dates - @nikyraja

**Comment by pacharanero** [comment]
On the last day of the month each quarter the dashboard should be updated.
(Starting at 30th Sept)

**Comment by eatyourpeas** [comment]
Sprint discussion with E12 team - would rather not have an automatic public publication funcction for the moment, rather would have a button to publish all data only visible to E12 team (see #639 )

**Comment by eatyourpeas** [comment]
implemented in #640
