### ISSUE TITLE
Dashboard to identify which trusts have submitted no data

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#533]
E12 need to show which trusts are not participating in the audit.

**Comment by anchit-chandran** [comment]
i believe only requirement is to specify whether "No data" on the KPI charts refers to audits incomplete or no eligible patients ?



![Image](https://github.com/rcpch/rcpch-audit-engine/assets/68898006/6eb6db1d-a139-413b-9f24-aeb1d37988a6)

**Comment by anchit-chandran** [comment]
This has been implemented using our new KPIAggregation data structure as so. Still some work to do re changing our data model to incorporate welsh regions, so will close issue on PR of that



![Image](https://github.com/rcpch/rcpch-audit-engine/assets/68898006/1914781d-6241-426e-a295-6dbcaca626df)
