### ISSUE TITLE
Browser resizing - Staff and Cohort view

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#535]
heya, 

the patient and staff lists don't resize correctly when viewing on a smaller screen. They're ok on the big screen. 
For reference, the screenshots are from my laptop screen 1920x1080, 150% scale (i know it's weird. it's what the IT team sets it to). 

![Image](https://user-images.githubusercontent.com/126471383/257867120-493de6df-9804-40f7-a604-061751fe26dd.PNG)
![Image](https://user-images.githubusercontent.com/126471383/257867119-eb6d1ce0-933c-4d4a-922c-87e7581b2b7c.PNG)

**Comment by anchit-chandran** [comment]
might be a silly question but can you zoom out? Can try `Ctrl`+mouswheel down?

**Comment by AmaniKrayemRCPCH** [comment]
Yep. It's fine when zoomed out. 

If i zoom in >100% on the laptop screen, it resizes weirdly. It resizes better on the big screen.
