### ISSUE TITLE
Audit Centre Clinician has option to add new users

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#536]
Heya, 

I've created a clinician and admin user to get screenshots for the guidance, and noticed that the Audit Centre Clinician has the option to add new users. This doesn't align with the permissions stated in the administrator guide. 

![Image](https://user-images.githubusercontent.com/126471383/258078451-4e5b60a1-2c6b-4e3c-8b80-ab67253b95dd.PNG)

**Comment by AmaniKrayemRCPCH** [comment]
I am also able to transfer patients while logged in as a clinician user.

**Comment by anchit-chandran** [comment]
This is odd. Re adding users as an Audit Centre Clinician, I can't on the latest version (that I have on my computer). Checked to see if live/staging sites were very behind development but doesn't seem like it?

In any case, on the next PR it looks like this:

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/68898006/c83f2498-fe7d-4a43-9916-74928bf0c776)

@eatyourpeas it seems odd as the only difference between live/staging and dev is that dev has api-related commits, but none for the client? 

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/68898006/78db7291-dd78-4a78-8fd3-2d4d71f913b6)

**Comment by AmaniKrayemRCPCH** [comment]
Here's a screen-recording. I can also see the RCPCH user toggle. 
I can also see the RCPCH toggle when logged in as a lead clinician

https://github.com/rcpch/rcpch-audit-engine/assets/126471383/c27d9f9a-80d4-4a9b-98bf-2988f49ff51e

**Comment by anchit-chandran** [comment]
Should be fixed in next PR
