### ISSUE TITLE
all postcodes flagged as invalid

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#537]
Making new patients to create screenshots, and the postcode field is invalid regardless of what I enter. 

The below postcode is valid, as it's my postcode. I've also tried other postcodes from a random generator, with and without spaces, with and without uppercase letters. 

![Image](https://user-images.githubusercontent.com/126471383/258142024-83616f1c-f86e-4b68-b770-5094c581a8cc.PNG)

**Comment by anchit-chandran** [comment]
Hi i came across this just now whilst updating kpi's too! I've fixed it for the next PR

**Comment by eatyourpeas** [comment]
Thanks @AmaniKrayemRCPCH for finding this
