### ISSUE TITLE
Patient transfer notification emails

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#538]
I tested out a patient transfer to see if the permissions were correct for clinician users (see [issue #536](https://github.com/rcpch/rcpch-audit-engine/issues/536)) and a notification email appeared to have been sent to everyone, including staff not allocated to the site. 

The email also contains the patient's name. We'd much prefer an anonymous ID of some sort, as we can't guarantee that the recipient's email is secure to handle patient identifiable info. Plus, if RCPCH staff receive the email, we can't handle patient info in our servers. 

![Image](https://user-images.githubusercontent.com/126471383/258144947-78b24d26-6f84-49dc-8adf-bf4e18e1df24.PNG)

**Comment by AmaniKrayemRCPCH** [comment]
email was also sent to nnap@rcpch.ac.uk, and this account wasn't 'active' at the time.

**Comment by eatyourpeas** [comment]
Thanks for testing this functionality.
We have not fully discussed the workflow of this yet, so I was not clear how you wanted this to work.
Currently emails are sent to the lead clinician of the accepting trust if they exist and all E12 team. Perhaps, rather than an identifier, it should simply say 'Dr X from Organisation Y has transferred a young person to your team. Please contact Dr X for further details...'

Do please advise on appropriate text and recipients.

**Comment by pacharanero** [comment]
* [x] transfer buttin is going to be removed see #513 
* [x] remove patient's name from the transfer email anyway
* [x] transfer emails should go to E12 team email address epilepsy12@rcpch.ac.uk

**Comment by AmaniKrayemRCPCH** [comment]
Has this been actioned?

**Comment by eatyourpeas** [comment]
Yes this has been actioned

**Comment by nikyraja** [comment]
A patient was transferred between organisations and the project team were included in the email. 

Only the clinicians should receive these transfer emails. If there is no clinician registered to the receiving organisation, the email can go to [epilepsy12@rcpch.ac.uk](mailto:epilepsy12@rcpch.ac.uk). No transfer emails need to be going to personal emails. 

@eatyourpeas @pacharanero

**Comment by eatyourpeas** [comment]
Apologies - in the last fix all RCPCH audit team members were included in the transfer request emails. These have been removed in pull request #726 which should close this issue.
In addition I have made some small extra changes

**Comment by nikyraja** [comment]
Great, thank you Simon!
