### ISSUE TITLE
ESN

### ISSUE THREAD

**Issue by hstac** [rcpch/rcpch-audit-engine#54]
no where to record Epilepsy Specialist Nurse input (plus date of first input) - required for performance indicator

**Comment by pacharanero** [comment]
Are these things that are in the Netsolving version which we've missed?

**Comment by eatyourpeas** [comment]
fixed with [8601650](https://github.com/rcpch/rcpch-audit-engine/commit/8601650c975c62892ea02aa99f4a875e16fdfb0f)
