### ISSUE TITLE
Lead Clinician can't unlock a locked record

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#541]
Logged in as lead clinician (epilepsy12@rcpch.ac.uk) and I couldn't unlock a submitted patient record. All users should be able to un-submit records. 

the tooltip also runs off the page. 

https://user-images.githubusercontent.com/126471383/258155220-5d6ffd89-d2b1-4189-b77b-9a5a98f0506a.mp4

**Comment by eatyourpeas** [comment]
That permission is currently only allocated to the E12 team. I thought these had been agreed already?
I think what may have happened here is that the list [here](https://epilepsy12.rcpch.tech/docs) in the administrator guide is that the small handful of custom permissions have not been included. Perhaps we could agree these at sprint?

**Comment by anchit-chandran** [comment]
Link to table: https://epilepsy12docs.rcpch.tech/admin-users/admin-user-guide/#user-permissions

**Comment by eatyourpeas** [comment]
This relates to #544

**Comment by eatyourpeas** [comment]
closed with #640
