### ISSUE TITLE
Refactoring boundary model <-> entity model

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#548]
When introducing SHAPE files, boundary models + entity models have lots of overlap.

Steps for refactor:

1. Combine boundary model and entity models
2. Separate NHS Regions  field foreign keys into 2:
	1. NHS Regions (for english organisations)
	2. Local Health Boards (welsh organisations)

**Comment by eatyourpeas** [comment]
this is now done in the local-health-boards branch and can be closed once merged

**Comment by anchit-chandran** [comment]
will close on pr
