### ISSUE TITLE
School/ individual health care plan

### ISSUE THREAD

**Issue by hstac** [rcpch/rcpch-audit-engine#55]
No where to record if a school individual care plan in place. Used in performance indicator.

**Comment by hstac** [comment]
Is there evidence of a School Individual Healthcare plan (IHP) or EHCP in place?

**Comment by eatyourpeas** [comment]
fixed with [8601650](https://github.com/rcpch/rcpch-audit-engine/commit/8601650c975c62892ea02aa99f4a875e16fdfb0f)
