### ISSUE TITLE
Endpoint to get all users

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#551]
E12 sprint today.
It would be helpful at golive to have a GET endpoint to pull down a list of all users to be able to send group emails

**Comment by anchit-chandran** [comment]
I've implemented this as a simple button and view that downloads a csv with the following headers (can update columns according to what @nikyraja @AmaniKrayemRCPCH need).

Also added tests confirming only RCPCH_AUDIT_TEAM_MEMBERS ( group name is `EPILEPSY12_AUDIT_TEAM_FULL_ACCESS` ) can access it, everyone else gets a 403. The button is only visible to RCPCH_staff / superusers.



![Image](https://github.com/rcpch/rcpch-audit-engine/assets/68898006/30f4fac7-81e5-4489-a8a8-22ca68aba302)



![Image](https://github.com/rcpch/rcpch-audit-engine/assets/68898006/94f2e6bb-3259-4e39-a658-cb148e7bdbd7)

**Comment by anchit-chandran** [comment]
@AmaniKrayemRCPCH this is the issue for getting all users
