### ISSUE TITLE
New POST/PUT endpoint for migrating existing cohort data

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#552]
In October prior to golive data needs to be migrated from the existing platform into the new E12.
Suggested work flow
- [ ] initial data dump to be stored securely independently
- [ ] E12 separately to refactor the data / clean for testing purposes
- [ ] Create new POST/PUT endpoint to create new cases against organisations in secure development environment
- [ ] Write unit test to check data successfully migrated
- [ ] Run unit test against data dump to ensure successful migration of data
- [ ] RCPCH independently to do spot checks using their own cleaned dataset.

**Comment by anchit-chandran** [comment]
@AmaniKrayemRCPCH @nikyraja are there any further details for this?

**Comment by nikyraja** [comment]
Agree with the above!

**Comment by pacharanero** [comment]
This POST/PUT endpoint REST API approcah has been superseded by a simpler CSV importer approach as detailed in #596 
Closing.
