### ISSUE TITLE
Renaming user groups

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#555]
Hi!

We wanted to rename the user groups to get rid of the term 'audit centre', as it's a bit ambiguous. 

Suggested changes are below. I'm not sure if this affects much, apart from the documentation, but I thought I'd let you know. I'm currently drafting edits to the documentation and I can reflect these changes in there. 

Group|Current Name|New Name
---|---|---
trust_audit_team_view_only|Audit Centre Lead Clinician|Lead Clinician
trust_audit_team_edit_access|Audit Centre Clinician|Clinician
trust_audit_team_full_access|Audit Centre Administrator|Administrator

**Comment by eatyourpeas** [comment]
This is now fixed in the local-health-boards branch
<img width="550" alt="image" src="https://github.com/rcpch/rcpch-audit-engine/assets/1058647/459d4857-5016-4f20-afa7-08018e40beb1">
