### ISSUE TITLE
Lead Clinician can add RCPCH user

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#557]
Lead clinician user has the option to make an RCPCH audit team member
I couldn't remember if this has already been resolved, but I couldn't find an issue on it. 

![Image](https://user-images.githubusercontent.com/126471383/264362312-96c91992-6ffa-4ac9-a1cb-58ff0ee95a6d.PNG)

**Comment by AmaniKrayemRCPCH** [comment]
Additionally, I can't seem to delete other users while logged in as a lead user.

**Comment by AmaniKrayemRCPCH** [comment]
If this hasn't already been fixed, can we label it as before-launch.

**Comment by eatyourpeas** [comment]
This was the main vulnerability rightly identified in the pen test report and has now been fixed in the local-health-boards branch. Lead clinicians can delete users in their own trust. We can close this when it has merged.

**Comment by anchit-chandran** [comment]
Will close on PR - fixed by @eatyourpeas

**Comment by eatyourpeas** [comment]
fixed with [d625196](https://github.com/rcpch/rcpch-audit-engine/commit/d625196a3945cc92916b2fc55969fcfa2afc543c)
