### ISSUE TITLE
Homepage edits

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#563]
![Image](https://user-images.githubusercontent.com/126471383/264975005-8c192680-a7db-4dea-b2c8-47e2d428ab38.png)

- [x] Change background to [strongblue-to-lightblue.jpg](https://user-images.githubusercontent.com/126471383/264975154-4e14369e-5176-48a5-8735-488810cb1e64.jpg) (this is a gradient of #3366cc to #11A7F2 at 45 degrees)
- [x] Change the logo to [EP12_ID_MONO_WHITE_Digital_full_Screen.png](https://user-images.githubusercontent.com/126471383/264975292-a1e608c1-c6ee-4e48-9cee-78c852246f33.png)
- [x] Change the header to:

National Clinical Audit of Seizures and Epilepsies for Children and Young People <br> Data Capture Platform
|---|

- [x] Remove the subheading
- [x] Change the introduction to:

**Welcome to the Epilepsy12 data capture platform**

Epilepsy12 is a national clinical audit established in 2009 and has the continued aim of helping epilepsy services, and those who commission health services, to measure and improve the quality of care for children and young people with seizures and epilepsies.
Epilepsy12 is delivered by the Royal College of Paediatrics and Child Health (RCPCH), and Round 4 is underway. The RCPCH mission is to transform child health through knowledge, innovation and expertise.

By accessing, browsing, entering data or otherwise accessing the Site, you become a ‘user’ and assert that you have read and understand and agree to be bound by [the terms of Agreement](https://epilepsy12.rcpch.tech/docs). If you have any questions about this Disclaimer, please contact us. 

- [x] Change the about-us text to:

Epilepsy12 is commissioned by the Healthcare Quality Improvement Partnership (HQIP), as part of the National Clinical Audit and Patient Outcomes Programme (NCAPOP), and is funded by NHS England and the Welsh Government. Round 4 contract is underway and is being delivered by the Royal College of Paediatrics and Child Health (RCPCH) from 1 April 2022 to 31 March 2025. 

- [x] Change the children and families button to the image below, and link to https://www.rcpch.ac.uk/work-we-do/clinical-audits/epilepsy12

![Image](https://user-images.githubusercontent.com/126471383/264977250-d08f94fb-0010-4350-91f1-e36426ba1d08.png)

**Comment by anchit-chandran** [comment]
thanks will sort this!

**Comment by anchit-chandran** [comment]
updates made . will close on pr

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/68898006/e24b38f4-ffd7-4dd0-9a44-50ddfcb9c048)
