### ISSUE TITLE
Mental health issue question should be multiple choice

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#567]
The final question in the Multiaxial diagnosis category. 
Users should be able to select multiple mental health problems. At the moment, they can only select one. 

Please flag as before launch. 

![Image](https://user-images.githubusercontent.com/126471383/266648560-cd510f38-78d4-4808-8675-edd7ef85c110.PNG)

**Comment by eatyourpeas** [comment]
![image](https://github.com/rcpch/rcpch-audit-engine/assets/1058647/895ed206-6f38-4781-8ce1-e38d027f51c9)
This is fixed in the health-boards branch
