### ISSUE TITLE
Class-based Views

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#58]
In an effort to ensure we are using idiomatic Django, we will start to convert the Views to Class-based
https://docs.djangoproject.com/en/4.0/topics/class-based-views/intro/

* [ ] assessment_views.py
* [ ] case_views.py
* [ ] comorbidity_views.py
* [ ] docs_views.py
* [ ] epilepsy_context_views.py
* [ ] hospital_trust_autocomplete.py
* [ ] initial_assessment_views.py
* [ ] investigation_management_views.py
* [ ] multiaxial_description_views.py

**Comment by eatyourpeas** [comment]
I think this idea is maybe deprecated now. We have function based views which affords us granular control and the ability (using HTMX) save form elements in real time without requiring form submission, but has come at the expense of a lot of boiler plate. If you agree @pacharanero we can close this issue.

**Comment by eatyourpeas** [comment]
closing this
