### ISSUE TITLE
Merging the docs site into this repo

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#586]
Merging the Mkdocs folder into this repo will have multiple benefits:
- less cognitive load for starting up the docs site concurrently with e12 local dev work
- increased likelihood of keeping docs updated with new features, due to reduced friction
- nicer local dev env

The steps to achieve this will be as follows:

- [x] 1. Dockerize the Mkdocs site, whilst still keeping the option to start it up via `pyenv` or `venv`
- [x] 2. Add docker build container step in `docker-compose.local-dev.yml` just for mkdocs site - this means during local development, no extra steps are required to get the docs site running
- [x] 3. Update GitHub actions workflow to deploy the mkdocs folder only to Azure
- [x] 4. Update docs on how to edit docs site

**Comment by pacharanero** [comment]
Definitely agree this will be beneficial and will reduce friction to keep docs up to date. Happy to help implement. Will defer any new changes to the e12 docs site until the docs are in the main repo now.

**Comment by pacharanero** [comment]
this is now completed apart from a little bit of fiddling to mount the docs site at a URL within the E12 application

**Comment by pacharanero** [comment]
Docs site is now served from Caddy, within the same server as the rest of the application, so there is no need for Azure static website to deploy the docs. The Azure resource `rcpch-epilepsy12-documentation` has now been deleted as no longer needed.
