### ISSUE TITLE
Updates to DESSCRIBE from CD

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#593]
Apologies I couldn't find the original issues. We've got feedback from Colin and I've listed the actions below. 
Here's the notes from Colin for reference - [Data Dictionary 5.0 cd.docx](https://github.com/rcpch/rcpch-audit-engine/files/12848010/Data.Dictionary.5.0.cd.docx)

- [x] Seizure Type - Focal Onset Motor Manifestations - Add `Automatisms `and `Focal to bilateral tonic-clonic`
- [x] Seizure Type - Focal Onset Non-motor Manifestations - Remove `Automatisms`
- [x] Seizure Type - Focal Onset - Rename `EEG findings` to `Localisation`
- [x] Causes - Remove duplicates from the list of epilepsy causes
- [x] Comorbidities - Only keep the following items: `Attention deficit hyperactivity disorder (MBD - Minimal brain disorder)`, `Cerebral palsy (Cerebral palsy)`, `Conductive hearing loss (Conductive deafness)`, `DCD - developmental coordination disorder (Developmental dyspraxia)`, `Developmental language disorder (Developmental language disorder)`, `Developmental speech disorder (Developmental speech disorder, NOS)`, `Disorder of fluency (Disorder of fluency)`, `Dyscalculia (Dyscalculia)`, `Dysgraphia (Dysgraphia)`, `Dyslexia (Specific reading difficulty)`, `Hereditary spastic paraplegia (Strumpell disease)`, `Hydrocephalus (Hydrocephalus)`, `Migraine (Migraine)`, `Moderate binocular visual impairment (Moderate visual impairment, binocular)`, `Movement disorder (Movement disorder)`, `Oppositional defiant disorder (Oppositional defiant disorder)`, `Sensorineural hearing loss (Perceptive deafness, NOS)`, `Sleep disorder (Sleep disorder, NOS)`, `Speech and language developmental delay (Speech and language developmental delay)`, `Tic disorder (Habit disorder)`

**Comment by eatyourpeas** [comment]
Just to say I have updated this a little following conversation with @coldunk - the nonmotor section retains impaired awareness but does not include the request 'aware'
