### ISSUE TITLE
Some E12 images don’t load properly

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#598]
@dc2007git I saw an error from the loading of `epilepsy12-logo-1.png` which was to do with relative paths which have changed since the move of the doc repo into the main E12 repo.

Are there any other broken images?

**Comment by dc2007git** [comment]
> @dc2007git I saw an error from the loading of `epilepsy12-logo-1.png` which was to do with relative paths which have changed since the move of the doc repo into the main E12 repo.
> 
> Are there any other broken images?

@pacharanero it looks like on the live website there are 4 still broken, and the same for the post-documentation-combine-tidying branch too. Have put a screenshot below.

![image](https://github.com/rcpch/rcpch-audit-engine/assets/65614251/080ffa10-2478-4b6f-ab09-52f4ed79cfad)

**Comment by pacharanero** [comment]
These are images which are white with a transparent background, being shown on a white page.
The actual image links to the files are working, it's just they don't show very well. 
TBH we don't really need to actually have a menu of the available images, they just need to be linked somewhere so that people can find them
