### ISSUE TITLE
Multiaxial diagnosis

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#601]
confidence in reported date of episode. Currently the date of the episode is mandatory, yet the confidence in the date includes 'not known'. Does that mean that in circumstances when 'not known' is selected, the episode date can be blank?

Question to @nikyraja and @coldunk

**Comment by nikyraja** [comment]
Yes that is correct. Sometimes they won't know the date of the seizure, so in this case they currently select 'not known' and then don't input a date. If they know the exact or approximate date, they can then enter this in the date field. 

Two options:
Can we make the date field mandatory if 'approximate' or 'exact' date in known. If 'not known' is selected, the date field doesn't appear/is greyed out etc. 

OR, we force them to put in an approximate date, if the exact is not known. We would then remove the 'not known' option. 

@eatyourpeas is there a preference for the system/data model?
@coldunk is there a preference clinically?

**Comment by nikyraja** [comment]
Update - can we please go with option two:

Remove the 'not known' option and force an approximate date, if the exact is not known.

**Comment by eatyourpeas** [comment]
Clarification: to update tooltip to reflect if date not known, user must still enter an approximate date (eg 1st of the month)

**Comment by eatyourpeas** [comment]
Just thinking about this - if the date is still a mandatory field, might it be better to leave just the 2 options? Exact/Approximate and drop the unknown? Happy otherwise to update a tooltip to reflect that this is a mandatory field

**Comment by coldunk** [comment]
Sometimes is so unknowable that some will stress about approximating.  Then they start digging for dates, requesting noteS etc.  I just want them to be able to move on quick. ColinOn 19 Nov 2023, at 14:41, Simon Chapman ***@***.***> wrote:﻿
Just thinking about this - if the date is still a mandatory field, might it be better to leave just the 2 options? Exact/Approximate and drop the unknown? Happy otherwise to update a tooltip to reflect that this is a mandatory field

**Comment by nikyraja** [comment]
Can see your point Simon and it may be something to reflect on with user feedback, but for now lets still with the current exact, approximate and unknown options, but force a date either way and update the tool tip accordingly.
