### ISSUE TITLE
Spacing and layout of buttons in User View and Organisation View is irregular and cluttered

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#606]
Looking at these buttons I feel as though we need more symmetry, alignment, and regular sizing
A challenge to be addressed is that the text for buttons may change according to the Organisation Name
However not every button needs to NAME the Organisation

User View
![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/2d6ea2ea-0e3c-44ce-b4b6-7c92efa7d023)

Organisation View
![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/3327e442-ee56-429a-be6a-bf07e8a1e5cf)

**Comment by dc2007git** [comment]
Resolved with #622
