### ISSUE TITLE
Page widths vary between several of the main views

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#607]
It would be nice to have all the main pages of a similar width and general layout so the changes between pages is more smooth feeling.

Se examples below. 

We could consider the use of a sidebar on the left to reduce the extremely long page length of the Organisation Summary

Organisation View
![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/4f0c738f-5561-45c1-9565-21a7a9c8036c)

Cohort View
![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/4b1d140e-be57-4bb8-8212-c7c8d07b0418)

Home Page
![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/0264919e-a8ea-4734-b9c6-c3dbe470f653)

Settings
![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/b4703dd3-8d09-4939-b14f-df51cc11c604)

**Comment by eatyourpeas** [comment]
@dc2007git is this fixed ?

**Comment by anchit-chandran** [comment]
@dc2007git i believe this should be done in PR we'll merge tomorrow

**Comment by anchit-chandran** [comment]
close as fixed in PR
