### ISSUE TITLE
importing users at launch

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#614]
we will provide a list of leads to import ready for the launch. it will have each user's full name, email, organisation.
we don't have title at the moment but most will be 'dr'

**Comment by nikyraja** [comment]
The list of users and their organisation details has been uploaded to the SP site. **Please wait for our go ahead before importing into the live site.** 

These are all lead accounts and the organisation has been specified.

**Comment by pacharanero** [comment]
OK, acknowledged. We will await go-ahead.

**Comment by pacharanero** [comment]
For the team's info the list of users includes 215 users and the field names are

Title | First Name | Surname | Email | Role | Trust | Organisation | Organisation ODS Code

We will need to build an importer tool I think

@nikyraja this will be prioritised but it is development work and will take time. Alternative is manual creation of users. Ideally we would have had a dummy user data set to prepare with.

**Comment by nikyraja** [comment]
Hi @pacharanero 

Will it be doable to create an importer in this timeframe? Apologies we were not aware that you would need dummy data. 

Manual entry can be an option - we can weigh the time manual entry will take us against how long building the importer will take for you? I am around tomorrow to discuss this more if needed.

**Comment by pacharanero** [comment]
We are working on an importer today and it's quite possible it will be ready in the timeframe.

**Comment by pacharanero** [comment]
This is now completed and users are imported on Live
