### ISSUE TITLE
email 'spammyness' test

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#615]
are we able to test the emails on https://www.mail-tester.com/ 

We had an issue recently where users on the current platform weren't receiving emails from the platform 
 (via noreply@rcpch.ac.uk) and it was being caught by the Trust spam filters. 

It would be good to ensure this doesn't happen with emails from this platform at launch.

**Comment by pacharanero** [comment]
10/10 on MailTester https://www.mail-tester.com/test-ulrlmjlo4

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/c6e4f04b-7352-4ae6-bc54-01770c995903)

The only thing we could add to improve is a DMARC record:

> You do not have a DMARC record, please add a TXT record to your domain _dmarc.rcpch.ac.uk with the following value:
> v=DMARC1; p=none

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/f04ba0bf-9bbc-45c3-8af9-81914d4b5daa)

@ollyrice would you be able to add the DMARC record (the details are above). It should not interfere with anything else on the TLD.

**Comment by ollyrice** [comment]
I removed this recently for testing another email issue on another platform. Should be re-enabling it shortly.
