### ISSUE TITLE
Templates for the 2fa setup step - footer doesn't go to the bottom

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#618]
I think because the main content's height isn't tall enough, the footer at the bottom has some white space between it and the bottom of the page. 

**Target behaviour**: footer should be at bottom, no whitespace underneath

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/68898006/e6d5a2b9-f121-4db7-8b6c-ec9a5cd86a41)

**Comment by dc2007git** [comment]
Seems like this was an issue on every page as a result of the Footer's padding. PR #622 should fix this, let me know if it doesn't work once it gets merged into development
