### ISSUE TITLE
Too many map cards for London hospitals

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-audit-engine#620]
@eatyourpeas we should only keep 3 map cards. Whichever ones you want, can then leave to Danny to remove the card that's not required?

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/68898006/7bab12ff-5da2-46cf-a90b-70ff2158aefb)

**Comment by dc2007git** [comment]
Sounds good, tag me when you decide @eatyourpeas

**Comment by eatyourpeas** [comment]
I agree looks bad when it rolls over to 4. I would go for losing the national view when we are talking about london as it adds nothing really

**Comment by dc2007git** [comment]
Resolved in #622 with commit 4774abbc7ca91112c179c8c4a9106d9c9adca3d9

**Comment by pacharanero** [comment]
> I would go for losing the national view when we are talking about london as it adds nothing really

Surely London IS England, right? I mean there's London and then a load of empty Northern wasteland? ;-)
No need for a National view
