### ISSUE TITLE
Email addresses are CaSe SeNsItIvE in the login screen!!!!

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#624]
Oops this is a bit of a blooper on our part. The email address is used as the surrogate username in E12.

However, unlike usernames which might well be case sensitive, email addresses should never be case sensitive, this is part of the RFC for them.

Unfortunately, email addresses that are equivalent, but differently cased, are being handled as incorrect
hence: niky.raja@rcpch.ac.uk was regarded as incorrect when the correct email was Niky.Raja@rcpch.ac.uk

Solution: email needs to be stored in lower case only, and sent from the UI in lower case as well.

**Comment by eatyourpeas** [comment]
<img width="519" alt="image" src="https://github.com/rcpch/rcpch-audit-engine/assets/1058647/95f42fd2-58bb-44ad-bd74-ce964e6f29d6">
Emails currently are converted to lower case before persisting in the database. How should we do this differently?

**Comment by pacharanero** [comment]
Ah OK, perhaps I've prematurely jumped to the incorrect diagnosis.
The symptoms are that the niky.raja email address did not work, but the Niky.Raja email address did work.
I thought it might be a problem to do with the way emails are downcased, but from the code above that seems to be handled.
We do need to dig a little further to work out what is happening. Happy to do a pairing session on this.

**Comment by eatyourpeas** [comment]
This is fixed once #626 has merged

**Comment by pacharanero** [comment]
Closed via #626
