### ISSUE TITLE
Add organisation (needs to be done before cohort 6 import)

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#631]
Can we add the following organisations

RAE01 - Bradford Royal Infirmary
COX3P - Manchester Local Care Organisation
RT5CF - City Community Paeds

I couldn't find the long/lat in as many decimal places as you have it for other sites. 

    {
        "OrganisationID": "",
        "OrganisationCode": "RAE01",
        "OrganisationType": "",
        "SubType": "",
        "Sector": "",
        "OrganisationStatus": "",
        "IsPimsManaged": "",
        "OrganisationName": "BRADFORD ROYAL INFIRMARY",
        "Address1": "DUCKWORTH LANE",
        "Address2": "",
        "Address3": "",
        "City": "BRADFORD",
        "County": "WEST YORKSHIRE",
        "Postcode": "BD9 6RH",
        "Latitude": "53.80683265969457",
        "Longitude": "-1.7966404739876927",
        "ParentODSCode": "RAE",
        "ParentName": "BRADFORD TEACHING HOSPITALS NHS FOUNDATION TRUST",
        "Phone": "",
        "Email": "",
        "Website": "",
        "Fax": "",
        "LocalAuthority": "E08000032",
    },
    {
        "OrganisationID": "",
        "OrganisationCode": "COX3P",
        "OrganisationType": "",
        "SubType": "",
        "Sector": "",
        "OrganisationStatus": "",
        "IsPimsManaged": "",
        "OrganisationName": "MANCHESTER LOCAL CARE ORGANISATION",
        "Address1": "5TH FLOOR, BRIDGEWATER HOUSE",
        "Address2": "58-60 WHITWORTH STREET",
        "Address3": "",
        "City": "MANCHESTER",
        "County": "GREATER MANCHESTER",
        "Postcode": "M1 6LT",
        "Latitude": "53.47520",
        "Longitude": "-2.24016",
        "ParentODSCode": "R0A",
        "ParentName": "MANCHESTER UNIVERSITY NHS FOUNDATION TRUST",
        "Phone": "",
        "Email": "",
        "Website": "",
        "Fax": "",
        "LocalAuthority": "E08000003",
    },
    {
        "OrganisationID": "",
        "OrganisationCode": "RT5CF",
        "OrganisationType": "",
        "SubType": "",
        "Sector": "",
        "OrganisationStatus": "",
        "IsPimsManaged": "",
        "OrganisationName": "CITY COMMUNITY PAEDS (EPMA)",
        "Address1": "RIVERSIDE HOUSE",
        "Address2": "BRIDGE PARK PLAZA",
        "Address3": "BRIDGE PARK ROAD",
        "City": "LEICESTER",
        "County": "LEICESTERSHIRE",
        "Postcode": "LE4 8PQ",
        "Latitude": "52.67650",
        "Longitude": "-1.10302",
        "ParentODSCode": "RT5",
        "ParentName": "LEICESTERSHIRE PARTNERSHIP NHS TRUST",
        "Phone": "",
        "Email": "",
        "Website": "",
        "Fax": "",
        "LocalAuthority": "E06000016",
    },

The following can be removed:

    {
        "OrganisationID": "",
        "OrganisationCode": "RR842",
        "OrganisationType": "",
        "SubType": "",
        "Sector": "",
        "OrganisationStatus": "",
        "IsPimsManaged": "",
        "OrganisationName": "BRADFORD ROYAL INFIRMARY",
        "Address1": "CHESNUT HOUSE",
        "Address2": "DUCKWORTH LANE",
        "Address3": "",
        "City": "BRADFORD",
        "County": "WEST YORKSHIRE",
        "Postcode": "BD9 6RJ",
        "Latitude": "53.80683265969457",
        "Longitude": "-1.7966404739876927",
        "ParentODSCode": "RR8",
        "ParentName": "LEEDS TEACHING HOSPITALS NHS TRUST",
        "Phone": "",
        "Email": "",
        "Website": "",
        "Fax": "",
        "LocalAuthority": "E08000032",
    },

**Comment by pacharanero** [comment]
These organisations have been amended as per the data here
