### ISSUE TITLE
Cohort calculation error?

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#641]
Can I check that the cohort calculation is definitely correct? Sorry I know we have previously covered it:
<img width="1044" alt="image" src="https://github.com/rcpch/rcpch-audit-engine/assets/1058647/faf36e76-a615-4426-b539-0be0eae9a0a5">

Here, both children are allocated to cohort 6, but the first has 51 days left from a first paediatric assessment date of 15/12/22,
while the second has 422 days left with a first paediatric assessment date on 17/7/2023. Is it ok they are both still in the same cohort?

**Comment by AmaniKrayemRCPCH** [comment]
Thanks for checking!

They should both have the same deadline. The deadline for Cohort 6 is 14 January 2025. 

Dolly Shepard-0 has been given the Cohort 5 deadline.

**Comment by pacharanero** [comment]
As discussed today this will be looked at by @eatyourpeas and hopefully closed very soon.
