### ISSUE TITLE
Update log-in error image

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#659]
Heya, 

Here's an image you can use for the log-in error screen. I've attached as a png and eps file.

**Comment by AmaniKrayemRCPCH** [comment]
[Illustration_R5_22.zip](https://github.com/rcpch/rcpch-audit-engine/files/13487271/Illustration_R5_22.zip)

**Comment by eatyourpeas** [comment]
That is a lovely picture! Is this ok?

<img width="1195" alt="image" src="https://github.com/rcpch/rcpch-audit-engine/assets/1058647/2d9b30e9-bf52-45b2-a6de-c33ccefcdbad">

**Comment by AmaniKrayemRCPCH** [comment]
Perfect! Thank you!
