### ISSUE TITLE
password reset email - minor edit

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#660]
Heya, 

The password reset email is missing a space before the link, so it's not clickable. 

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/352788bd-7fec-4f81-8880-85f28b553135)

**Comment by nikyraja** [comment]
@eatyourpeas

**Comment by pacharanero** [comment]
@nikyraja this is fixed now. I will pull this change through to Live as well now
