### ISSUE TITLE
UI - fix to the Organisation Card

### ISSUE THREAD

**Issue by dc2007git** [rcpch/rcpch-audit-engine#669]
In the organisation card, if contact information doesn't exist, then we should simply have it not show. So for example, instead of:

<img width="449" alt="image" src="https://github.com/rcpch/rcpch-audit-engine/assets/65614251/aedea086-e16b-459e-834a-1f542c40da39">

We remove the phone number and email slot so it's just the website.

**Comment by pacharanero** [comment]
closed by #741
