### ISSUE TITLE
UI button tidyup

### ISSUE THREAD

**Issue by dc2007git** [rcpch/rcpch-audit-engine#672]
On User creation forms, or any other form submission pages, I think that having a 'save' or 'add' button on the left hand side of the bottom of the page and a cancel button on the far right side of that div would potentially look a bit better.

Also, it might be worth increasing the font-weight of buttons for a smoother UI. Similar to how these buttons look now:

<img width="863" alt="image" src="https://github.com/rcpch/rcpch-audit-engine/assets/65614251/b4c1c4b6-74a6-4b3a-8285-650ca2a97805">

**Comment by anchit-chandran** [comment]
Implemented updated design so closing
