### ISSUE TITLE
Refactor of top nav?

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#673]
Wondered if perhaps we could refactor the two bits of navigation we have in the top nav, into one single top bar?

![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/76435a51-9809-4d07-a420-b36b351b70f7)

* Find somewhere else to display the Admin Data section
* Move the account/Log Out button onto the same line as the below nav

**Comment by mbarton** [comment]
@pacharanero I think this will be covered in more detail in #806 but do re-open if it needs a standalone issue
