### ISSUE TITLE
Bug in Days remaining until latest submission date

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#674]
Currently it is not showing any number of days (it is Dec 1 2023 today, not sure if this is relevant, but the Cohort Number has incremented correctly to 7 today since yesterday.

![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/7b8e109e-079d-418e-a924-8f2157fdeabc)

**Comment by eatyourpeas** [comment]
fixed in #676
