### ISSUE TITLE
Bug in Completed Patient Records

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#675]
As you can see in the screenshot, although there are children loaded into E12 (this is on Dev), the metrics about completed patient records don't look to be accurate.

I have one child registered here:
![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/150c74ba-7803-4c47-a2b8-a1ce64c0168f)

But in the Completed Patient Records metrics there is nothing showing:
![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/a271cb7c-1c21-4c12-a379-35a3418177a4)

**Comment by eatyourpeas** [comment]
I am thinking this may be artefact. I notice from the image you post that the current cohort is 7. So today (as the 1st December) is the first day of that new cohort, and if the children you seeded the database with are from yesterday (30th Nov) or before, they will all be in cohort 6.
Currently the queries that power that label only report total completed cases as a fraction of total registered cases **in the current cohort**. It is on the road map to have a drop down in the UI that allows the user to select different cohorts to drive the reports but this has not been yet been built (although cohort has been added as a param to all the aggregation queries to allow this to be down fairly easily in future). So before we close this we should test it by seeding a fresh database with current new cases and then seeing that the count is correct.

**Comment by eatyourpeas** [comment]
So in follow up to this it seems to be working as expected - see here children seeded in cohort 7. The totals are 0 until 1 is registered. Here, 1 is registered in the current cohort but none are complete. Perhaps the label needs to make this clearer? It is not just completed records we are showing: it is all those with completed records as a fraction of all those registered. 
<img width="1343" alt="image" src="https://github.com/rcpch/rcpch-audit-engine/assets/1058647/91efc0dd-d0fc-4893-a149-677469353d83">
Let me know how you think it would be clearer.

**Comment by eatyourpeas** [comment]
An allied and important issue I have discovered in the context of exploring this is that the async aggregations were not being called on clicking refresh or landing on the page as before. I have sent a separate pull request (#682) that applies a fix.

**Comment by eatyourpeas** [comment]
thanks @anchit-chandran
