### ISSUE TITLE
Bug - when clicking 'add a new child', redirected to the log in page

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#691]
Reported by two users. 

1. "when clicking 'add a new child', I am taken to a log in page (despite being signed in already). However, when I sign in again, I am diverted to the sign in page again. I am therefore unable to add a new child  to the platform as I am repeatedly  prompted to sign in, even when completing all information.  This must be a flaw in the platform."

2. "When I click ‘add a new child/young person’ it won’t let me and I have to relogin and doesn’t then take me past login. Then relogin and generate code. But when put in token code takes me back to this page. So I cannot get to the ‘add a new child/young person section?"

**Comment by AmaniKrayemRCPCH** [comment]
Both users are lead clinicians

**Comment by AmaniKrayemRCPCH** [comment]
Cannot replicate this issue as a lead clinician in staging or live

**Comment by eatyourpeas** [comment]
Hopefully both these issues addressed - please reopen this issue if persists.
