### ISSUE TITLE
Lead clinician cannot add new users

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#692]
Issue reported by user
"when trying to add a new user the blue banner is greyed out and I can not click on it"

The user then asked for their email address to be changed, so I deleted their account and created a new one. I've asked them to confirm if the issue continues with their new account and, if so, to get a screenshot

**Comment by AmaniKrayemRCPCH** [comment]
Another email just came in - ", please could you offer log in access to the included members of our Epilepsy team. I have set my password but was unable to add in members by accessing the staff view"

**Comment by AmaniKrayemRCPCH** [comment]
Cannot replicate this issue as a lead clinician in staging or live

**Comment by AmaniKrayemRCPCH** [comment]
Another user has reported this and provided this screenshot


![Image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/173a1f19-2955-42c1-a091-df8a7223e766)

**Comment by eatyourpeas** [comment]
This was a permissions issue now fixed. Closing this now but please reopen if persists.
