### ISSUE TITLE
User cannot log in - told password/email is incorrect

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#695]
"I’ve tried to set up my access on the new data platform but am experiencing problems. I have successfully changed my password twice, which has been confirmed on screen. When I then try & login it then says my email address & password are incorrect (I know I’m using the correct login details)."

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/4c17b945-21b9-4093-ae9c-2f7bf768d434)

**Comment by AmaniKrayemRCPCH** [comment]
The user's email address has been sent to Simon

**Comment by AmaniKrayemRCPCH** [comment]
Two more users have reported the same thing. All 3 users have capital letters in their email addresses on the platform

**Comment by eatyourpeas** [comment]
Hopefully all these issues have been addressed. Closing this now, but please reopen if not resolved
