### ISSUE TITLE
Header font in the Audit data entry section is not Montserrat

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#698]
In this example the heading text "Record View - Epilepsy ContextBob Dylan 1766577954" is not in the correct font

![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/5247e536-64ba-49da-bfb2-1b5b51b3f47c)

Consider also a slightly larger font size - keeping it in line with other font sizes we use elsewhere in the app

**Comment by eatyourpeas** [comment]
I think RCPCH guidelines are to use Arial in titles/headings and montserrat in text. Agree there needs to be consistency across the application to reflect what we do.

**Comment by anchit-chandran** [comment]
@AmaniKrayemRCPCH what's the E12 verdict re this font design?

**Comment by AmaniKrayemRCPCH** [comment]
Montserrat would be preferable. 
Arial is reserved for when Montserrat can't be used.

**Comment by anchit-chandran** [comment]
But should we use Arial in titles/headings - sounds like that's RCPCH guidelines? Or should have Montserrat everywhere possible

**Comment by AmaniKrayemRCPCH** [comment]
I don't believe so. Here's the RCPCH guidance on fonts - so Montserrat everywhere
![image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/8dc58b0f-9c2e-430d-912c-29cfd8f01258)

**Comment by dc2007git** [comment]
Closing as Montserrat has already been implemented for this title as per #741
