### ISSUE TITLE
Consider emboldening this text in all main questions?

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#699]
Just to make the main questions stand out a little more, I wonder if emboldening the text of (in this example) "Consultant paediatrician with expertise in epilepsies" would be nice?

![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/ee4c4a3f-ed15-4a0e-ad37-ebba2d4522a3)

**Comment by eatyourpeas** [comment]
I agree would look better

**Comment by anchit-chandran** [comment]
will add in tomorrow
