### ISSUE TITLE
There needs to be a standard look up for ethnicities - DM&D

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#7]
```
        # TODO There needs to be a standard look up for ethnicities - DM&D
```

https://github.com/rcpch/rcpch-audit-engine/blob/4cafd1c7bdc158daf59f164c65a5e6317529099e/rcpch-audit-engine/epilepsy12/models.py#L196

**Comment by pacharanero** [comment]
NHS Data Model and Dictionary has standard categories for ethnicities

https://datadictionary.nhs.uk/Covid19PRA/Ethnic_Category.html?hl=ethnicity

**Comment by eatyourpeas** [comment]
The NHS standard for recording this is [here](https://datadictionary.nhs.uk/data_elements/ethnic_category.html)
