### ISSUE TITLE
Consent and Performance Summary - positioning of Patient Name

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#701]
Should be a simple fix but in the questions 8 and 9 of the Audit, the patient's name is marged with the left side text, whereas in all previous screens it is pulled right and separate, and includes the NHS number

### Example

7. Treatment and Care Planning
![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/0da4a731-ca37-4e51-a5a0-03451bccb1d6)

8. Consent (we need to change the heading "consent" probably anyway, see #700)
![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/21ad2f23-681a-4d9c-8224-4c43c3fef500)

9. Performance Summary
![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/7d1f0136-f47e-44ab-b83c-0b155c5da0d7)

**Comment by anchit-chandran** [comment]
@dc2007git is this in #741

**Comment by dc2007git** [comment]
Yes it is will be merged tomorrow
