### ISSUE TITLE
Delayed one time log-in code emails

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#704]
Had two users today report that they've been unable to log in as they haven't received the email with their code. 

"I have been trying to get on to the new platform with no success – I have asked for a password reset twice but with no return e-mail"

"I have followed instruction for the new platform.  Have managed to get account password and log in for myself.  But then stuck in getting onto it -  when it comes to 2 point authentication I asked for email verification and I haven’t received anything.  Not in junk mail either.  Therefore I cannot log into the new and set up my team."

**Comment by eatyourpeas** [comment]
Thanks @AmaniKrayemRCPCH. If you are happy to check first they have a correct email and group/role, then maybe start by deleting the account and create a new one in the standard way. If still no joy perhaps messag separately and we can go through together.

**Comment by anchit-chandran** [comment]
Closing as completed.
