### ISSUE TITLE
cohorts_and_dates() has `first_paediatric_assessment_date` as a parameter but this isn't how it is used

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#705]
I will merge the relevant PR due to time pressure today, but we need to engineer out this kind of slightly confusing parameter.
Where `cohorts_and_dates` is defined the parameter is `first_paediatric_assessment_date`, but then where it is called we are simply sending it `today()`, which does not pertain to a Case/Registration, so `first_paediatric_assessment_date` doesn't have any relevance.

Definition
![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/4c2ea1b7-1db8-4d93-b7ad-f3e90ff97068)

Where it's called
![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/141e80df-1c1f-4b39-9d57-0ae84713c8a4)

**Comment by eatyourpeas** [comment]
I agree it is confusing but it is strictly what it says. The function creates a cohort object with the dates of the two cohorts (submitting and recruiting) should the first paediatric assessment be on the date when the function is called. So in your example, the cohort if a child were registered today would be 6 for submitting and 7 for recruiting. For sure could be named better and I am open to suggestions but that is the reasoning behind it at present.

**Comment by anchit-chandran** [comment]
Agreed with @eatyourpeas - the `cohorts_and_dates` function returns information based specifically on the `first_paediatric_assessment_date`, so arg name is logical.

Where it's called inside the `selected_organisation_summary` view, though it's not specific to a particular Case's `fpa`, we can 'overload' its use to display generic cohort information based on the current date. We're saying "give me the cohort data for a child who has a `fpa` for today". The other place where it's called IS specific for a particular Case. But in both instances, it is always based on the `first_paediatric_assessment_date.`

**Comment by pacharanero** [comment]
OK fair enough let's leave it as it is.
