### ISSUE TITLE
Searching children doesn't work if you're at Trust level

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#707]
If you're looking at the list of kids within a Trust, the search function doesn't work.
If you're looking at the organisation-level or national-level, it does work. 

This was flagged by a user - "At the moment the search function does not work at all? Is this because the platform is not fully functional?"

**Comment by eatyourpeas** [comment]
This is a super helpful pick up @AmaniKrayemRCPCH thank you to your user for identifying. It has identified also that the filter was not working for local health boards in Welsh organisations. I have pushed a fix to a branch of this name and this issue should close automatically once reviewed and merged.

**Comment by pacharanero** [comment]
I've reviewed the PR and now it does appear that the Trust-level search function is working.
