### ISSUE TITLE
Paediatrician referral date error

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#712]
user getting error when paediatrician referral date is before the first paediatric assessment date? 
This date should **not** be limited to after the first paediatric assessment. 

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/3eb8a5e6-153a-441d-a46a-4b34f5e7372a)

**Comment by AmaniKrayemRCPCH** [comment]
This is related to #713

**Comment by eatyourpeas** [comment]
please see reply to #713 - I have fixed this and ESN/EEG dates in the branch associated with that issue.
