### ISSUE TITLE
Date validations

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#713]
This may be something to discuss when @nikyraja is back from AL

A user has raised a case where patients are getting ESN input and EEG referral before first paediatric assessment. In their Trust, the ESN will read referrals prior to assessment and may arrange EEGs or contact the family to provide safety netting information prior to the first paediatric assessment

at the moment, we don't allow professional input or investigation referral dates prior to first assessment, so they are having a lot of trouble with data entry. 

Should we reconsider the date validations?

**Comment by pacharanero** [comment]
Thanks @AmaniKrayemRCPCH 

These edge-cases do seem like a reason to relax the date validation around ESN/EEG etc

**Comment by AmaniKrayemRCPCH** [comment]
I am personally happy to relax it. The validation from cohort 5 and earlier don't restrict to after the first paediatric assessment.

**Comment by eatyourpeas** [comment]
I have relaxed the validation rules for ESN referral date and EEG request date, but left them in place for all the other dates. Changes are in branch #issue716 - if you would like to relax the rules for any other dates, please list which dates you would like changed here and I will push further updates to be reviewed and merged afterwards.
If you are happy with just these 2 changes I would be grateful if you could just say so below this issue.

**Comment by AmaniKrayemRCPCH** [comment]
Looking at last year's data, there's a good number of children who had ESN input before first paediatric assessment, so I would also relax the validation for ESN input.

Otherwise yes, happy with just these changes (and the one in issue #712)

**Comment by nikyraja** [comment]
Thanks all for resolving this! Happy with the above.
