### ISSUE TITLE
Improve logging inside shell

### ISSUE THREAD

**Issue by dc2007git** [rcpch/rcpch-audit-engine#719]

**Comment by anchit-chandran** [comment]
Thanks for opening Danny.

Useful logs are essential for live debugging.

We should fully set up a more comprehensive logging workflow:

1. Logs should be sent to stdout as well as to files, keeping this for ?7 days - whatever is best practice
2. All print statements should be replaced with `logging.{LEVEL}` - there should be no print statements at all
3. This will be a more organic implementation over time as we discover what information is needed when bugs come up, but: all important pathway endpoints e.g. user tries to access a page but doesn't have permission, should provide more verbose output related to that specific user and specific action +/- any state which can be gathered. Essentially, as much info as possible to recreate bugs locally

**Comment by pacharanero** [comment]
closed by #724 thanks @anchit-chandran
