### ISSUE TITLE
Cannot view all local health board staff

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#727]
E.g. Cwm Taf Morgannwg University Health Board
I can view the list of staff in the organisation (e.g. the royal glamorgan hospital), but when I try to view all health board staff, the list is empty.

**Comment by eatyourpeas** [comment]
Thanks for picking this up @AmaniKrayemRCPCH. There was a small error in the filter at local health board level. I have fixed and pushed a change to the same PR to fix the transfer emails fix. Once that merges, this should close.
