### ISSUE TITLE
NHS number field doesn't appear for administrator users

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#728]
Issue raised by user

We are having trouble entering data on the web portal today (we have been trying to enter patients since yesterday with no issues until this morning). The above message is displayed when entering patient demographics (details redacted for data protection, but have actually been filled in).

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/77921b00-1fee-4b2e-adc6-ddbc08c4bb75)

**Comment by AmaniKrayemRCPCH** [comment]
They've stated that they tried 4 different patients, and that none of the information is invalid. 
They have added patients before with no difficulty. The issue started today and is ongoing.

**Comment by AmaniKrayemRCPCH** [comment]
Just spotted that it's missing the NHS number field. I was able to replicate this as an administrator user on the staging site:  

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/bd594cad-f593-4c93-8800-3c769613ef3f)

(this isn't real patient data)

**Comment by eatyourpeas** [comment]
Thanks for raising this @AmaniKrayemRCPCH 
I think this is to do with permissions of the person entering the data:
```
{% if request.user|has_group:"trust_audit_team_full_access, trust_audit_team_edit_access, epilepsy12_audit_team_edit_access, epilepsy12_audit_team_full_access" %}
  <div class="field">
    <label>NHS Number</label>
    {{form.nhs_number}} {% if form.nhs_number.errors %}
    <div class="ui pointing red basic label">{{form.nhs_number.errors}}</div>
    {% endif %}
  </div>
{% endif %}
```
It is a bit of legacy code before we introduced more granular permissions and Helen at the time wanted NHS number invisible from certain users. Of course the child cannot be saved without an NHS number, hence the error. I will remove the conditional test and this should fix this item, but I would be grateful if @nikyraja / @AmaniKrayemRCPCH you could independently send me the name of the user that I might check their permissions and ensure they are allocated to the correct group.

This will close once #726 merges
