### ISSUE TITLE
Fix ethnicity labelling

### ISSUE THREAD

**Issue by dc2007git** [rcpch/rcpch-audit-engine#730]
2 Tasks:

- [ ] When selecting ethnicity for a patient, the option from the NHS DMD for 'White British' actually shows up as 'Mixed British',  which is confusing. This corresponds to option A in the NHS DMD.
- [ ] The dropdown for ethnicities should ideally be in order, so 'White' categories are grouped together, 'Mixed' categories are grouped together

**Comment by eatyourpeas** [comment]
Can I check before making changes - is this the correct list to copy?
https://digital.nhs.uk/data-and-information/data-collections-and-data-sets/data-sets/mental-health-services-data-set/submit-data/data-quality-of-protected-characteristics-and-other-vulnerable-groups/ethnicity

**Comment by pacharanero** [comment]
Yes I believe those are the right codes.

The master list is here
https://www.datadictionary.nhs.uk/attributes/ethnic_category_code_2001.html
