### ISSUE TITLE
User log - show if 2FA set up

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#734]
I just wanted to ask if it was possible to log 2FA was set up in the user logs? It would make things easier for me when dealing with user queries. 

No worries if not!

**Comment by anchit-chandran** [comment]
What exactly do you mean by user logs and what's the required behaviour? This can be done, just trying to figure out the best place to put it. You want to be able to tell when exactly a user successfully completes setup of their 2fa?

**Comment by AmaniKrayemRCPCH** [comment]
Apologies I mean the logs of user log-in activity. 
<img width="533" alt="image" src="https://github.com/rcpch/rcpch-audit-engine/assets/126471383/efe8b136-f516-4c1c-9b40-68b164c1912d">

![image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/0d11400e-2cd5-47eb-9e47-60901dd9c9bb)
