### ISSUE TITLE
Add genetic cause - Constitutional mismatch repair deficiency (CMMRD) syndrome

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#735]
Add cause Constitutional mismatch repair deficiency (CMMRD) syndrome, as requested by user

**Comment by eatyourpeas** [comment]
Thank you. Could the work flow for these additions please include @coldunk who might provide the SNOMED code if able and I can then add these through the admin. What I have found is [here](https://termbrowser.nhs.uk/?perspective=full&conceptId1=764946008&edition=uk-edition&release=v20231122&server=https://termbrowser.nhs.uk/sct-browser-api/snomed&langRefset=999001261000000100,999000691000001104)
Constitutional mismatch repair deficiency syndrome (disorder)
SCTID: 764946008

**Comment by eatyourpeas** [comment]
closed
