### ISSUE TITLE
Free-text episode description - Mark complete once text is entered

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#737]
There's been some confusion around the free-text question, as it remains as 'incomplete' with a blue dot, even when text is entered. It is only marked as 'complete' with a pink tick after you click away. 

This has led to some confusion, with users thinking they haven't completed that section. 

Is it possible to mark as complete while text is being entered?

Let me know if this doesn't make sense. Happy to demonstrate.

**Comment by eatyourpeas** [comment]
fixed in the new-ui-fixes branch
