### ISSUE TITLE
Log in error - Request aborted page

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#738]
Sometimes when I log in, I am shown the below page. If I refresh the page, I can access it just fine. 
This doesn't affect my ability to use the platform, just flagging

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/79044672-7d9e-4aa1-9ba0-7e7a70d64cd0)

**Comment by anchit-chandran** [comment]
@pacharanero @eatyourpeas how do we want to handle this?

I think Marcus was right in that the CSRF error screen is just styled like the Debug=True screens (can see it says `"More information is available with DEBUG=True"`. I think this is a feature, not a bug - CSRF genuinely can't be verified for whatever reason (?some cached state) but it's fixed upon refreshing like amani mentioned. Just to confirm @AmaniKrayemRCPCH - login DOES work once you refresh?

Proposed solution: we change add a styling page for CSRF error as per the rest of the RCPCH error pages. If you guys agree, will close this issue and make a separate issue for that

**Comment by eatyourpeas** [comment]
I agree. Is it possible simply to redirect to 403?

**Comment by AmaniKrayemRCPCH** [comment]
Can confirm that it's fine once refreshed. I don't have to log in again.

**Comment by dc2007git** [comment]
> [@pacharanero](https://github.com/pacharanero) [@eatyourpeas](https://github.com/eatyourpeas) how do we want to handle this?
> 
> I think Marcus was right in that the CSRF error screen is just styled like the Debug=True screens (can see it says `"More information is available with DEBUG=True"`. I think this is a feature, not a bug - CSRF genuinely can't be verified for whatever reason (?some cached state) but it's fixed upon refreshing like amani mentioned. Just to confirm [@AmaniKrayemRCPCH](https://github.com/AmaniKrayemRCPCH) - login DOES work once you refresh?
> 
> Proposed solution: we change add a styling page for CSRF error as per the rest of the RCPCH error pages. If you guys agree, will close this issue and make a separate issue for that

Closing as resolved with refresh. @anchit-chandran can you make your separate issue for the CSRF-403 redirect?
