### ISSUE TITLE
Add SQL Explorer to the Admin pages to enable queries to be run by E12 internal staff

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#739]
As discussed in the Data Access meeting and documented in issue #683 we are going to use an initial approach of adding the SQL Explorer plugin into Django to enable queries to be run as required by trusted team members. We can trial this approach and review as required.

**Comment by eatyourpeas** [comment]
Really just a question. Could the team instead not have have tunnelled access to the postgresql database instead? They could be locked down to View only access and it would avoid having a dependency.

**Comment by mbarton** [comment]
[from sprint planning] we should convert this ticket into direct database access once #832 is complete. The analysts can then write SQL directly and we can iterate on what stays as bespoke reports and what we bring into the the app itself

**Comment by mbarton** [comment]
Analysts can now access the database read only directly
