### ISSUE TITLE
Cannot delete case in old cohort

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#743]
Under The Queen Elizabeth Hospital – King’s Lynn, there’s a child who’s been added with the wrong first paediatric assessment date, putting them in Cohort 5.

I can't edit the record or delete it. What would you suggest we do? 

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/ce397679-5037-4f15-8930-968fb405e66b)

I anticipate that this issue will happen again. Are we able to allow RCPCH staff to edit records in old cohorts? or edit first paediatric assessment dates?

**Comment by anchit-chandran** [comment]
@eatyourpeas do we disable it for Cases in the wrong Cohort? was this required functionality?

**Comment by eatyourpeas** [comment]
You should be able to delete the patient through the admin in the patients table. When I log in I can see them.
Several options here:
1. delete patients in the usual way through admin and reregister
2. allow patients to be editable by rcpch e12 staff in historical cohorts
3. all first paediatric assessment date to be editable for college staff
I think I favour option 2

**Comment by AmaniKrayemRCPCH** [comment]
I did try option 1, and got an error saying 'Cannot delete patient', although I may have done it wrong. 
Happy with 2 or 3, @nikyraja do you have a preference?

**Comment by AmaniKrayemRCPCH** [comment]
@eatyourpeas , just to follow up, I think option 3 would be ideal considering the number of queries we're getting to correct FPA after the form has been completed. 

I think users are getting to the performance summary, seeing missed KPIs, and realising that the date is wrong. This means that the performance summary is working to improve data quality!!! But does mean FPA date errors are only being spotted after the form is complete.

**Comment by nikyraja** [comment]
I would also favour option 3 in light of the above. It is great that the new platform is already minimising data entry errors, but particularly as users are still getting used to the new processes, it would be ideal for the E12 team to be able to edit the FPA dates. We had originally thought that it would be okay to delete and re-add patients when wrong dates were entered, but as the errors are being identified after all the data is entered, and that this is becoming a common issue, we need a way to edit the dates for users.

**Comment by pacharanero** [comment]
Option 3 has been implemented. @AmaniKrayemRCPCH @nikyraja if you would be able to confirm that you can change date of FPA in the E12 Live instance then we can close this issue.
