### ISSUE TITLE
Cannot save syndrome entry

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#745]
Cannot save syndrome entry. A user flagged this and I've been able to replicate in staging.

**Comment by AmaniKrayemRCPCH** [comment]
https://github.com/rcpch/rcpch-audit-engine/assets/126471383/ee2e0f9c-1cc9-47db-b8d4-536863e53bf3

**Comment by eatyourpeas** [comment]
Thanks @AmaniKrayemRCPCH
