### ISSUE TITLE
Redirect to Sign In page when a user is logged out?

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#748]
Just noticed that when one is logged out after the inactivity time expires, the page one is shown has no function:

![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/983686f2-6438-47c1-aeb3-5dd274d4a01f)

It would be better to just send users back to the Sign In page, which will save them a click, and I think users understand when they see a Sign In page that they must have been logged out automatically, this happens with banking apps and other secure portals.

![image](https://github.com/rcpch/rcpch-audit-engine/assets/2348385/51cae3c9-d191-4862-9a47-87cbead928e3)

**Comment by dc2007git** [comment]
@pacharanero having a think about edge cases, I think that if a user doesn't have the correct permissions to view a particular page and they are redirected to the login page then they may not understand that it's a permissions problem.

I've added a button to redirect the user to the sign in page, and also changed the text to signpost that it is likely a sign in problem.
