### ISSUE TITLE
time data '' does not match format '%Y-%m-%d' is a bit confusing for users

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#755]
Date pickers refresh after 1000ms due to the HTMX validation loop replacing the element with a new element. This means you can lose input focus half way through typing a year, for example. We should look at ways to improve this, although it is not a huge priority.

`time data '' does not match format '%Y-%m-%d'` should be rewritten to be easier for the layperson to understand

`Date supplied (9939-01-01) cannot be in the future for this measure!` could probably look better with a more human-formatted date

Totally ridiculous dates should be invalid (eg Year 200) - perhaps should just have a cutoff before which dates will be invalid.

**Comment by pacharanero** [comment]
Some info on HTMX repo Issues discussing the loss of focus issue, for context/ideas on how to solve https://github.com/bigskysoftware/htmx/issues/75

**Comment by eatyourpeas** [comment]
Duplicate now of #774 and should be fixed on merge of PR #775

**Comment by dc2007git** [comment]
Closing as per PR #775
