### ISSUE TITLE
Time to EEG field doesn't update

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#757]
If the user updates the 'EEG requested' date, the 'Time to EEG' field doesn't update alongside it

**Comment by pacharanero** [comment]
Interesting one. I am unable to replicate it actually. I'm on Staging now and have tried a variety of changes of dates and it does seem to update. There was a slight glitch noticed when the date was set to the future and it didn't immediately revert when I set it to an acceptable date, but this seems unrelated to the user report here.

https://github.com/rcpch/rcpch-audit-engine/assets/2348385/27e853db-4873-4be1-ac25-72fb1a9768d1

**Comment by anchit-chandran** [comment]
@AmaniKrayemRCPCH do you remember context in which you were facing this bug? If can't replicate, will close - can re open if we can find a way to replicate

**Comment by AmaniKrayemRCPCH** [comment]
It was a report from a user (lead clinician). 
"The automated time to EEG field doesn't update when the requested date was changed - user had to select no to EEG question and then yes and renter all dates"

**Comment by AmaniKrayemRCPCH** [comment]
Just noting that I also can't replicate this issue in staging as a lead clinician user.

**Comment by eatyourpeas** [comment]
I can't replicate this either. The wait time is calculated in the model on save and the new calculated wait time is update when the new partial template is rendered. Let's close this for the moment but can reopen if any other reports.
