### ISSUE TITLE
Styling differences in epileptic episode form upon Description 'Yes' being selected or 'No'

### ISSUE THREAD

**Issue by dc2007git** [rcpch/rcpch-audit-engine#762]
The Epilepsy and Seizure Type stylings change depending on whether you are editing the seizure record or are creating a new one. 

Here is the styling when Description has no choice selected or No:
![image](https://github.com/rcpch/rcpch-audit-engine/assets/65614251/bfa5383b-3f90-4ca0-8e1a-62cfaf86dc66)

And here is the styling when you press Yes on an episode's description

![image](https://github.com/rcpch/rcpch-audit-engine/assets/65614251/19f7d8c2-4076-4b63-a986-c732b886844b)

The generated E and S sections seem to fall outside of the appropriate rcpch_pink segment are that is defined in the html.

**Comment by anchit-chandran** [comment]
Will be something in the partial - generally wouldn't have thought we'd have separate partials for add vs edit as an `'edit'` is the same as adding, but with pre-filled values taken from the db. If these are separate, would be good to combine as leads to these kinds of incorrect duplication errors

**Comment by dc2007git** [comment]
@anchit-chandran thanks for the heads up. It looks like it's actually conditional dependent on whether the description aspect has a "Yes" or "No" or empty response (see the updated description above in the issue)

**Comment by dc2007git** [comment]
Resolved in #761
