### ISSUE TITLE
Password reset in local development not working

### ISSUE THREAD

**Issue by dc2007git** [rcpch/rcpch-audit-engine#767]
Upon entering my email address in the password reset button in local development (even for the first time), I get raised the following error:
![image](https://github.com/rcpch/rcpch-audit-engine/assets/65614251/5dad45e4-ce6a-47f6-91fc-49178dae6a14)

This is not the case in e12.rcpch.ac.uk - it is still fully functional there. However, it does happen even when running the live branch locally.

Can anyone replicate this problem while on the HEAD of development? @pacharanero @eatyourpeas @anchit-chandran

**Comment by dc2007git** [comment]
Note - this is fixed by removing the 'autoescape off' tag. I can't find a default value for autoescape in the django settings, so removing it should have the same level of autoescape security as having it set to off in the first place. @eatyourpeas is this correct?

**Comment by eatyourpeas** [comment]
Just before signing this off, do check the emails are formatted correctly. The autoescape template tag is used to escape symbols to html, for example < is converted to 'ampersandlt;' when set to True, which is the default.
This template contains email text as well as html. I think apostrophes escape to apostrophes, so will be unaffected. But if there are any other symbols, these will be escaped to html unless the flag is set to false.
