### ISSUE TITLE
User not receiving OTP email

### ISSUE THREAD

**Issue by nikyraja** [rcpch/rcpch-audit-engine#768]
A user is not receiving the one time password email token as part of the 2FA, however is receiving the reset password emails. We have asked them to check in with their local IT department in case there are blockers, but could we check if there are any issues on our side?

Could we reset their 2FA method to be via the app instead of email?

The use was from Medway here.

**Comment by eatyourpeas** [comment]
The user can reset their own OTP
<img width="285" alt="image" src="https://github.com/rcpch/rcpch-audit-engine/assets/1058647/323d189b-cf4e-4779-9869-fe2730380c2a">
which will lead to this screen:
<img width="598" alt="image" src="https://github.com/rcpch/rcpch-audit-engine/assets/1058647/09ebf5eb-4513-42e3-b8cd-3a8546047d24">
Following the link will lead here. Tick the box and disable the method of authentication:
<img width="554" alt="image" src="https://github.com/rcpch/rcpch-audit-engine/assets/1058647/05e8b9e2-5151-4cf9-b5d3-6070e16188cd">
which will lead back here:
<img width="565" alt="image" src="https://github.com/rcpch/rcpch-audit-engine/assets/1058647/8b78c17f-32d4-4c15-8b11-80183be236a4">
Steps from here are the same as on first log in.

**Comment by anchit-chandran** [comment]
Any further issues on this @nikyraja ? Will close if not

**Comment by dc2007git** [comment]
@nikyraja @AmaniKrayemRCPCH are we happy to close this issue?

**Comment by nikyraja** [comment]
Thanks Danny. I can confirm that this user has successfully logged onto the new platform. They did however have to switch to the OTP app, as they never received the OTP emails. 

I think we can close this, and perhaps re-open if another user encounters this issue? (no other users have reported this though)
