### ISSUE TITLE
Celery jobs should also save logs to file

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#790]
We have implemented Django file-based logging which enables us to investigate errors 'after the fact' where they occur on a VPS. However this does not extend to Celery jobs, which include some critical functionality such as email sending for password resets and new users - so we should either:

1. Implement similar rotating, file-based logging in Celery (preferred, as we will see everything, including stacktraces, if there is a problem)

1. Log in detail in Django when jobs are sent to a Celery task, so that it can be investigated if a Celery task fails for some reason.

1. Spend some time understanding Flower's UI and how to investigate a failed job in Flower/Celery that way - perhaps with Flower we just don't need file-based logging?

**Comment by mbarton** [comment]
We've removed Celery for now #828
