### ISSUE TITLE
Community paediatrics users appearing under multiple organisations

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#794]
When viewing a list of users under a 'community paediatrics' organisation, users from other community paeds organisations in other Trusts also appear. 

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/26e87d39-eb61-4d40-a86f-7a272c7ebb1d)

**Comment by AmaniKrayemRCPCH** [comment]
I can confirm, after testing on the dummy accounts, that lead clinicians can see users and patients from other community paediatrics teams outwith their trust. As such, flagging as a security issue and labelled as highest priority. 


![Image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/6f139882-1144-4fff-9ddb-a51f7d710371)

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/8fc22bc9-6f65-4982-ac4e-8b74f8fe4053)

There is no real patient/user data in the above screenshots.

**Comment by eatyourpeas** [comment]
Thanks @AmaniKrayemRCPCH for picking this up. Just goes to show how good the django `icontains` filter is. You are right that it has been filtering all parent organisations which are similar, ie that contain community in them. Be reassured that while they can view each others users and children, they cannot edit them at least. I have pushed a fix.
