### ISSUE TITLE
Visible Case IDs for each patient

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#799]
We've been having trouble communicating about patient records via email. IG has just confirmed that we can't share patient NHS numbers over email. 
We need a way of communicating about patients without using patient identifiable information (e.g. name, NHS no.). Please can each patient's pseudonymous case ID be made visible to users on the platform.

**Comment by eatyourpeas** [comment]
#800 will close this issue
<img width="574" alt="image" src="https://github.com/rcpch/rcpch-audit-engine/assets/1058647/51d9b6d5-1f2b-499c-9c75-77f99911ad35">

**Comment by pacharanero** [comment]
Repoening following E12 SPM call - @AmaniKrayemRCPCH @nikyraja because they have realised they will need a way to search by Case ID so that the other person can easily find the case in question, without having to hover over the (?).
