### ISSUE TITLE
request.user|has_group filter is broken

### ISSUE THREAD

**Issue by dc2007git** [rcpch/rcpch-audit-engine#807]
I've spotted a few instances throughout the code of request.user|has_group being used as a filter to conditionally render some elements depending on the user's group. 

It seems as though there is a bug with this filter however, as in all places where it is called with the group set to 'epilepsy12_audit_team_full_access', it fails to show its contents to the screen.

The fix to this is simple - we use `request.user.is_<role>` as is used (and works) elsewhere in the codebase.

**Comment by eatyourpeas** [comment]
If possible it would be better not to rely on groups, but rather test for the more granular permissions. This is what is used in most of the templates, and anything referencing groups preceded that.  You can use the `has_permission` property on user. I am happy to help with this if you need.

**Comment by dc2007git** [comment]
Yep have substituted in the `has_permissions` property where it's needed - but maybe then we should remove groups as this is unnecessary code?

**Comment by eatyourpeas** [comment]
yes i agree
