### ISSUE TITLE
information notes

### ISSUE THREAD

**Issue by coldunk** [rcpch/rcpch-audit-engine#81]
There are 7 steps to complete. The clock begins when the child has been registered. All fields are mandatory and can be completed in any order. Progress is saved automatically. The audit steps will not become active until eligibility has been confirmed, a lead site has been allocated, and the child has been registered.

Can this be rephrased:
There are 7 steps to complete. The 'clock begins' when the child has had their first paediatric assessment for the episode(s) ultimately treated as epileptic. The audit covers all that is achieved during the first 12 months of care after this first paediatric assessment.  Each child is assigned to a cohort according to their first paediatric assessment date and ultimately contributes to the audit against the trust who is providing ongoing 'secondary care' at the 12 months point after that first paediatric assessment.  All fields are mandatory and can be completed in any order. Progress is saved automatically. The audit steps will not become active until the child has been registered, a 'secondary care' trust site has been allocated and eligibility has been verified.

**Comment by eatyourpeas** [comment]
fixed by d0e2baba1c7d43a4c74ca381340412f91b191f58
