### ISSUE TITLE
Aggregations must only reflect children who have  COMPLETED 1 year of care

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#846]
Thanks @dc2007git and @eatyourpeas.

We've reflected on this and have reached the decision that it is okay to include CYP with partially completed records in the KPI calculations. Ie, a record doesn't have to be complete for it to be included in the trust, ICB, region etc aggregates in the dashboard.

**However, it is important that the aggregated KPI calculations in the dashboard only include CYP who have completed a full year of care, ie. one year has passed from their first paediatric assessment date.**   Apologies that I had not explicitly said this before.

Our annual analyses only include those CYP who have completed a full year (the deadline makes this true for everyone in the cohort) so it is important that the dashboard follows the same methodology. Otherwise, we will have instances where CYP are included in the live dashboards and the results are therefore different to our published outputs. This would cause confusion and effect the confidence users have in our data. 

The KPI info in the individual patient records (image attached) do not need this restriction to 1 year though. These can indicate for example that the KPI has not been met yet, and this gives clinicians time to rectify this before the year is completed, and promotes prospective data entry.
![image](https://github.com/rcpch/rcpch-audit-engine/assets/115647429/68648289-8d3d-4817-8cb4-03e1bb7b1859)

We can discuss this on Friday perhaps?

_Originally posted by @nikyraja in https://github.com/rcpch/rcpch-audit-engine/issues/831#issuecomment-1994144377_

**Comment by nikyraja** [comment]
Thank you!
