### ISSUE TITLE
Comment on login/register page to notify users that Epilepsy12 is a new platform

### ISSUE THREAD

**Issue by dc2007git** [rcpch/rcpch-audit-engine#850]
As per the in person discussion at the RCPCH HQ, we found that some users have attempted to login to Epilepsy12 with their credentials for the old audit platform.

We should therefore add a simple line of text on the login/register page to notify new users of this

@AmaniKrayemRCPCH @nikyraja let us know when you've come up with the text that you'd like us to place on the website

**Comment by dc2007git** [comment]
@AmaniKrayemRCPCH @nikyraja I've come up with this in the meantime:

For users of our old platform, please note that you require a new login to access this service. Contact your lead clinician or administrator for assistance.

**Comment by nikyraja** [comment]
Thank you @dc2007git !

Could the text please be:

'For users of the old platform (cohort 1 -5), please note that you will require a new username and password to access this new platform. Please contact your Lead clinician or epilepsy12@rcpch.ac.uk for assistance.'
