### ISSUE TITLE
Missing causes in dropdown

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#851]
Received this email from a user:
"In multiaxial diagnosis, under cause, my patient has Klinefelter (XXY) and SCN1A gene mutations- but I can find neither ?
Am I missing something ? I think I have found Klinefelter for a previous patient so was surprised"

It appears that causes from this list aren't appearing in the drop down - epilepsy12/constants/causes.py
All the SNOMED causes are still appearing.

I'm happy to try to find the SNOMED codes for the items from causes.py to unify the two lists, but that will take a little bit of time and will require approval from colin.

**Comment by eatyourpeas** [comment]
The epilepsy causes were originally seeded from a SNOMED refset which we have since added to. The lists in `constants.py` are not used. I did not know that Klinefelter was a cause of seizures? Would SCN1A not be a cause, and the Klinefelter a comorbidity? The easiest thing probably is to add Klinefelter and SCN1A SNOMED codes to those tables.

**Comment by AmaniKrayemRCPCH** [comment]
Ah makes sense! I'll go through the lists of causes in the constants and make sure they're all reflected in the SNOMED list, plus add Klinefelter. SCN1A mutation isn't in SNOMED, but Dravet syndrome is.

Will add another comment with any causes to be added

**Comment by AmaniKrayemRCPCH** [comment]
I've taken a look at this and added some causes from the old platform, which weren't in the SNOMED refset - https://github.com/rcpch/rcpch-audit-engine/issues/854

There are a number of genetic causes missing from SNOMED. To cover these, Colin's suggested that we add `Genetic disease (disorder) | 782964007` as a cause. 

So, for example, a kid with SCN1A mutation would select 'Dravet Syndrome' for syndrome and 'Genetic disease' for cause. At the moment, I presume users are just leaving the cause blank?

For the kids with genetic mutations, it may be useful to capture the specific gene, even if SNOMED doesn't provide that option. Is there a way we can do this? This is the list of gene abnormalities from Netsolving:

```
- UBE3A
- GLUT1
- SLC2A1
- MECP2
- SCN1A
- STXBP1
- CDKL5
- KCNQ2
- SCN2A
- KCNT1
- ARX
- FOXG1
- PCDH19
- GRIN2A
- Other
```

**Comment by nikyraja** [comment]
Thanks both. 

@eatyourpeas I think this is what we were discussing at conference? My understanding that it is okay for us to have causes on our list that don't have snowmed codes as we will then retain an up to date and relevant list, but we will still reference snowmed where codes exit.

So can the above just be added as causes? And can we add ones from epilepsy12/constants/causes.py which are currently not in the list?

**Comment by eatyourpeas** [comment]
Yes that is right. If there are SNOMED codes we should use them but the table can store causes where SNOMEDCT codes do not exist. For those, it would be good if Colin could confirm what name we store them as and we can add SNOMED codes or edit the name at a later date once added to SNOMED.

**Comment by eatyourpeas** [comment]
Sorry just coming back to this in relation to #854 
I have therefore not implemented 'genetic causes', and instead have added the individual gene mutations as separate causes. Where there is no SNOMED code I will leave the code out but add the name:

| gene defect | SNOMED CT ID |
|-------------|----------------|
| UBE3A | 722056009 |
| GLUT1 |   445252005 |
| SLC2A1 | 782911008 |
| MECP2 | 702816000 |
| SCN1A | 230437002 |
| STXBP1 | 768666006 |
| CDKL5 | 773230003 |
| KCNQ2 | 778001003 |
| SCN2A | 778002005 |
| KCNT1 | no code |
| ARX | 725163002 |
| FOXG1 | 702450004 |
| PCDH19 | 888801000000105 |
| GRIN2A | 770431001 |

<img width="836" alt="image" src="https://github.com/rcpch/rcpch-audit-engine/assets/1058647/bc9c608a-6b88-47c1-a088-6e2db37af120">

**Comment by nikyraja** [comment]
Thanks Simon! Let us know if there are any where we need to ask Colin for the most appropriate name to use etc (where there is no snowmed code)
