### ISSUE TITLE
Add causes

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#854]
Approved by Colin

Name | SCTID
--- | ---
Genetic disease (disorder) | 782964007
Klinefelter syndrome (disorder) | 22053006
Hypothalamic neuronal hamartoma (disorder) | 230791000
Traumatic brain injury (disorder) | 127295002
Angelman syndrome (disorder) | 76880004
Rett's disorder (disorder) | 68618008
Neuronal ceroid lipofuscinosis (disorder) | 42012007

**Comment by eatyourpeas** [comment]
<img width="688" alt="image" src="https://github.com/rcpch/rcpch-audit-engine/assets/1058647/941c0600-9ce9-4352-9309-bc73bfc132dc">
I have added these to live.
I am not sure we should be adding Genetic Disease (not wishing to overrule @coldunk who is the expert here) as it is too broad? I can of course add if you think we should.

**Comment by coldunk** [comment]
As long as then obliges us to put in a genotype.  Weirdly there isn’t snomed ct codes for genotypes so this was born from trying to have some type of snomed ct hook.  They must have some digital code nomenclature for genotypes??ColinOn 29 Mar 2024, at 15:04, Simon Chapman ***@***.***> wrote:﻿
image.png (view on web)
I have added these to live.
I am not sure we should be adding Genetic Disease (not wishing to overrule @coldunk who is the expert here) as it is too broad? I can of course add if you think we should.

**Comment by eatyourpeas** [comment]
I have added all the genotypes from the old platform and they all have SNOMED codes apart from KCNT1 which I have added as KCNT1-Related epilepsy as I found a paper referring to it as that.
