### ISSUE TITLE
Number of CYP incorrect in KPI table

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#863]
Looking at organisation 322 - 

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/f8e7d50c-02b3-4210-89de-47c9a0704a07)

They should actually have about 9 completed forms and 8 incomplete forms. It has remained at '6' since Friday. 

Trust, ICB, and Region-level data is not appearing.

**Comment by mbarton** [comment]
Thanks for the report @AmaniKrayemRCPCH, we will have a look.

Are other organisations updating?

**Comment by eatyourpeas** [comment]
sorry possibly closed this prematurely - I found the KPIAggregation models were not creating records in cohort 6 and have fixed this in development. I am not sure that is a fix for this specific issue though. I will dig some more. Thank you for identifying @AmaniKrayemRCPCH

**Comment by mbarton** [comment]
Thanks @eatyourpeas - after #860 production should be running all commits apart from #862

**Comment by mbarton** [comment]
> I found the KPIAggregation models were not creating records in cohort 6 and have fixed this in development

The logs on the production VM show that aggregations are being done for cohort 6 but not for trusts or regions

**Comment by eatyourpeas** [comment]
<img width="1336" alt="image" src="https://github.com/rcpch/rcpch-audit-engine/assets/1058647/a05f7cec-0238-44b3-b86d-77bcbce757de">
now fixed in live

**Comment by AmaniKrayemRCPCH** [comment]
Hi Simon, 

The table is currently showing 6 CYP for that organisation. 
Can confirm that there are more than 6 - at least 9 with completed audit records and a few more that are incomplete.

**Comment by eatyourpeas** [comment]
Are you sure all 9 have completed a full year of care?
