### ISSUE TITLE
cannot reset password

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#868]
Error reported by @coldunk. When trying to reset password, returns 500 - Server Error

I was able to reproduce - 

https://github.com/rcpch/rcpch-audit-engine/assets/126471383/0af7413f-b83a-4520-9b69-8c7dc826e8e7

**Comment by eatyourpeas** [comment]
I have just reset my password without difficulty on live and staging. Could you try again?

**Comment by AmaniKrayemRCPCH** [comment]
Has worked for me now too! Seems to be resolved.

**Comment by eatyourpeas** [comment]
closing now but @coldunk let me know if still ongoing problem

**Comment by coldunk** [comment]
Is working.  Cheers!
