### ISSUE TITLE
DESSCRIBE

### ISSUE THREAD

**Issue by coldunk** [rcpch/rcpch-audit-engine#87]
next to the letters.
can they include the text in some way as i think the meaning of the acronym will get lost otherwise.

Description
Epileptic, non-epileptic or uncertain
Seizure type
Syndrome
Cause
Relevant Impairments, behaviouaral, educational or emotional problems
<img width="32" alt="Screenshot 2022-08-27 at 15 21 42" src="https://user-images.githubusercontent.com/79205365/187034373-132ad7f8-84d6-4640-a27d-1f8d29aec029.png">

**Comment by eatyourpeas** [comment]
fixed by https://github.com/rcpch/rcpch-audit-engine/commit/90cfde588bb288f6c01db9795a0afb04743045f8
