### ISSUE TITLE
reword 'Recruitment closed'

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#871]
The wording on 'recruitment closed'/'actively recruiting' is a bit confusing. A user got in touch as they thought it meant that they cannot enter data for cohort 6.

What are our thoughts on rewording this? The deadline below should make it clear that data entry is still ongoing but maybe we can make it clearer. 
Maybe we don't even need the 'recruitment closed' statement, as it says 'submitting cohort' and 'active cohort' above.

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/5a5ca744-f15b-4b8d-8537-c6945097b00b)

**Comment by eatyourpeas** [comment]
hoping this fix is clearer?
<img width="437" alt="image" src="https://github.com/rcpch/rcpch-audit-engine/assets/1058647/77b41b00-a9eb-4b08-843f-94955eecc9eb">
