### ISSUE TITLE
Trust merger - Mersey and West Lancashire NHS Foundation Trust

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#885]
Trust merger to action:

`Southport and Ormskirk Hospital NHS Trust (RVY)` have merged with `St Helens and Knowsley Teaching Hopsital NHS Trust (RBN)` to form `Mersey and West Lancashire Teaching Hospitals NHS Foundation Trust (RBN)`.

The new trust details are:

```
  {
        "ods_code": "RBN",
        "trust_name": "MERSEY AND WEST LANCASHIRE TEACHING HOSPITALS NHS TRUST",
        "address_line_1": "WHISTON HOSPITAL",
        "address_line_2": "WARRINGTON ROAD",
        "town": "PRESCOT",
        "postcode": "L35 5DR",
        "country": "ENGLAND",
    },
```

**Comment by eatyourpeas** [comment]
Thanks @AmaniKrayemRCPCH 
For the dev & e12 team here are the steps to perform a Trust merger. It is all done in the django admin
- [ ] find Ormskirk and District General Hospital in the **Organisation** table
- [ ] In the **Trusts dropdown** change from Southport and Ormskirk to St Helen's and Knowsley Teaching Hospitals NHS Trust and save
- [ ] in the **Trusts table** find St Helen's and Knowsley Teaching Hospitals NHS Trust and update the name to Mersey and West Lancashire teaching hospitals nhs trust and any other details as necessary.
- [ ] in the **Trusts table**, find Southport and Ormskirk and click the active check box to false
Note that this assumes that one trust is swallowing another, and therefore the organisations are really just changing parents, leaving one trust entity childless. In the case where a new hospital is built or some new entity is incorporated we shall have to think again - after all, they got rid of CCGs and introduced ICBs only last year so none of this can be predicted.

**Comment by dc2007git** [comment]
@AmaniKrayemRCPCH thanks for this, will be actioned today! Just double checking - did any of the hospitals have any detail changes we can input also into the Django admin? So for example, Ormskirk & District General Hospital (RVY02) now has a different parent trust (RBN), so is it now RBN02? Cheers!

**Comment by dc2007git** [comment]
Closed after performing merger with @mbarton
