### ISSUE TITLE
Trust merger - Somerset NHS Foundation Trust

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#886]
Trust acquisition:

`Somerset NHS Foundation Trust (RH5)` and `Yeovil District Hospital NHS Foundation Trust (RA4)` merged, retaining the Somerset NHS Foundation Trust name and ODS code of RH5.

The details of Somerset NHS Foundation Trust remain as:
```

    {
        "ods_code": "RH5",
        "trust_name": "SOMERSET NHS FOUNDATION TRUST",
        "address_line_1": "TRUST MANAGEMENT",
        "address_line_2": "LYDEARD HOUSE",
        "town": "TAUNTON",
        "postcode": "TA1 5DA",
        "country": "ENGLAND",
    },
```

**Comment by mbarton** [comment]
@eatyourpeas do you know if this was done? In live Yeovil District Hospital appears under Somerset NHS Foundation Trust in the dropdown

**Comment by mbarton** [comment]
Done in https://github.com/rcpch/rcpch-audit-engine/commit/a1c20f3520eda53b646964ca28cb659845c3cb58
