### ISSUE TITLE
Trust name on organisation dashboard buttons

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#889]
Can these buttons have the Trust name instead of the organisation name.
Users sometimes don't realise that they can see data from other organisations in their Trust by following these buttons.

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/5be98b07-86f9-4458-8d0b-f4b0e23d31f9)

**Comment by eatyourpeas** [comment]
closed by #974
