### ISSUE TITLE
KPI data download for April

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#895]
We're hoping to update our Power BI dashboard on Wednesday 1st May. 
Can we be sent the KPI data download for May, as outlined in https://github.com/rcpch/rcpch-audit-engine/issues/791

Trust mergers don't need to be actioned by then, as we can action these before publication.

**Comment by mbarton** [comment]
I'll keep a list of issues that need to be fixed here as I or others raise them:

**Blockers**

- https://github.com/rcpch/rcpch-audit-engine/issues/899
- https://github.com/rcpch/rcpch-audit-engine/issues/900
- https://github.com/rcpch/rcpch-audit-engine/issues/901
- https://github.com/rcpch/rcpch-audit-engine/issues/910
- https://github.com/rcpch/rcpch-audit-engine/issues/907
- https://github.com/rcpch/rcpch-audit-engine/issues/912
- https://github.com/rcpch/rcpch-audit-engine/issues/924
- https://github.com/rcpch/rcpch-audit-engine/issues/931
- https://github.com/rcpch/rcpch-audit-engine/issues/934

**Nice to have**

- https://github.com/rcpch/rcpch-audit-engine/issues/913
- https://github.com/rcpch/rcpch-audit-engine/issues/914
- https://github.com/rcpch/rcpch-audit-engine/issues/915

**Comment by AmaniKrayemRCPCH** [comment]
The below issue may affect this

*  #901

**Comment by mbarton** [comment]
Thanks @AmaniKrayemRCPCH! @eatyourpeas and I will review that issue asap

**Comment by mbarton** [comment]
@AmaniKrayemRCPCH the download KPI button is now live in staging. It's a little confusingly placed on the organisation page even though it gives you data across all orgs but is only visible to RCPCH admins:

<img width="505" alt="Capture" src="https://github.com/rcpch/rcpch-audit-engine/assets/395805/a813d7eb-e25b-4679-b30e-b370e35185e8">

Could you try and it let me know if there's anything obviously missing. We'll investigate #901 before deploying this to production and of course can do some more rounds if the data isn't correct there, given staging has very limited data.

**Comment by AmaniKrayemRCPCH** [comment]
Thanks @mbarton! 

I've put some comments below in order of priority. I believe we can correct all of these ourselves after downloading, but it would be helpful if these were resolved (particularly the first one).

- [x] There are some extra Trusts in there that aren't part of the audit e.g. South East Coast Ambulance Service NHS Foundation Trust. There's also a number of closed Trusts. This was raised in #791. I believe Danny said in a meeting that this was resolved.  If it helps, it seems that none of the extra trusts have an associated ICB.

- [x] We're missing column 'uk' from National_level

- [x] There are a number of extra columns that are no longer needed: 
* CountryMeasure in Country_level
* ICBMeasure in ICB_level
* NHSregionMeasure in NHSregion_level
* NetworkMeasure in Network_level
* ukMeasure in National_level

- [x] Can we reorder the columns as below:
* in HBT_level = HBT, Measure, Percentage, Numerator, Denominator
* in ICB_level = ICB, Measure, Percentage, Numerator, Denominator
* in NHSregion_level = NHSregion, Measure, Percentage, Numerator, Denominator
* In Network_level = Network, Measure, Percentage, Numerator, Denominator
* in National_level = uk, Measure, Percentage, Numerator, Denominator

**Comment by mbarton** [comment]
Thanks so much for having a look!

The issue with trusts makes sense, I had to remove those changes from the last PR to get our tests to pass. I will try and put them back.

The other changes are easy fixes - I should be able to get to them this week.

**Comment by dc2007git** [comment]
@AmaniKrayemRCPCH would you like the Country_level sheet to also follow the order of Country, Measure, Percentage, Numerator, Denominator?

**Comment by AmaniKrayemRCPCH** [comment]
Yes please

**Comment by dc2007git** [comment]
Great thank you @AmaniKrayemRCPCH  - and would you also like columns such as NHSregionMeasure in NHSregion_level to be removed? i.e. the reordering list above is explicit, and each sheet mentioned should have only 5 columns?

**Comment by AmaniKrayemRCPCH** [comment]
Yep that's correct

**Comment by mbarton** [comment]
We believe the issues with the report showing data for one group against another one incorrectly are now resolved (https://github.com/rcpch/rcpch-audit-engine/pull/941)
