### ISSUE TITLE
MRI 'data incomplete' on completed records

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#901]
Spotted while creating a dummy patient on the staging site - William Crane

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/281257d6-2b62-42bd-b77c-8f25f6a7f4c0)

The record is complete. Measures needed for MRI calculation are syndrome (multiaxial diagnosis), DOB, and whether an MRI has been done. All of this info has been provided in the audit record.

**Comment by eatyourpeas** [comment]
In the example you post, no date has been set for the MRI, so the measure is still incomplete. I am loathe to touch it, but I am confident that if you set the dates, the measure will score.

**Comment by AmaniKrayemRCPCH** [comment]
There isn't a date set because an MRI hasn't been requested - 
![image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/5a0b6cbd-2180-4e99-aa0a-0da1ff34dbae)

Therefore, the KPI should be failed, instead of incomplete.

The KPI is met if they have an MRI within 6 weeks. If they have no MRI, or an MRI >6 weeks from referral, then it is not met.

**Comment by eatyourpeas** [comment]
Oh I see! Sorry Amani - the button was not set to 'No' when I looked at it. Yes I see this is an issue. I think a small thing in the calculation. Leave it with me and I will report back.

**Comment by AmaniKrayemRCPCH** [comment]
Thanks!
I've just spotted that the same applies for care planning

![image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/b9ee5ea4-d618-405e-a9cb-f0b670aabbee)

![image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/23054011-af16-4feb-b627-e5ea37ca257c)

**Comment by eatyourpeas** [comment]
Now fixed in staging
<img width="778" alt="image" src="https://github.com/rcpch/rcpch-audit-engine/assets/1058647/8410b915-c983-4f82-8f31-c9e7034bdb85">
