### ISSUE TITLE
Remove irrelevant trusts from KPI report

### ISSUE THREAD

**Issue by mbarton** [rcpch/rcpch-audit-engine#912]
Spin off from https://github.com/rcpch/rcpch-audit-engine/issues/895#issuecomment-2075179987

> There are some extra Trusts in there that aren't part of the audit e.g. South East Coast Ambulance Service NHS Foundation Trust. There's also a number of closed Trusts. This was raised in https://github.com/rcpch/rcpch-audit-engine/issues/791. I believe Danny said in a meeting that this was resolved. If it helps, it seems that none of the extra trusts have an associated ICB.

@AmaniKrayemRCPCH has sent me the list of trusts participating in the audit so we can cross reference, although that does not include some mergers that are [EDIT] already actioned in the platform.

I think the easiest way to proceed for now is to compare that list with ours and remove any extra. The removal is a three step process, remove from the seeding code and then remove manually from the Django admin in staging then live. We must double check no data has been entered under those trusts, even though the Django relation management should stop us deleting them if that's the case.

We need a longer term solution for actioning trust mergers but this issue is simply scoped to what we need to do to get the KPI report out of the door.

**Comment by AmaniKrayemRCPCH** [comment]
Just to be clear, there are mergers that _are_ actioned in the platform but _not_ in the reference list I sent. I don't think there are any more mergers for you to action on the platform. 

The reference comes from our cohort 5 analyses, where we didn't action some mergers because it wasn't feasible on the old platform. Now we will try to remain up-to-date with ODS.

**Comment by mbarton** [comment]
I think it might actually be better to derive a list of trusts from the `ParentODSCode` fields in the organisations list. That should ensure the report always includes the relevant trusts as we add and remove data at the lower organisation level.
