### ISSUE TITLE
Home button should redirect to organisation dashboard if user is logged in 

### ISSUE THREAD

**Issue by dc2007git** [rcpch/rcpch-audit-engine#930]
Instead of redirecting a logged in user to the organisation dashboard it takes you back to the audit homepage

**Comment by eatyourpeas** [comment]
So I started to implement this an realised that then there is no way of getting to the audit homepage for a logged in user. Is that what we want? I agree the home page does not add much in this situation.
Currently you land on the home page, and when logged in are redirected from the login screen to the selected organisation view. If you then click on home or the RCPCH logo, your are redirected back to the home page. 
If we redirect logged in users each time to the  organisation view, they will never be able to get back to the home page. This maybe desirable. What do people think?

**Comment by mbarton** [comment]
> there is no way of getting to the audit homepage for a logged in user. Is that what we want? I agree the home page does not add much in this situation

There's still the "Home" link on the right hand side but I agree it's better to just go to your organisation overview as home once you're logged in.
