### ISSUE TITLE
[Feedback from E12 Webinar 2024.05.02] MRI Intervention/Investigation timing options 

### ISSUE THREAD

**Issue by pacharanero** [rcpch/rcpch-audit-engine#940]
> "Some times MRI has already been performed before the Paediatric assessment requested by A&E
The platform wouldn’t allow that date to be entered"

@nikyraja @AmaniKrayemRCPCH Do we perhaps need MRI performance date to be allowable to be **before** the DOFPA?

> "there is a long wait for MRI under GA - as there is no option now for not performed yet i am unable to submit the form."

@nikyraja @AmaniKrayemRCPCH Do we perhaps need to add an option for "not yet done"?

> "Will the new platform accept dates that precede the first assessment, for things like MRI, psychology, diagnosis of autism etc?"

Similar to the first question, do we need these things to be able to be entered as performed before the DOFPA?

**Comment by AmaniKrayemRCPCH** [comment]
This is related to issue #904 

We need to consider how this affects KPI 5.
Will an MRI that occurs just before the FPA pass the KPI? How about if the MRI is 10 years before the FPA date?

We can set a cut off? e.g. MRIs that happen in the year prior to FPA still meet the KPI.
Or we can rely on the judgement of the clinicians entering the data? Presumably they'd only enter an MRI if they know it is a relevant and recent enough investigation for that CYP's epilepsy.

Alternatively, we say that we're only interested in the first year of care and won't consider MRIs prior to FPA. This may mean that some CYP that have had appropriate investigations don't meet the KPI, but we acknowledge that there are limitations to the audit design. 100% KPI attainment may not always reflect optimal care.

Thoughts? @nikyraja @coldunk

**Comment by nikyraja** [comment]
Thanks All. Have discussed this with @coldunk, and we have decided:

- MRI dates before the first assessment is okay, but still needs to be after the DOB
- KPI 5 can include all MRI dates within the first year of care, including those before the first assessment date (and then the 6 week timeframe can be applied)
- We can add a option for when and MRI isn't achieved. I think you have already added this button on the staging site, and this looks good thank you! Can the wording of the button please be updated to "MRI not achieved yet"? 

So I think the next steps would be to update the data validation for the MRI question to allow dates before FPA, add the not achieved yet button and then check that the KPI calculations aren't excluding dates before FPA. I don't imagine they would but it would be good to check. 

Note, that this can be done after the KPI export download #895 issue has been resolved.

**Comment by nikyraja** [comment]
After discussing the above in the sprint call (10/05/24), please can we instead:

- Re word the MRI question to 'Has an MRI been achieved'
- Keep the two date boxes
- Allow dates before FPA for both, but after DOB
- Not add a further option to say 'MRI not achieved yet'
- Keep all of these as mandatory questions

This should therefore not affect the KPI calculations. To confirm, for an eligible CYP to pass the KPI, they must
1) select 'yes' to 'Has an MRI been achieved' - selecting 'no' would be a fail
2) the input date must be within 6 weeks of request

We can add additional wording to the tooltip to clarify this for users. I will add the wording here/create another issue asap for this.

Thanks all!

**Comment by eatyourpeas** [comment]
I have made all those changes in a branch. Just to be sure E12 are happy with all dates (not just MRI), I would be grateful if you could confirm this table as what is needed?

| Model | Date | mandatory | earliest allowable date | other flags |
| ---- | ---- | ---- | ---- | ---- |
| Registration | first_paediatric_assessment_date | Yes | date_of_birth |   |
| Episode | seizure_onset_date | Yes | date_of_birth |   |
| Syndrome | syndrome_diagnosis_date | Yes | date_of_birth |   |
| Comorbidity | comorbidity_diagnosis_date | Yes | date_of_birth |   |
| Assessment | consultant_paediatrician_referral_date | Yes | date_of_birth |   |
| Assessment | consultant_paediatrician_input_date | Yes | consultant_paediatrician_referral_date |   |
| Assessment | paediatric_neurologist_referral_date | Yes | first_paediatric_assessment_date |   |
| Assessment | paediatric_neurologist_input_date | Yes | paediatric_neurologist_referral_date |   |
| Assessment | childrens_epilepsy_surgical_service_referral_date | Yes | first_paediatric_assessment_date |   |
| Assessment | childrens_epilepsy_surgical_service_input_date | No | childrens_epilepsy_surgical_service_referral_date |   |
| Assessment | epilepsy_specialist_nurse_referral_date | Yes | first_paediatric_assessment_date |   |
| Assessment | epilepsy_specialist_nurse_input_date | Yes | epilepsy_specialist_nurse_referral_date |   |
| Investigations | eeg_request_date | Yes | date_of_birth |   |
| Investigations | eeg_performed_date | Yes | eeg_request_date |   |
| Investigations | mri_brain_requested_date | Yes | date_of_birth |   |
| Investigations | mri_brain_reported_date | Yes | mri_brain_requested_date |   |
| AntiepilepsyMedicine | antiepilepsy_medicine_start_date | Yes | first_paediatric_assessment_date | is_rescue = False   |
| AntiepilepsyMedicine | antiepilepsy_medicine_stop_date | No | antiepilepsy_medicine_start_date |  is_rescue = False |
| AntiepilepsyMedicine | antiepilepsy_medicine_start_date | Yes | first_paediatric_assessment_date | is_rescue = True   |
| AntiepilepsyMedicine | antiepilepsy_medicine_stop_date | No | antiepilepsy_medicine_start_date |  is_rescue = True |
| Management | individualised_care_plan_date | Yes | first_paediatric_assessment_date |   |

**Comment by nikyraja** [comment]
Thanks Simon! All of those are correct, so happy for you to merge into live.
