### ISSUE TITLE
Focal seizure lateralisation - make optional

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#955]
A user raised that they have a CYP whose focal seizures are not lateralised. Discussed with Colin. Decided that the lateralisation field should be optional.

Under multiaxial diagnosis > episodes > epileptic > focal onset

![Image](https://github.com/rcpch/rcpch-audit-engine/assets/126471383/8f5f83cf-5b87-4a2a-8250-150885fcf026)

**Comment by eatyourpeas** [comment]
Are they in the middle? How about if instead we add a 'not-known' option but leave it as mandatory? It would be quicker to implement and would have no implication that way for all the children where this has already been scored?

**Comment by AmaniKrayemRCPCH** [comment]
Thoughts @nikyraja @coldunk ?

**Comment by eatyourpeas** [comment]
So actually looking at this I think both options are equally doable. I still think an unknown option that is mandatory is cleaner, but actually don't mind either option.

**Comment by nikyraja** [comment]
Thanks both - happy to have a 'unknown' option and keep the question mandatory.

**Comment by eatyourpeas** [comment]
Fixed with next merge
<img width="713" alt="image" src="https://github.com/rcpch/rcpch-audit-engine/assets/1058647/7995f408-0c08-4df7-8d67-96e54cc30828">
