### ISSUE TITLE
Associated trusts

### ISSUE THREAD

**Issue by coldunk** [rcpch/rcpch-audit-engine#97]
with regards to the trusts associated with each child during their first year of care:

Each child by definition should have

A **Secondary Care NHS Trust** that undertook the first paediatric assessment.   (Can be any community or NHS hospital trust)

An ongoing **Secondary Care NHS Trust** that is providing ongoing care for the epilepsy  (Can be community or hospital trust, may or may not be the same as initial trust ...the audit vehicle allows transfer of the child to the auditing trust and it is the assigned trust at 1 year following the first paediatric assessment which is accountable for submission and the audit results for that child)
(Can be community or hospital trust).  

Some may additionally have 
An NHS trust providing **Tertiary Paediatric Neurology NHS Trust** care (maybe same trust as that providing secondary care or different)

Some may additionally have 
An NHS trust providing **CESS NHS Trust** care (maybe same trust as secondary and tertiary or different).  There are only 5 CESS centres

I would take the word 'lead' out as that is subjective and contestable!  I would avoid word 'centre'.  Can you tell i have anti-gravitational and anti-hierarchical issues!

**Comment by eatyourpeas** [comment]
fixed with [09eeaa9](https://github.com/rcpch/rcpch-audit-engine/commit/09eeaa9eb859ed4ebf920b4a39abdf78b00a1f0a)

**Comment by eatyourpeas** [comment]
Sorry closed this by mistake
I have refactored the eligibility criteria then closed the wrong issue!

I will change the wording
As it stands we capture if a hospital is 'lead' or not (by that I had meant is responsible for audit submission), whether is manages the general paediatric care or not (as this might be different), whether it is is a tertiary neurology hospital and whether it is an epilepsy surgery centre. In theory it is possible for 4 hospitals to be actively involved in the care of the same child, though only one would be 'lead' and therefore had responsibility for audit submission. 
The benefit of this design is that it allows ownership for the audit submission, and an audit trail if care is transferred. It is possible to build a granular history of trusts that have had past responsibilities in either of these four areas (lead, general paediatrics, neurology and surgery), as well as report how many trusts are actively involved, compared with how many trusts have been previously involved.

I think reading between the lines this meets your requirements, even if the wording wrong? Please change the nomenclature for me if you are happy with the broad principle. I am not sure if my list of hospital trusts includes children's community centres. It does seem to include private hospitals and even CAMHS units. Do you have a way to check?
