### ISSUE TITLE
Three organisations to add

### ISSUE THREAD

**Issue by AmaniKrayemRCPCH** [rcpch/rcpch-audit-engine#984]
Under Hywel Dda UHB in Wales

1)      7A2AA - Glangwili General Hospital, Dolgwili Road, Carmarthen, Carmarthenshire, SA31 2SF.
2)      7A2BM - Withybush General Hospital, Fishguard Road, Haverfordwest,  Pembrokeshire, SA61 2PZ. 
3)      7A2P7 - Elizabeth Williams Clinic, Mill Lane, Llanelli, Carmarthenshire, SA15 3SE. 

Apologies for not providing all the details! I'm short on time at the moment

**Comment by dc2007git** [comment]
@AmaniKrayemRCPCH it looks like Glangwili General Hospital shares an ODS code with GLANGWILI HOSPITAL CHILD HEALTH SECTION, which is already in E12 as an organisation.

E12 can't have more than 1 organisation of the same ods code. Is this therefore maybe an update to GLANGWILI HOSPITAL CHILD HEALTH SECTION (rename, change postcode)?

**Comment by dc2007git** [comment]
@AmaniKrayemRCPCH additionally, Elizabeth Williams Clinic has already been entered into E12, with the same information as you have posted above

**Comment by AmaniKrayemRCPCH** [comment]
Apologies! I had just listed the info that the user gave me without checking against the platform. 

Let's keep Glangwili Hospital and Elizabeth Williams clinic as is. 

Thanks!

**Comment by dc2007git** [comment]
No worries! Thanks for the reply :)
