### ISSUE TITLE
MRI dates

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/rcpch-audit-engine#991]
![image](https://github.com/rcpch/rcpch-audit-engine/assets/1058647/332133d1-2b87-4422-901e-c7da592ee08f)

**Comment by eatyourpeas** [comment]
This one is a little puzzling @nikyraja as i am finding I can enter that date without difficulty. Might you be happy to checkin with the user and get a bit more detail?

**Comment by nikyraja** [comment]
I've checked the record and from my point of view, the date has been entered and recording correctly. The MRI KPI has also been correctly marked as achieved for this child. 

Could it be a bug where the error messages are still appearing for users, but for our accounts its working?

Below is a screenshot of my view, and then a screenshot of the users view of the same record on the same day - not sure why they are different
<img width="589" alt="MRI Niky screenshot" src="https://github.com/rcpch/rcpch-audit-engine/assets/115647429/1e99d9b7-48e6-4190-a58f-bd1583b512c1">
![MRI user screenshot](https://github.com/rcpch/rcpch-audit-engine/assets/115647429/50a90c10-a672-4716-86f3-4e669601b285)

When I logged onto the staging site as a lead clinician, I was able to enter MRI dates before the first assessment though...

**Comment by eatyourpeas** [comment]
I think the agreement finally was that MRI dates pre-FPA were allowed (#940) - see table in this issue. I am afraid I cannot explain what is happening for this user - is it possible to explore with them how they are entering dates and if/when they are pressing the set button? It should not matter what order, but the validation would be most logically followed if the request date is entered and set before the performed date. 
Given that it is working for you, perhaps I will close this here but do please reopen if this is an ongoing problem.
