### ISSUE TITLE
Incorrect measure names on KPI export

### ISSUE THREAD

**Issue by nikyraja** [rcpch/rcpch-audit-engine#997]
After downloading the KPIs today, I noticed that the measures on the exported excel file are slightly wrong, which means power Bi doesn't pick them up correctly. This was true for every level of granularity. 

Specifically, KPI 1, 3a and 10 were incorrect, but here is a complete list of what they should be:

```
1.  Paediatrician with expertise
2.  Epilepsy specialist nurse
3a. Tertiary involvement
3b. Epilepsy surgery referral
4.  ECG
5.  MRI
6.  Assessment of mental health issues
7.  Mental health support
8.  Sodium valproate
9a. Comprehensive care planning agreement
9b. Comprehensive care planning content
10. School Individual Health Care Plan
```

Please could these be corrected?

**Comment by nikyraja** [comment]
Hello, Is there any way we can get this fixed for the next monthly download on 1 August please?

**Comment by dc2007git** [comment]
@mbarton one of the points in the sprint was to action this issue before the first of august. Simon and I are away for the next two weeks so would you be able to action this please? Cheers!

**Comment by mbarton** [comment]
@nikyraja this change is now live

**Comment by nikyraja** [comment]
great thank you!

**Comment by nikyraja** [comment]
KPI 10 is still showing as the incorrect name. 

It is currently 'School Individual Healthcare Plan', but should be 'School Individual **Health Care** Plan'. Please can you update this?

**Comment by eatyourpeas** [comment]
all done
